lib/JsonParserGeneratorRK/examples/2-generator/2-generator-JsonParserGeneratorRK.cpp File Reference
#include `Particle.h`
#include `JsonParserGeneratorRK.h`
Functions
void runTest ()
void setup ()
void loop ()
Variables
const unsigned long TEST_RUN_PERIOD_MS = 10000
unsigned long lastRun = 0
Function Documentation
loop()
void loop ()
Definition at line 15 of file 2-generator-JsonParserGeneratorRK.cpp.
References runTest().
            {
    if (millis() - lastRun >= TEST_RUN_PERIOD_MS) {
        lastRun = millis();
        runTest();
    }
}
runTest()
void runTest ()
Definition at line 22 of file 2-generator-JsonParserGeneratorRK.cpp.
References JsonBuffer::getBuffer(), JsonWriter::insertKeyValue(), and JsonWriterAutoObject::JsonWriterAutoObject().
Referenced by loop().
               {
    // This creates a buffer to hold up to 256 bytes of JSON data (good for Particle.publish)
    JsonWriterStatic<256> jw;
    // Creating a scope like this in {} with a JsonWriterAutoObject in it creates an object,
    // and automatically closes the object when leaving the scope. This is necessary because
    // all JSON values must be in either an object or an array to be valid, and JsonWriter
    // requires all startObject to be balanced with a finishObjectOrArray and JsonWriterAutoObject
    // takes care of doing that automatically.
    {
        JsonWriterAutoObject obj(&jw);
        // Add various types of data
        jw.insertKeyValue("a", true);
        jw.insertKeyValue("b", 1234);
        jw.insertKeyValue("c", "test");
    }
    // Verify the results
    if (strcmp(jw.getBuffer(), "{\"a\":true,\"b\":1234,\"c\":\"test\"}")) {
        Serial.printlnf("test mismatch got %s", jw.getBuffer());
        return;
    }
    Serial.println("test passed!");
}
setup()
void setup ()
Definition at line 11 of file 2-generator-JsonParserGeneratorRK.cpp.
             {
    Serial.begin(9600);
}
Variable Documentation
lastRun
unsigned long lastRun = 0
Definition at line 6 of file 2-generator-JsonParserGeneratorRK.cpp.
TEST_RUN_PERIOD_MS
const unsigned long TEST_RUN_PERIOD_MS = 10000
Definition at line 5 of file 2-generator-JsonParserGeneratorRK.cpp.