src/2020_photon_code.cpp File Reference
#include `Particle.h`
#include <MQTT.h>
#include <MFRC522.h>
#include `Commandparser.h`
#include <JsonParserGeneratorRK.h>
Macros
#define CHARGEROFFSET 0
constant that sets for which Photon this program is intended
#define DEBUGPORT Serial
#define SIZEOFUSERLIST 2
#define SS_PIN_CHARGER1 A1
#define SS_PIN_CHARGER2 A2
#define RST_PIN A0
#define EXTRA_DIGITAL_BREAKOUT_1 D0
#define EXTRA_DIGITAL_BREAKOUT_2 D1
#define EXTRA_DIGITAL_BREAKOUT_3 D3
#define WAKEUP_OLIMEX D2
#define RESET_OLIMEX D4
#define PILOT_FEEDBACK_CAR_1 A6
#define PILOT_FEEDBACK_CAR_2 A7
#define AUTHENTICATION_CAR1 D5
#define AUTHENTICATION_CAR2 D6
#define EXTRA D7
Functions
int resetOlimex (String input)
Sends reset signal to EV charger controller.
int WifiSignal (String input)
Return wifi strength.
int resetParticle (String input)
Resets Photon.
int progModeOlmx (String input)
Sets Olimex into programming mode.
void blinkRFIDled (int charger, int action)
unused function to blink the Photon LED
int activeCharger ()
Return 1 if socket 1 is used, 2 if socket 2 is used, and 3 if both are in use.
int switchTest (String valueString)
Switches between renewable mode (-input `true`) and manual setpoint mode.
int maxCurrentC1 (String setPointStr)
Sets max Current output at socket 1 in manual mode.
int maxCurrentC2 (String setPointStr)
Sets max Current output at socket 2 in manual mode.
int maxCurrentC1_test (unsigned int setPoint)
Sets max Current output at socket 1/3 in renewable mode and publishes new setpoint at `HANevse/photonMaxC1` or C3.
int maxCurrentC2_test (unsigned int setPoint)
Sets max Current output at socket 2/4 in renewable mode and publishes new setpoint at `HANevse/photonMaxC2` or C4.
 String getUserIdAtSocket (int socket)
Returns RFID tag at the asked socket.
void allowUser_callback (byte *payload, unsigned int length)
Callback function to process and execute approval or denial to charge from Pi, then MQTT publish reason to website GUI.
int initRFID (String input)
Initialises RFID reader.
bool readRFIDCard (int Charger)
Checks and reads RFID tag at the asked socket, then MQTT publishes it for Pi.
void setup ()
Inital setup for pin assignments and serial links start.
void loop ()
Main running function that executes all other functions; runs over 5times/second.
int readSerialOlimex ()
void reconnect (void)
Function to reconnect to MQTT server if not connected and subscribe to needed topics.
void callback (char *topic, byte *payload, unsigned int length)
Main function for MQTT client to check for new messages and execute callback functions.
void charToString (const char in[], String &out)
Deprecated function to convert char to String - the String class already has one.
void getMeasure_callback (byte *payload, unsigned int length)
Callback function to automatically set max Currents from MQTT message if in renewable mode.
 STARTUP (WiFi.selectAntenna(ANT_EXTERNAL))
void add_Measurement (float phaseVoltageL1, float phaseVoltageL2, float phaseVoltageL3, float currentL1, float currentL2, float currentL3, float Frequency, unsigned long Timestamp, int socketId=0, String userId=`00`)
Function ran for each socket every 30s in main loop to send measurements through MQTT.
Variables
float Current [2][3]
float Power [2][3]
float PhaseVoltage [2][3]
float LineVoltage [2][3]
float Energy [2]
float Frequency [2]
float CurrentList [20]
int numberOfZeroReadings [2]
 String UIDtagCharger1 =`No ID`
var to hold swiped RFID tag at first socket
 String UIDtagCharger2 =`No ID`
var to hold swiped RFID tag at second socket
 MQTT client (`broker.hivemq.com`, 1883, MQTT_DEFAULT_KEEPALIVE, callback, 512)
MQTT client details; do not set last number to over 512!
 String test = `0`
int counter =1
 MFRC522 mfrc522_Charger1 (SS_PIN_CHARGER1, RST_PIN)
 MFRC522 mfrc522_Charger2 (SS_PIN_CHARGER2, RST_PIN)
unsigned long LatestStartTime [2] ={0,0}
Holds latest start of new charge if charger is in use.
bool handledCharger =0
Holds last handled socket (0 for first socket)
 String ShareVar
bool TESTCASE = false
var that holds the charging mode (TRUE = renewable)
ushort Pianswer =0
var that holds answer from Pi but is unused now
 String currentStr =``
unsigned int nextTime [2] = {30000,30000}
Next timestamp to publish measurements in ms.
Macro Definition Documentation
AUTHENTICATION_CAR1
#define AUTHENTICATION_CAR1 D5
Definition at line 76 of file 2020_photon_code.cpp.
AUTHENTICATION_CAR2
#define AUTHENTICATION_CAR2 D6
Definition at line 77 of file 2020_photon_code.cpp.
CHARGEROFFSET
#define CHARGEROFFSET 0
constant that sets for which Photon this program is intended
For Photon 1 set it to 0, for Photon 2 set to 2. Any more and program would need to be edited.
Definition at line 59 of file 2020_photon_code.cpp.
DEBUGPORT
#define DEBUGPORT Serial
Definition at line 60 of file 2020_photon_code.cpp.
EXTRA
#define EXTRA D7
Definition at line 78 of file 2020_photon_code.cpp.
EXTRA_DIGITAL_BREAKOUT_1
#define EXTRA_DIGITAL_BREAKOUT_1 D0
Definition at line 69 of file 2020_photon_code.cpp.
EXTRA_DIGITAL_BREAKOUT_2
#define EXTRA_DIGITAL_BREAKOUT_2 D1
Definition at line 70 of file 2020_photon_code.cpp.
EXTRA_DIGITAL_BREAKOUT_3
#define EXTRA_DIGITAL_BREAKOUT_3 D3
Definition at line 71 of file 2020_photon_code.cpp.
PILOT_FEEDBACK_CAR_1
#define PILOT_FEEDBACK_CAR_1 A6
Definition at line 74 of file 2020_photon_code.cpp.
PILOT_FEEDBACK_CAR_2
#define PILOT_FEEDBACK_CAR_2 A7
Definition at line 75 of file 2020_photon_code.cpp.
RESET_OLIMEX
#define RESET_OLIMEX D4
Definition at line 73 of file 2020_photon_code.cpp.
RST_PIN
#define RST_PIN A0
Definition at line 67 of file 2020_photon_code.cpp.
SIZEOFUSERLIST
#define SIZEOFUSERLIST 2
Definition at line 61 of file 2020_photon_code.cpp.
SS_PIN_CHARGER1
#define SS_PIN_CHARGER1 A1
Definition at line 65 of file 2020_photon_code.cpp.
SS_PIN_CHARGER2
#define SS_PIN_CHARGER2 A2
Definition at line 66 of file 2020_photon_code.cpp.
WAKEUP_OLIMEX
#define WAKEUP_OLIMEX D2
Definition at line 72 of file 2020_photon_code.cpp.
Function Documentation
activeCharger()
int activeCharger ()
Return 1 if socket 1 is used, 2 if socket 2 is used, and 3 if both are in use.
Definition at line 195 of file 2020_photon_code.cpp.
References Current.
                    {
    int number = 0;
    for (int i=0; i<3; i++) {
        if (Current[0][i] != 0.0) {
            number += 1;
            break;
        }
    }
    
    for (int i=0; i<3; i++) {
        if (Current[1][i] != 0.0) {
            number += 2;
            break;
        }
    }
    
    return number;
}
add_Measurement()
void add_Measurement (float phaseVoltageL1, float phaseVoltageL2, float phaseVoltageL3, float currentL1, float currentL2, float currentL3, float Frequency, unsigned long Timestamp, int socketId = 0, String userId = `00`)
Function ran for each socket every 30s in main loop to send measurements through MQTT.
Definition at line 510 of file 2020_photon_code.cpp.
                                                                                                           
                                                                                                                  
         {
    
    //< Filter to skip if current values are impossibly high or under 0.1A
    //if ((currentL1 > 50.0)||(currentL2 > 50.0)||(currentL3 > 50.0))
    // return;
    //if ((currentL1 < 0.1)&&(currentL2 < 0.1)&&(currentL3 < 0.1))
    // return;
    //This rounds floats to 3 decimal places
    // float newvar = (float)(((int)(oldvar * 1000 + .5)) / 1000);
    
    // phaseVoltageL1 = (float)(((int)(phaseVoltageL1 * 1000 + .5)) / 1000);
    // phaseVoltageL2 = (float)(((int)(phaseVoltageL2 * 1000 + .5)) / 1000);
    // phaseVoltageL3 = (float)(((int)(phaseVoltageL3 * 1000 + .5)) / 1000);
    // currentL1 = (float)(((int)(currentL1 * 1000 + .5)) / 1000);
    // currentL2 = (float)(((int)(currentL2 * 1000 + .5)) / 1000);
    // currentL3 = (float)(((int)(currentL3 * 1000 + .5)) / 1000);
    // Frequency = (float)(((int)(Frequency * 1000 + .5)) / 1000);
    JsonWriterStatic<512> jsonMessage;
        {
        JsonWriterAutoObject obj(&jsonMessage);
        // Add various types of data
        jsonMessage.insertKeyValue("V1", phaseVoltageL1);
        jsonMessage.insertKeyValue("V2", phaseVoltageL2);
        jsonMessage.insertKeyValue("V3", phaseVoltageL3);
        jsonMessage.insertKeyValue("I1", currentL1);
        jsonMessage.insertKeyValue("I2", currentL2);
        jsonMessage.insertKeyValue("I3", currentL3);
        //jsonMessage.insertKeyValue("P", Power);
        //jsonMessage.insertKeyValue("E", Energy);
        jsonMessage.insertKeyValue("F", Frequency);
          
        jsonMessage.insertKeyValue("UserID", userId);
        jsonMessage.insertKeyValue("SocketID", socketId);
        jsonMessage.insertKeyValue("Time", Timestamp);
        }
    for(int i=0; i<3; i++) {
        if(client.publish("HANevse/photonMeasure", jsonMessage.getBuffer())) {
            break;
        }
    }
}
allowUser_callback()
void allowUser_callback (byte * payload, unsigned int length)
Callback function to process and execute approval or denial to charge from Pi, then MQTT publish reason to website GUI.
Definition at line 438 of file 2020_photon_code.cpp.
References client, String::concat(), String::operator=(), Pianswer, UIDtagCharger1, and UIDtagCharger2.
                                                            {
    char payl[length+1];
    char *endchar;
        
    memcpy(payl, payload, length);
    payl[length] = NULL;
    int port = (int) strtol(payl, &endchar, 10);
    //action=1 successfully start new charge (charger is free and last stopped session > 20 sec ago)
    //action=2 charger is free, but you already swiped the card in the last 20 sec (second swipe within
       20sec)
    //action=3 charger is occupied by another user
    //action=4 succesful stop of charge session
    //action=5 you just started a charge at this charger, but had another consecutive RFID swipe within 20
       seconds
    //action=6 you are already charging at another charger
    //action=7 succesful RFID read, but you are not in the userlist
    int socketNr = port - 1 - CHARGEROFFSET;
    
    String topic_str = "HANevse/photonConverted/";
    topic_str.concat(port);
    endchar = endchar + 1;
    if (port == (1 + CHARGEROFFSET))
        port = AUTHENTICATION_CAR1;
    else if (port == (2 + CHARGEROFFSET))
        port = AUTHENTICATION_CAR2;
    else
        return; //port = EXTRA;
        
    int retPi = (int) strtol(endchar, &endchar, 10);
    Pianswer = retPi;
    // if (Pianswer == 0)
        // Pianswer = 9;
    switch(retPi) {
        case 1:
            digitalWrite(port, HIGH);
            LatestStartTime[socketNr] = Time.now();
            client.publish(topic_str, "successful start new charge");
            break;
        case 2:
            client.publish(topic_str, "charger is free, but card was swiped in the last 20 sec");
            break;
        case 3:
            client.publish(topic_str, "charger is occupied by another user");
            break;
        case 4:
            digitalWrite(port, LOW);
            if (socketNr == 0)
                UIDtagCharger1="No ID";
            else if (socketNr == 1)
                UIDtagCharger2="No ID";
            client.publish(topic_str, "successful stop charge session");
            break;
        case 5:
            client.publish(topic_str, "consecutive RFID swipe within 20s of new charge start");
            break;
        case 6:
            client.publish(topic_str, "you are already charging at another charger");
            break;
        case 7:
            client.publish(topic_str, "you are in the userlist, but not verified by admin");
            break;
        case 8:
            client.publish(topic_str, "successful RFID read, but you are not in the userlist");
            break;
        default:
            client.publish(topic_str, "ERROR: unknown scenario");
        
    }
    
}
blinkRFIDled()
void blinkRFIDled (int charger, int action)
unused function to blink the Photon LED
Definition at line 179 of file 2020_photon_code.cpp.
                                          {
    //action=1 succesfull start new charge (charger is free and last stoped session > 20 sec ago)
    //action=2 charger is free, but you allready swiped the card in the last 20 sec (second swipe within
       20sec)
    //action=3 charger is occupied by annother user
    //action=4 succesful stop this charge session
    //action=5 you just started a charge on this charger, but have another consecutive RFID read/swipe
       within 20 seconds
    //action=6 you are already charging at another charger
    //action=7 succesfull RFID read, but you are not in the userlist
    
    digitalWrite(D7,HIGH);
    delay(100);
    digitalWrite(D7,LOW);
    return;
}
callback()
void callback (char * topic, byte * payload, unsigned int length)
Main function for MQTT client to check for new messages and execute callback functions.
Definition at line 671 of file 2020_photon_code.cpp.
References maxCurrentC1(), maxCurrentC2(), String::operator=(), resetOlimex(), resetParticle(), switchTest(), test, and TESTCASE.
                                                               {
    test = "99";
    time_t time = Time.now();
    //DEBUGPORT.println(time);
    DEBUGPORT.print("MQTT>\tCallback function is called at: ");
    DEBUGPORT.println(Time.format(time, TIME_FORMAT_DEFAULT));
    if (CHARGEROFFSET==0) {
         if (strcmp(topic, "HANevse/allowUser")==0)
        {
            allowUser_callback(payload, length);
            //client.publish("HANevse/photonConverted", "test photon responds");
        }
        else
         if ((strcmp(topic, "HANevse/energyMeter")==0) && TESTCASE)
        {
            getMeasure_callback(payload, length);
            //client.publish("HANevse/photonTest", "test photon responds");
        }
        else
         if (strcmp(topic, "HANevse/resetOlimex")==0)
        {
            char payl[length+1];
            memcpy(payl, payload, length);
            payl[length] = NULL;
            resetOlimex(payl);
        }
        else
         if (strcmp(topic, "HANevse/resetPhoton")==0)
        {
            resetParticle("1");
        }
        else
         if (strcmp(topic, "HANevse/switchTest1")==0)
        {
            char payl[length+1];
            memcpy(payl, payload, length);
            payl[length] = NULL;
            switchTest(payl);
        }
        else
         if ((strcmp(topic, "HANevse/maxC1")==0) && !TESTCASE)
        {
            char payl[length+1];
            memcpy(payl, payload, length);
            payl[length] = NULL;
            maxCurrentC1(payl);
            //client.publish("HANevse/photonTest", "test photon responds");
        }
        else
         if ((strcmp(topic, "HANevse/maxC2")==0) && !TESTCASE)
        {
            char payl[length+1];
            memcpy(payl, payload, length);
            payl[length] = NULL;
            maxCurrentC2(payl);
            //client.publish("HANevse/photonTest", "test photon responds");
        }
    }
    else {
         if (strcmp(topic, "HANevse/allowUser")==0)
        {
            allowUser_callback(payload, length);
            //client.publish("HANevse/photonConverted", "test photon responds");
        }
        else
         if ((strcmp(topic, "HANevse/energyMeter")==0) && TESTCASE)
        {
            getMeasure_callback(payload, length);
            //client.publish("HANevse/photonTest", "test photon responds");
        }
        else
         if (strcmp(topic, "HANevse/resetOlimex")==0)
        {
            char payl[length+1];
            memcpy(payl, payload, length);
            payl[length] = NULL;
            resetOlimex(payl);
        }
        else
         if (strcmp(topic, "HANevse/resetPhoton")==0)
        {
            resetParticle("1");
        }
        else
         if (strcmp(topic, "HANevse/switchTest2")==0)
        {
            char payl[length+1];
            memcpy(payl, payload, length);
            payl[length] = NULL;
            switchTest(payl);
        }
        else
         if ((strcmp(topic, "HANevse/maxC3")==0) && !TESTCASE)
        {
            char payl[length+1];
            memcpy(payl, payload, length);
            payl[length] = NULL;
            maxCurrentC1(payl);
            //client.publish("HANevse/photonTest", "test photon responds");
        }
        else
         if ((strcmp(topic, "HANevse/maxC4")==0) && !TESTCASE)
        {
            char payl[length+1];
            memcpy(payl, payload, length);
            payl[length] = NULL;
            maxCurrentC2(payl);
            //client.publish("HANevse/photonTest", "test photon responds");
        }
    }
}
charToString()
void charToString (const char in[], String & out)
Deprecated function to convert char to String - the String class already has one.
Definition at line 140 of file 2020_photon_code.cpp.
References String::operator=().
                                                {
    byte index = 0;
    const char *pointer = in;
    out = "";
    while (*pointer++) {
      out.concat(in[index++]);
      }
}
getMeasure_callback()
void getMeasure_callback (byte * payload, unsigned int length)
Callback function to automatically set max Currents from MQTT message if in renewable mode.
Definition at line 316 of file 2020_photon_code.cpp.
References JsonBuffer::clear(), maxCurrentC1_test(), maxCurrentC2_test(), and JsonParser::parse().
                                                             {
    //int sockets = 1;
    //char p[length + 1];
    //memcpy(p, payload, length);
    
    //int setPoint = (String(p)).toInt();
    
    int setP = 0;
    
    JsonParser parser1;
    parser1.clear();
    parser1.addData((char*)(payload), length);
    parser1.parse();
// parser1.getOuterValueByKey("I1", EMeterData.PhaseCurrent[0]);
// parser1.getOuterValueByKey("I2", EMeterData.PhaseCurrent[1]);
// parser1.getOuterValueByKey("I3", EMeterData.PhaseCurrent[2]);
// parser1.getOuterValueByKey("Sockets", sockets);
    parser1.getOuterValueByKey("setPoint", setP);
    
    unsigned int setPoint = setP;
    //client.publish("HANevse/photonMax", String(setPoint));
    // if (activeCharger() != 0)
    // {
      maxCurrentC1_test(setPoint); //Emeter3, I1
      delay(10);
      maxCurrentC2_test(setPoint); //Emeter3, I1
    // }
}
getUserIdAtSocket()
 String getUserIdAtSocket (int socket)
Returns RFID tag at the asked socket.
Definition at line 307 of file 2020_photon_code.cpp.
References UIDtagCharger1, and UIDtagCharger2.
                                     {
    if (socket == 1+CHARGEROFFSET)
        return UIDtagCharger1;
    if (socket == 2+CHARGEROFFSET)
        return UIDtagCharger2;
    return "00";
}
initRFID()
int initRFID (String input)
Initialises RFID reader.
Definition at line 558 of file 2020_photon_code.cpp.
Referenced by setup().
                           {
    //additional config for debugging RFID readers
    pinMode(SS_PIN_CHARGER1, OUTPUT);
    digitalWrite(SS_PIN_CHARGER1, HIGH);
    pinMode(SS_PIN_CHARGER2, OUTPUT);
    digitalWrite(SS_PIN_CHARGER2, HIGH);
  
    SPI.begin(D0); // Initiate SPI bus
    //Particle.process();
    delay(50);
    mfrc522_Charger1.PCD_Init(); // Initiate MFRC522
    delay(500);
    mfrc522_Charger2.PCD_Init(); // Initiate MFRC522
    //mfrc522_Charger1.PCD_SetAntennaGain(mfrc522.RxGain_max);
    mfrc522_Charger1.PCD_SetAntennaGain(mfrc522_Charger1.RxGain_max);
    mfrc522_Charger2.PCD_SetAntennaGain(mfrc522_Charger2.RxGain_max);
    
    DEBUGPORT.println("Approach your card to the reader...");
    DEBUGPORT.println();
    return 1;
}
loop()
void loop ()
Main running function that executes all other functions; runs over 5times/second.
Definition at line 879 of file 2020_photon_code.cpp.
References client, handledCharger, LatestStartTime, String::operator=(), readRFIDCard(), readSerialOlimex(), reconnect(), UIDtagCharger1, and UIDtagCharger2.
            {
    //Check the connection to the Particle server
    if (Particle.connected() == false) {
        Particle.connect();
    }
    //Check the connection to the MQTT broker and let client take care of messages in buffers
    if (client.isConnected()) {
        client.loop();
    }
    else reconnect();
    
    Particle.process();
    //currentStr = String(Current[0][0],1)+" "+String(Current[0][1],1)+" "+String(Current[0][2],1)+"
       "+String(Current[1][0],1)+" "+String(Current[1][1],1)+" "+String(Current[1][2],1)+" "+String(Frequency[0],2);
//+ currentStr = String(Current[0][0],1)+" "+String(PhaseVoltage[0][1],1)+"
       "+String(LineVoltage[0][2],1)+" "+String(Power[1][0],1)+" "+String(Energy[1],1)+" "+String(Current[1][2],1)+"
       "+String(Frequency[0],2);
    //currentStr=String(Current[1][2],1)+" "+currentStr.substring(0, max(200, currentStr.length()))
    //currentStr = String(CurrentList[0],1)+" "+String(CurrentList[1],1)+" "+String(CurrentList[2],1)+"
       "+String(CurrentList[3],1)+" "+String(CurrentList[4],1)+" "+String(CurrentList[5],1)+"
       "+String(CurrentList[6],1)+" "+String(CurrentList[7],1)+" "+String(CurrentList[8],1)+" "+String(CurrentList[9],1)+"
       "+String(CurrentList[10],1)+" "+String(CurrentList[11],1)+" "+String(CurrentList[12],1)+" "+String(CurrentList[13],1)+"
       "+String(CurrentList[14],1)+" "+String(CurrentList[15],1)+" "+String(CurrentList[16],1)+"
       "+String(CurrentList[17],1)+" "+String(CurrentList[18],1)+" "+String(CurrentList[19],1);
    
    //int Charger =1; //+
    
    //Read measurements from Olimex and save for which socket
    int Charger = readSerialOlimex() + CHARGEROFFSET; //+
    Particle.process();
    // !!!! This runs multiple times a second for some reason (serial)
    // if(counter>10){
    // counter = 0;
    // !!!! DEBUGPORT.println("LatestStartTime>\t"+String(LatestStartTime[0])+",
       "+String(LatestStartTime[1]));
    // DEBUGPORT.println(String(Current[1][0]+ Current[1][1]+ Current[1][2]));
    // }
    // counter++;
    // store new measurement value if it is received correctly from energymeter (via the Olimex).
    if(millis()>nextTime[handledCharger] && (Charger==1+CHARGEROFFSET || Charger==2+
      CHARGEROFFSET)) //+ all the if{}
    {
        Particle.process();
        //getUserIdAtSocket(Charger)
        int tempCharger = Charger;
        Charger = handledCharger + 1;
        //if(((activeCharger()==Charger) || (activeCharger() == 3)) && (getUserIdAtSocket(Charger)!="00"))
        //{
            //getUserIdAtSocket(Charger+CHARGEROFFSET);
            add_Measurement(PhaseVoltage[Charger-1][0], PhaseVoltage[Charger-1][1],
      PhaseVoltage[Charger-1][2], Current[Charger-1][0], Current[Charger-1][1],
      Current[Charger-1][2], /*Power[Charger-1][0]+Power[Charger-1][1]+Power[Charger-1][2], Energy[Charger-1],*/
      Frequency[Charger-1], Time.now(), Charger+CHARGEROFFSET, getUserIdAtSocket(Charger+CHARGEROFFSET));
        //}
        Charger = tempCharger;
        nextTime[handledCharger] = millis() + 30000; //every 30 sec
    }
    
// run loop very often to check new RFID cards
    Particle.process(); //+
    bool Authorized_Charger1=readRFIDCard(1+CHARGEROFFSET); //+
    delay(5);
    //if (Pianswer == 1 || Pianswer ==4)
    // Authorized_Charger1 = TRUE;
    bool Authorized_Charger2=readRFIDCard(2+CHARGEROFFSET); //+
    //delay(5);
    //if (Pianswer == 1 || Pianswer ==4) //+
    // Authorized_Charger2 = TRUE; //+
    
    
    //DEBUGPORT.println(Current[0][0]+ Current[0][1]+ Current[0][2],4);
    //DEBUGPORT.println(String(LatestStartTime[0]+60));
    //DEBUGPORT.println(String(Time.now()));
    //DEBUGPORT.println((LatestStartTime[0] + 60 < Time.now()),DEC);
    //if ((LatestStartTime[0] + 60 < Time.now()) && (Current[0][0]+ Current[0][1]+ Current[0][2]) < 1)
    //if (((numberOfZeroReadings[0]>10 && (LatestStartTime[0] + 60 < Time.now()))||
       ((Time.now()<LatestStartTime[0] + 70)&&(LatestStartTime[0] + 60 < Time.now()))) && (Current[0][0]+ Current[0][1]+ Current[0][2]) <
       1)
    
    // if 10+ Zero current readings have been taken or last start of new charge was over 1min ago and total
       Current is under 1A for first socket stop charge and reset StartTIme var
    if(((numberOfZeroReadings[0]>10)||(LatestStartTime[0] + 70 > Time.now()))&& (
      LatestStartTime[0] + 60 < Time.now()) && (Current[0][0]+ Current[0][1]+ Current[0][2]) < 1)
    {
        //timeout with current almost zero
        DEBUGPORT.println("Timeout charger"+String(CHARGEROFFSET+1));
        digitalWrite(AUTHENTICATION_CAR1,LOW);
        LatestStartTime[0]=2147483548;
    }
    //DEBUGPORT.println(Current[1][0]+ Current[1][1]+ Current[1][2],4);
    //DEBUGPORT.println(String(LatestStartTime[1]+60));
    //DEBUGPORT.println(String(Time.now()));
    //DEBUGPORT.println((LatestStartTime[1] + 60 < Time.now()),DEC);
    
    // if 10+ Zero current readings have been taken or last start of new charge was over 1min ago and total
       Current is under 1A for second socket stop charge and reset StartTIme var
    if(((numberOfZeroReadings[1]>10)||(LatestStartTime[1] + 70 > Time.now()))&& (
      LatestStartTime[1] + 60 < Time.now()) && (Current[1][0]+ Current[1][1]+ Current[1][2]) < 1)
    {
        //timeout with current almost zero
        DEBUGPORT.println("Timeout charger"+String(CHARGEROFFSET+2));
        digitalWrite(AUTHENTICATION_CAR2,LOW);
        //digitalWrite(D7,LOW);
        LatestStartTime[1]=2147483548;
    }
    delay(100);
    //Reset the UIDtag if there is no car charging and last wsipe was over 1min ago at first socket
    if ((activeCharger()!=1)&&(activeCharger()!=3)&&(UIDtagCharger1!="No ID")&& (
      LatestStartTime[0] + 60 < Time.now())){
        
        JsonWriterStatic<512> jsonMessage;
        {
        JsonWriterAutoObject obj(&jsonMessage);
        
        jsonMessage.insertKeyValue("UserId", UIDtagCharger1);
        jsonMessage.insertKeyValue("Charger", (1 + CHARGEROFFSET));
        jsonMessage.insertKeyValue("StartTime", Time.now());
        }
        client.publish("HANevse/updateUser", jsonMessage.getBuffer());
        UIDtagCharger1="No ID";
    }
        
    if ((activeCharger()!=2)&&(activeCharger()!=3)&&(UIDtagCharger2!="No ID")&& (
      LatestStartTime[1] + 60 < Time.now())){
        
        JsonWriterStatic<512> jsonMessage;
        {
        JsonWriterAutoObject obj(&jsonMessage);
        
        jsonMessage.insertKeyValue("UserId", UIDtagCharger2);
        jsonMessage.insertKeyValue("Charger", (2 + CHARGEROFFSET));
        jsonMessage.insertKeyValue("StartTime", Time.now());
        }
        client.publish("HANevse/updateUser", jsonMessage.getBuffer());
        UIDtagCharger2="No ID";
    }
            
    handledCharger = !handledCharger;
}
maxCurrentC1()
int maxCurrentC1 (String setPointStr)
Sets max Current output at socket 1 in manual mode.
Definition at line 229 of file 2020_photon_code.cpp.
References TESTCASE, and String::toInt().
Referenced by callback(), and switchTest().
                                     {
    unsigned int setPoint = setPointStr.toInt();
    if (setPoint < 7)
        setPoint = 6;
    byte olimexMessage[4] = {0xFE,1,setPoint,0xFF};
    if (!TESTCASE) {
        Serial1.write(olimexMessage,4);
        DEBUGPORT.println("maxCurrentC"+String(CHARGEROFFSET+1)+">\tNew setpoint set at "+
      String(setPoint)+" Amps.");
        return 0;
    }
    return 1;
}
maxCurrentC1_test()
int maxCurrentC1_test (unsigned int setPoint)
Sets max Current output at socket 1/3 in renewable mode and publishes new setpoint at `HANevse/photonMaxC1` or C3.
Definition at line 257 of file 2020_photon_code.cpp.
References client, String::concat(), String::String(), and TESTCASE.
Referenced by getMeasure_callback().
                                             {
    if (setPoint < 7)
        setPoint = 6;
    byte olimexMessage[4] = {0xFE, 1, setPoint, 0xFF};
    if (TESTCASE) {
        Serial1.write(olimexMessage,4);
        DEBUGPORT.println("maxCurrentC"+String(CHARGEROFFSET+1)+">\tNew setpoint set at "+
      String(setPoint)+" Amps.");
        String topic_str = "HANevse/photonMaxC";
        topic_str.concat(CHARGEROFFSET+1);
        client.publish(topic_str, String(setPoint));
        return 0;
    }
    return 1;
}
maxCurrentC2()
int maxCurrentC2 (String setPointStr)
Sets max Current output at socket 2 in manual mode.
Definition at line 243 of file 2020_photon_code.cpp.
References TESTCASE, and String::toInt().
Referenced by callback(), and switchTest().
                                     {
    unsigned int setPoint = setPointStr.toInt();
    if (setPoint < 7)
        setPoint = 6;
    byte olimexMessage[4] = {0xFE, 2, setPoint, 0xFF};
    if (!TESTCASE) {
        Serial1.write(olimexMessage,4);
        DEBUGPORT.println("maxCurrentC"+String(CHARGEROFFSET+2)+">\tNew setpoint set at "+
      String(setPoint)+" Amps.");
        return 0;
    }
    return 1;
}
maxCurrentC2_test()
int maxCurrentC2_test (unsigned int setPoint)
Sets max Current output at socket 2/4 in renewable mode and publishes new setpoint at `HANevse/photonMaxC2` or C4.
Definition at line 273 of file 2020_photon_code.cpp.
References client, String::concat(), String::String(), and TESTCASE.
Referenced by getMeasure_callback().
                                             {
    if (setPoint < 7)
        setPoint = 6;
    byte olimexMessage[4] = {0xFE,2,setPoint,0xFF};
    if (TESTCASE) {
        Serial1.write(olimexMessage,4);
        DEBUGPORT.println("maxCurrentC"+String(CHARGEROFFSET+2)+">\tNew setpoint set at "+
      String(setPoint)+" Amps.");
        String topic_str = "HANevse/photonMaxC";
        topic_str.concat(CHARGEROFFSET+2);
        client.publish(topic_str, String(setPoint));
        return 0;
    }
    return 1;
}
progModeOlmx()
int progModeOlmx (String input)
Sets Olimex into programming mode.
Definition at line 169 of file 2020_photon_code.cpp.
References resetOlimex().
                               {
    digitalWrite(WAKEUP_OLIMEX, HIGH);
    delay(500);
    resetOlimex("");
    delay(500);
    digitalWrite(WAKEUP_OLIMEX, LOW);
    return 1;
}
readRFIDCard()
bool readRFIDCard (int Charger)
Checks and reads RFID tag at the asked socket, then MQTT publishes it for Pi.
Definition at line 581 of file 2020_photon_code.cpp.
References Pianswer, String::substring(), UIDtagCharger1, and UIDtagCharger2.
Referenced by loop().
                               {
   // DEBUGPORT.print("readCard>\t");
    bool Authorized = true;
    Pianswer = 0;
    if(Charger==1+CHARGEROFFSET)
    {
      // Look for new cards
        if (! mfrc522_Charger1.PICC_IsNewCardPresent())
        {
            return false;
        }
        // Select one of the cards
        if (! mfrc522_Charger1.PICC_ReadCardSerial())
        {
            return false;
        }
  
        //Show UID on serial monitor
        DEBUGPORT.print("readCard>\tUID tag on charger1:");
        String content = "";
        //byte letter;
        for (byte i = 0; i < mfrc522_Charger1.uid.size; i++)
        {
            DEBUGPORT.print(mfrc522_Charger1.uid.uidByte[i] < 0x10 ? " 0" : " ");
            DEBUGPORT.print(mfrc522_Charger1.uid.uidByte[i], HEX);
            content.concat(String(mfrc522_Charger1.uid.uidByte[i] < 0x10 ? " 0" : " "));
            content.concat(String(mfrc522_Charger1.uid.uidByte[i], HEX));
        }
        JsonWriterStatic<512> jsonMessage;
        //Authorized=testUser(content,Charger);
        UIDtagCharger1=content.substring(1); //??? why does it start at 1?
        {
        JsonWriterAutoObject obj(&jsonMessage);
        jsonMessage.insertKeyValue("UserId", UIDtagCharger1);
        jsonMessage.insertKeyValue("Charger", Charger);
        jsonMessage.insertKeyValue("StartTime", Time.now());
        }
        client.publish("HANevse/updateUser", jsonMessage.getBuffer());
    }
    if(Charger==2+CHARGEROFFSET)
    {
    
        // Look for new cards
        if (! mfrc522_Charger2.PICC_IsNewCardPresent())
        {
            return false;
        }
        // Select one of the cards
        if (! mfrc522_Charger2.PICC_ReadCardSerial())
        {
            return false;
        }
        //DEBUGPORT.println("Read something on charger2");
        //Show UID on serial monitor
        DEBUGPORT.print("readCard>\tUID tag on charger2:");
        String content = "";
        //byte letter;
        for (byte i = 0; i < mfrc522_Charger2.uid.size; i++)
        {
            DEBUGPORT.print(mfrc522_Charger2.uid.uidByte[i] < 0x10 ? " 0" : " ");
            DEBUGPORT.print(mfrc522_Charger2.uid.uidByte[i], HEX);
            content.concat(String(mfrc522_Charger2.uid.uidByte[i] < 0x10 ? " 0" : " "));
            content.concat(String(mfrc522_Charger2.uid.uidByte[i], HEX));
        }
        //Authorized=testUser(content,Charger);
        UIDtagCharger2=content.substring(1);
        JsonWriterStatic<512> jsonMessage;
        {
        JsonWriterAutoObject obj(&jsonMessage);
        
        jsonMessage.insertKeyValue("UserId", UIDtagCharger2);
        jsonMessage.insertKeyValue("Charger", Charger);
        jsonMessage.insertKeyValue("StartTime", Time.now());
        }
        client.publish("HANevse/updateUser", jsonMessage.getBuffer());
        
    }
    DEBUGPORT.println("");
       
    delay(500);
    // This whole function is not interrupted by callback() so Pianswer can't be changed in the meantime
    //client.publish("HANevse/checkupdateUser", String(Pianswer));
     return Authorized;
}
readSerialOlimex()
int readSerialOlimex ()
Function to read from Olimex serial port and run stringParse() Returns the last charger socket it received data from.
Definition at line 271 of file Commandparser.h.
References buff, bufpos, and stringParse().
Referenced by loop().
                       {
    int Charger;
     char input;
  //if (millis()>(lastUpload+RSTTIMEOUT)){
   // softReset();
  //}
  for(int k=0;k<10;k++){
  if (Serial1.available()) {
    input = Serial1.read();
    //DEBUGPORT.print(input,HEX);
    //DEBUGPORT.print(" ");
    if (bufpos<BUFSIZE)
    {
        buff[bufpos] = input;
        bufpos++;
    }
    else
    {
        bufpos=0;
        DEBUGPORT.print("loopread>\tSerial Read Error!");
    }
    if (input == '\n') { // we hebben een regel binnen, tot aan \n // 0x0A
      Charger = stringParse(buff, bufpos);
      //Maak de buffer leeg
      for (int i=0; i<BUFSIZE; i++)
      { buff[i] = 0;}
      bufpos = 0;
    }
  }
}
return Charger;
}
reconnect()
void reconnect (void)
Function to reconnect to MQTT server if not connected and subscribe to needed topics.
Definition at line 785 of file 2020_photon_code.cpp.
References client.
Referenced by loop().
                     {
    while (!client.isConnected()) {
        DEBUGPORT.print("MQTT>\tConnecting to MQTT broker...");
        if (CHARGEROFFSET==0) {
            if (client.connect("EV-Photon1")) {
                DEBUGPORT.println("MQTT>\tConnected");
                //client.subscribe("HANevse/#", client.QOS2);
                client.subscribe("HANevse/energyMeter"); //+
                client.subscribe("HANevse/allowUser");
                
                client.subscribe("HANevse/resetOlimex");
                client.subscribe("HANevse/resetPhoton");
                client.subscribe("HANevse/switchTest1");
                client.subscribe("HANevse/maxC1");
                client.subscribe("HANevse/maxC2");
            }
            else {
                DEBUGPORT.println("MQTT>\tConnection failed");
                DEBUGPORT.println("MQTT>\tRetrying...");
                delay(10000);
            }
        }
        else if (CHARGEROFFSET==2){
            if (client.connect("EV-Photon2")) {
                DEBUGPORT.println("MQTT>\tConnected");
                //client.subscribe("HANevse/#", client.QOS2);
                client.subscribe("HANevse/energyMeter"); //+
                client.subscribe("HANevse/allowUser");
                
                client.subscribe("HANevse/resetOlimex");
                client.subscribe("HANevse/resetPhoton");
                 client.subscribe("HANevse/maxC3");
                 client.subscribe("HANevse/maxC4");
                 client.subscribe("HANevse/switchTest2");
            }
            else {
                DEBUGPORT.println("MQTT>\tConnection failed");
                DEBUGPORT.println("MQTT>\tRetrying...");
                delay(10000);
            }
        }
    }
}
resetOlimex()
int resetOlimex (String input)
Sends reset signal to EV charger controller.
Definition at line 151 of file 2020_photon_code.cpp.
Referenced by callback(), and progModeOlmx().
                              {
    digitalWrite(RESET_OLIMEX, LOW);
    delay(500);
    digitalWrite(RESET_OLIMEX, HIGH);
    return 1;
}
resetParticle()
int resetParticle (String input)
Resets Photon.
Definition at line 164 of file 2020_photon_code.cpp.
Referenced by callback().
                                {
    System.reset();
}
setup()
void setup ()
Inital setup for pin assignments and serial links start.
Definition at line 830 of file 2020_photon_code.cpp.
References initRFID().
             {
    DEBUGPORT.begin(115200);
    Serial1.begin(9600);
    //DEBUGPORT.println(Voltage,5);
    //DEBUGPORT.println(String(Voltage,5));
    
    waitUntil(Particle.connected);
    
    pinMode(AUTHENTICATION_CAR1, OUTPUT); //pinMode(D1, OUTPUT); //Charger1_Authorized
    pinMode(AUTHENTICATION_CAR2, OUTPUT); //pinMode(D2, OUTPUT); //Charger2_Authorized
    pinMode(PILOT_FEEDBACK_CAR_1,INPUT);
    pinMode(PILOT_FEEDBACK_CAR_2,INPUT);
    pinMode(WAKEUP_OLIMEX, OUTPUT);
    pinMode(RESET_OLIMEX, OUTPUT);
    pinMode(D7, OUTPUT);
    
    digitalWrite(AUTHENTICATION_CAR1, LOW); //digitalWrite(D1,LOW);
    digitalWrite(AUTHENTICATION_CAR2, LOW);//digitalWrite(D2,LOW);
    digitalWrite(WAKEUP_OLIMEX, LOW);
    digitalWrite(RESET_OLIMEX, HIGH);
    digitalWrite(D7, LOW);
    
    initRFID(""); //+
    
    //Particle.process();
    //resetOlimex("");
    //Particle.process();
    Particle.function("switchTest",switchTest);
    Particle.function("maxCurrentC1",maxCurrentC1);
    Particle.function("maxCurrentC2",maxCurrentC2);
    Particle.function("resetOlimex",resetOlimex);
    Particle.function("progModeOlmx",progModeOlmx);
    Particle.function("resetParticl",resetParticle);
    //Particle.function("AuthPinsHigh",AuthPinsHigh);
    //Particle.function("AuthPinsLow",AuthPinsLow);
    Particle.function("WifiSignal",WifiSignal);
    Particle.function("initRFID",initRFID);
    Particle.variable("currentStr",currentStr);
    Particle.variable("ShareVar",ShareVar);
    //Particle.variable("Current", Current_Str);
    Particle.variable("Topic", test);
    Particle.process();
    
    //RGB.control(true);
    Time.zone(1); //Dutch time zone
}
STARTUP()
STARTUP (WiFi. selectAntennaANT_EXTERNAL)
switchTest()
int switchTest (String valueString)
Switches between renewable mode (-input `true`) and manual setpoint mode.
Definition at line 215 of file 2020_photon_code.cpp.
References maxCurrentC1(), maxCurrentC2(), String::operator==(), and TESTCASE.
Referenced by callback().
                                   {
    if (valueString == "true") {
        TESTCASE = true;
        return 1;
    }
    if (valueString == "false") {
        TESTCASE = false;
        maxCurrentC1("32");
        maxCurrentC2("32");
        return 0;
    }
}
WifiSignal()
int WifiSignal (String input)
Return wifi strength.
Definition at line 159 of file 2020_photon_code.cpp.
                             {
    return WiFi.RSSI();
}
Variable Documentation
client
 MQTT client(`broker.hivemq.com`, 1883, MQTT_DEFAULT_KEEPALIVE, callback, 512)
MQTT client details; do not set last number to over 512!
Referenced by allowUser_callback(), loop(), maxCurrentC1_test(), maxCurrentC2_test(), and reconnect().
counter
int counter =1
Definition at line 96 of file 2020_photon_code.cpp.
Current
float Current[2][3]
Definition at line 30 of file Commandparser.h.
Referenced by activeCharger(), and stringParse().
CurrentList
float CurrentList[20]
Definition at line 36 of file Commandparser.h.
Referenced by stringParse().
currentStr
 String currentStr =``
Definition at line 135 of file 2020_photon_code.cpp.
Energy
float Energy[2]
Definition at line 34 of file Commandparser.h.
Referenced by stringParse().
Frequency
float Frequency[2]
Definition at line 35 of file Commandparser.h.
Referenced by stringParse().
handledCharger
bool handledCharger =0
Holds last handled socket (0 for first socket)
Definition at line 102 of file 2020_photon_code.cpp.
Referenced by loop().
LatestStartTime
unsigned long LatestStartTime[2] ={0,0}
Holds latest start of new charge if charger is in use.
Definition at line 100 of file 2020_photon_code.cpp.
Referenced by loop().
LineVoltage
float LineVoltage[2][3]
Definition at line 33 of file Commandparser.h.
Referenced by stringParse().
mfrc522_Charger1
 MFRC522 mfrc522_Charger1(SS_PIN_CHARGER1, RST_PIN)
mfrc522_Charger2
 MFRC522 mfrc522_Charger2(SS_PIN_CHARGER2, RST_PIN)
nextTime
unsigned int nextTime[2] = {30000,30000}
Next timestamp to publish measurements in ms.
Definition at line 137 of file 2020_photon_code.cpp.
numberOfZeroReadings
int numberOfZeroReadings[2]
Definition at line 37 of file Commandparser.h.
Referenced by stringParse().
PhaseVoltage
float PhaseVoltage[2][3]
Definition at line 32 of file Commandparser.h.
Referenced by stringParse().
Pianswer
ushort Pianswer =0
var that holds answer from Pi but is unused now
Definition at line 110 of file 2020_photon_code.cpp.
Referenced by allowUser_callback(), and readRFIDCard().
Power
float Power[2][3]
Definition at line 31 of file Commandparser.h.
Referenced by stringParse().
ShareVar
 String ShareVar
Definition at line 103 of file 2020_photon_code.cpp.
test
 String test = `0`
Definition at line 93 of file 2020_photon_code.cpp.
Referenced by callback().
TESTCASE
bool TESTCASE = false
var that holds the charging mode (TRUE = renewable)
Definition at line 107 of file 2020_photon_code.cpp.
Referenced by callback(), maxCurrentC1(), maxCurrentC1_test(), maxCurrentC2(), maxCurrentC2_test(), and switchTest().
UIDtagCharger1
 String UIDtagCharger1 =`No ID`
var to hold swiped RFID tag at first socket
Definition at line 51 of file 2020_photon_code.cpp.
Referenced by allowUser_callback(), getUserIdAtSocket(), loop(), and readRFIDCard().
UIDtagCharger2
 String UIDtagCharger2 =`No ID`
var to hold swiped RFID tag at second socket
Definition at line 53 of file 2020_photon_code.cpp.
Referenced by allowUser_callback(), getUserIdAtSocket(), loop(), and readRFIDCard().