lib/JsonParserGeneratorRK/examples/3-subscription/3-subscription-JsonParserGeneratorRK.cpp File Reference
#include `Particle.h`
#include `JsonParserGeneratorRK.h`
Functions
void subscriptionHandler (const char *event, const char *data)
void printJson (JsonParser &jp)
void setup ()
void loop ()
void printIndent (size_t indent)
void printString (const char *str)
void printJsonInner (JsonParser &jp, const JsonParserGeneratorRK::jsmntok_t *container, size_t indent)
Variables
 JsonParserStatic< 2048, 100 > jsonParser
Function Documentation
loop()
void loop ()
Definition at line 22 of file 3-subscription-JsonParserGeneratorRK.cpp.
            {
}
printIndent()
void printIndent (size_t indent)
Definition at line 47 of file 3-subscription-JsonParserGeneratorRK.cpp.
                                {
    for(size_t ii = 0; ii < 2 * indent; ii++) {
        Serial.printf(" ");
    }
}
printJson()
void printJson (JsonParser & jp)
Definition at line 149 of file 3-subscription-JsonParserGeneratorRK.cpp.
References JsonParser::getOuterToken(), and printJsonInner().
                               {
    printJsonInner(jp, jp.getOuterToken(), 0);
}
printJsonInner()
void printJsonInner (JsonParser & jp, const JsonParserGeneratorRK::jsmntok_t * container, size_t indent)
Definition at line 75 of file 3-subscription-JsonParserGeneratorRK.cpp.
References JsonParserGeneratorRK::jsmntok_t::end, JsonParser::getKeyValueTokenByIndex(), JsonParser::getTokenValue(), JsonParser::getValueTokenByIndex(), JsonParserGeneratorRK::JSMN_ARRAY, JsonParserGeneratorRK::JSMN_OBJECT, JsonParserGeneratorRK::JSMN_PRIMITIVE, JsonParserGeneratorRK::JSMN_STRING, JsonParserGeneratorRK::JSMN_UNDEFINED, printIndent(), printJsonInner(), printString(), JsonParserGeneratorRK::jsmntok_t::start, and JsonParserGeneratorRK::jsmntok_t::type.
                                                                                                    {
    switch(container->type) {
    case JsonParserGeneratorRK::JSMN_OBJECT: {
        printIndent(indent);
        Serial.printf("{\n");
        for(size_t ii = 0; ; ii++) {
            const JsonParserGeneratorRK::jsmntok_t *keyToken;
            const JsonParserGeneratorRK::jsmntok_t *valueToken;
            if (!jp.getKeyValueTokenByIndex(container, keyToken, valueToken, ii)) {
                break;
            }
            if (ii > 0) {
                Serial.printf(",\n");
            }
            String keyName;
            jp.getTokenValue(keyToken, keyName);
            printIndent(indent + 1);
            printString(keyName);
            Serial.printf(":");
            printJsonInner(jp, valueToken, indent + 1);
        }
        Serial.printf("\n");
        printIndent(indent);
        Serial.printf("}\n");
        break;
    }
    case JsonParserGeneratorRK::JSMN_ARRAY: {
        printIndent(indent);
        Serial.printf("[\n");
        for(size_t ii = 0; ; ii++) {
            const JsonParserGeneratorRK::jsmntok_t *valueToken;
            if (!jp.getValueTokenByIndex(container, ii, valueToken)) {
                break;
            }
            if (ii > 0) {
                Serial.printf(",\n");
            }
            printIndent(indent + 1);
            printJsonInner(jp, valueToken, indent + 1);
        }
        Serial.printf("\n");
        printIndent(indent);
        Serial.printf("]\n");
        break;
    }
    case JsonParserGeneratorRK::JSMN_STRING: {
        Serial.printf("\"");
        for(int ii = container->start; ii < container->end; ii++) {
            Serial.printf("%c", jp.getBuffer()[ii]);
        }
        Serial.printf("\"");
        break;
    }
    case JsonParserGeneratorRK::JSMN_PRIMITIVE: {
        for(int ii = container->start; ii < container->end; ii++) {
            Serial.printf("%c", jp.getBuffer()[ii]);
        }
        break;
    }
    case JsonParserGeneratorRK::JSMN_UNDEFINED:
    default: {
        break;
    }
    }
}
printString()
void printString (const char * str)
Definition at line 53 of file 3-subscription-JsonParserGeneratorRK.cpp.
                                  {
    Serial.printf("\"");
    for(size_t ii = 0; str[ii]; ii++) {
        if (str[ii] == '"') {
            Serial.printf("\\\"");
        }
        else
        if (str[ii] == '\\') {
            Serial.printf("\\\\");
        }
        else
        if (str[ii] >= 32 && str[ii] < 127) {
            Serial.printf("%c", str[ii]);
        }
        else {
            Serial.printf("\\x%02x", str[ii]);
        }
    }
    Serial.printf("\"");
}
setup()
void setup ()
Definition at line 17 of file 3-subscription-JsonParserGeneratorRK.cpp.
             {
    Serial.begin(9600);
    Particle.subscribe("jsonParserTest", subscriptionHandler, MY_DEVICES);
}
subscriptionHandler()
void subscriptionHandler (const char * event, const char * data)
Definition at line 25 of file 3-subscription-JsonParserGeneratorRK.cpp.
References JsonBuffer::addString(), JsonBuffer::clear(), jsonParser, JsonParser::parse(), and printJson().
                                                              {
    int responseIndex = 0;
    const char *slashOffset = strrchr(event, '/');
    if (slashOffset) {
        responseIndex = atoi(slashOffset + 1);
    }
    if (responseIndex == 0) {
        jsonParser.clear();
    }
    jsonParser.addString(data);
    if (jsonParser.parse()) {
        // Looks valid (we received all parts)
        // This printing thing is just for testing purposes, you should use the commands to
        // process data
        printJson(jsonParser);
    }
}
Variable Documentation
jsonParser
 JsonParserStatic<2048, 100> jsonParser
Definition at line 9 of file 3-subscription-JsonParserGeneratorRK.cpp.
Referenced by subscriptionHandler().