src/Commandparser.h File Reference
#include `Particle.h`
Macros
#define BUFSIZE 350
#define RSTTIMEOUT 300000
#define DEBUGPORT Serial
Functions
void Send (String test)
float bytesToFloat (unsigned char b0, unsigned char b1, unsigned char b2, unsigned char b3)
bool bytesArrToFloatArr (char *Arr, unsigned int ArrLen, float *OutputArr, unsigned int FloatLen)
int stringParse (char *buf, int buflen)
int readSerialOlimex ()
Variables
bool readnextLine = false
char buff [ BUFSIZE]
int bufpos = 0
unsigned long lastUpload = 0
float Current [2][3] ={{0,0,0},{0,0,0}}
float Power [2][3] ={{0,0,0},{0,0,0}}
float PhaseVoltage [2][3] ={{0,0,0},{0,0,0}}
float LineVoltage [2][3] ={{0,0,0},{0,0,0}}
float Energy [2] ={0,0}
float Frequency [2] ={0,0}
float CurrentList [20]
int numberOfZeroReadings [2] ={0,0}
Macro Definition Documentation
BUFSIZE
#define BUFSIZE 350
Definition at line 7 of file Commandparser.h.
DEBUGPORT
#define DEBUGPORT Serial
Definition at line 9 of file Commandparser.h.
RSTTIMEOUT
#define RSTTIMEOUT 300000
Definition at line 8 of file Commandparser.h.
Function Documentation
bytesArrToFloatArr()
bool bytesArrToFloatArr (char * Arr, unsigned int ArrLen, float * OutputArr, unsigned int FloatLen)
Function to convert an array of Olimex 4-byte values to float variables
Definition at line 65 of file Commandparser.h.
Referenced by stringParse().
{
    //FloatTriplet TriOutput;
    for(int i=0; (i<FloatLen) && (4*i+3 < ArrLen); i++)
    {
        float output;
        *((unsigned char *)(&output) + 3) = (unsigned char) Arr[4*i+0];
        *((unsigned char *)(&output) + 2) = Arr[4*i+1];
        *((unsigned char *)(&output) + 1) = Arr[4*i+2];
        *((unsigned char *)(&output) + 0) = Arr[4*i+3];
        
        OutputArr[i] = output;
    }
    return true;
}
bytesToFloat()
float bytesToFloat (unsigned char b0, unsigned char b1, unsigned char b2, unsigned char b3)
Function to convert Olimex 4-byte value to float variable
Definition at line 50 of file Commandparser.h.
Referenced by stringParse().
{
    float output;
    *((unsigned char *)(&output) + 3) = b0;
    *((unsigned char *)(&output) + 2) = b1;
    *((unsigned char *)(&output) + 1) = b2;
    *((unsigned char *)(&output) + 0) = b3;
    return output;
}
readSerialOlimex()
int readSerialOlimex ()
Function to read from Olimex serial port and run stringParse() Returns the last charger socket it received data from.
Definition at line 271 of file Commandparser.h.
References buff, bufpos, and stringParse().
Referenced by loop().
                       {
    int Charger;
     char input;
  //if (millis()>(lastUpload+RSTTIMEOUT)){
   // softReset();
  //}
  for(int k=0;k<10;k++){
  if (Serial1.available()) {
    input = Serial1.read();
    //DEBUGPORT.print(input,HEX);
    //DEBUGPORT.print(" ");
    if (bufpos<BUFSIZE)
    {
        buff[bufpos] = input;
        bufpos++;
    }
    else
    {
        bufpos=0;
        DEBUGPORT.print("loopread>\tSerial Read Error!");
    }
    if (input == '\n') { // we hebben een regel binnen, tot aan \n // 0x0A
      Charger = stringParse(buff, bufpos);
      //Maak de buffer leeg
      for (int i=0; i<BUFSIZE; i++)
      { buff[i] = 0;}
      bufpos = 0;
    }
  }
}
return Charger;
}
Send()
void Send (String test)
stringParse()
int stringParse (char * buf, int buflen)
Function to parse Olimex message into energy measurements Returns the charger socket it received data from.
Definition at line 107 of file Commandparser.h.
References bytesArrToFloatArr(), bytesToFloat(), Current, CurrentList, Energy, Frequency, LineVoltage, numberOfZeroReadings, PhaseVoltage, and Power.
Referenced by readSerialOlimex().
                                       {
  String cmdValue;
  int Charger=0;
  for (int i=0; i<buflen; i++){
    if(buf[i]==0x0F && i+2>=buflen) //error check?
    {
      DEBUGPORT.println("E");
    }
    if((buf[i]==0x0F || buf[i]==0x0E) && i+2<buflen) //we detect a command-character and the next two
       characters exists
    {
      if (buf[i]==0x0F)
      {
        Charger=1;
      }
      else
      {
        Charger=2;
      }
      DEBUGPORT.print("Charger "+String(Charger)+": ");
      String measurements;
      switch (buf[i+1])
      {
        case 1:
          //Phase Voltage
          if(buflen>4)
          {
              //Voltage[Charger-1] = bytesToFloat(buf[i+2], buf[i+3], buf[i+4], buf[i+5]);
              float VoltageArr[3];
              if(bytesArrToFloatArr(&buf[i+2], 12, VoltageArr,3))
              {
                //Current[Charger-1] = (CurrentArr[0]+CurrentArr[1]+CurrentArr[2])/3;
                for(int i=0;i<3;i++)
                {
                    PhaseVoltage[Charger-1][i]=VoltageArr[i];
                }
                //Voltage[Charger-1] = {VoltageArr[0],VoltageArr[1],VoltageArr[2]};
              }
              DEBUGPORT.print("Voltage: "+String(PhaseVoltage[Charger-1][0],4)+" "+
      String(PhaseVoltage[Charger-1][1],4)+" "+String(PhaseVoltage[Charger-1][2],4));
          }
          else
          {
              DEBUGPORT.print("did not receive enough voltage data");
          }
          break;
        case 2:
          //Current
          if(buflen>12) //(buflen>4)
          {
              //Current[Charger-1] = bytesToFloat(buf[i+2], buf[i+3], buf[i+4], buf[i+5]);
              float CurrentArr[3];
              if(bytesArrToFloatArr(&buf[i+2], 12, Current[Charger-1],3))
              {
                //Current[Charger-1] = (CurrentArr[0]+CurrentArr[1]+CurrentArr[2])/3;
                //Current[Charger-1] = {CurrentArr[0],CurrentArr[1],CurrentArr[2]}
              }
              DEBUGPORT.print("Current: ");
              DEBUGPORT.print(Current[Charger-1][0],4);DEBUGPORT.print(" ");
              DEBUGPORT.print(Current[Charger-1][1],4);DEBUGPORT.print(" ");
              DEBUGPORT.println(Current[Charger-1][2],4);
              if((Current[Charger-1][0]+Current[Charger-1][1]+Current[Charger-1][2])<1)
              {
                numberOfZeroReadings[Charger-1]++;
              }
              else
              {
                  numberOfZeroReadings[Charger-1]=0;
              }
              for(int i=18;i>=0;i--)
              {
                   CurrentList[i+1]= CurrentList[i];
              }
              CurrentList[0]=(Current[0][0]+Current[0][1]+Current[0][2]);//numberOfZeroReadings[0];
              CurrentList[1]=numberOfZeroReadings[0];
              CurrentList[2]=Current[0][2];
          }
          else
          {
              DEBUGPORT.print("did not receive enough current data");
          }
          break;
        case 3:
          //Frequency
          if(buflen>4)
          {
              Frequency[0] = bytesToFloat(buf[i+2], buf[i+3], buf[i+4], buf[i+5]);
              Frequency[1]=Frequency[0];
              DEBUGPORT.print("Frequency: ");
              DEBUGPORT.print(Frequency[Charger-1],4);
          }
          else
          {
              DEBUGPORT.print("did not receive enough frequency data");
          }
          break;
        case 4:
          //Power
          if(buflen>4)
          {
              //Power[Charger-1] = bytesToFloat(buf[i+2], buf[i+3], buf[i+4], buf[i+5]);
              float PowerArr[3];
              if(bytesArrToFloatArr(&buf[i+2], 12, Power[Charger-1],3))
              {
                //Power[Charger-1] = {PowerArr[0],PowerArr[1],PowerArr[2]}
              }
              DEBUGPORT.print("Power: "+String(Power[Charger-1][0],4)+" "+String(
      Power[Charger-1][1],4)+" "+String(Power[Charger-1][2],4));
              //DEBUGPORT.print("Power: ");
              //DEBUGPORT.print(Power[Charger-1],4);
          }
          else
          {
              DEBUGPORT.print("did not receive enough power data");
          }
          break;
        case 5:
          //Energy
          if(buflen>4)
          {
              Energy[Charger-1] = bytesToFloat(buf[i+2], buf[i+3], buf[i+4], buf[i+5]);
              DEBUGPORT.print("Energy: ");
              DEBUGPORT.print(Energy[Charger-1],4);
          }
          else
          {
              DEBUGPORT.print("did not receive enough energy data");
          }
          break;
        case 6:
          //Line Voltage
          if(buflen>4)
          {
              //Voltage[Charger-1] = bytesToFloat(buf[i+2], buf[i+3], buf[i+4], buf[i+5]);
              float VoltageArr[3];
              if(bytesArrToFloatArr(&buf[i+2], 12, VoltageArr,3))
              {
                //Current[Charger-1] = (CurrentArr[0]+CurrentArr[1]+CurrentArr[2])/3;
                for(int i=0;i<3;i++)
                {
                    LineVoltage[Charger-1][i]=VoltageArr[i];
                }
                //Voltage[Charger-1] = {VoltageArr[0],VoltageArr[1],VoltageArr[2]};
              }
              DEBUGPORT.print("Voltage: "+String(LineVoltage[Charger-1][0],4)+" "+
      String(LineVoltage[Charger-1][1],4)+" "+String(LineVoltage[Charger-1][2],4));
          }
          else
          {
              DEBUGPORT.print("did not receive enough voltage data");
          }
          break;
          break;
        default:
          break;
      }
    }
  }
  //Test only
  //Current[0][0] = 3.0;
  //Current[1][0] = 4.0;
  return Charger;
}
Variable Documentation
buff
char buff[ BUFSIZE]
Definition at line 14 of file Commandparser.h.
Referenced by readSerialOlimex().
bufpos
int bufpos = 0
Definition at line 15 of file Commandparser.h.
Referenced by readSerialOlimex().
Current
float Current[2][3] ={{0,0,0},{0,0,0}}
Definition at line 30 of file Commandparser.h.
Referenced by activeCharger(), and stringParse().
CurrentList
float CurrentList[20]
Definition at line 36 of file Commandparser.h.
Referenced by stringParse().
Energy
float Energy[2] ={0,0}
Definition at line 34 of file Commandparser.h.
Referenced by stringParse().
Frequency
float Frequency[2] ={0,0}
Definition at line 35 of file Commandparser.h.
Referenced by stringParse().
lastUpload
unsigned long lastUpload = 0
Definition at line 18 of file Commandparser.h.
LineVoltage
float LineVoltage[2][3] ={{0,0,0},{0,0,0}}
Definition at line 33 of file Commandparser.h.
Referenced by stringParse().
numberOfZeroReadings
int numberOfZeroReadings[2] ={0,0}
Definition at line 37 of file Commandparser.h.
Referenced by stringParse().
PhaseVoltage
float PhaseVoltage[2][3] ={{0,0,0},{0,0,0}}
Definition at line 32 of file Commandparser.h.
Referenced by stringParse().
Power
float Power[2][3] ={{0,0,0},{0,0,0}}
Definition at line 31 of file Commandparser.h.
Referenced by stringParse().
readnextLine
bool readnextLine = false
Definition at line 13 of file Commandparser.h.