JsonReference Class Reference
This class provides a fluent-style API for easily traversing a tree of JSON objects to find a value.
#include <JsonParserGeneratorRK.h>
Public Member Functions
 JsonReference (const JsonParser * parser)
Constructs an object. Normally you use the JsonParser getReference() method to get one of these instead of constructing one.
virtual ~JsonReference ()
Destructor. This does not affect the lifecycle of the JsonParser.
 JsonReference (const JsonParser * parser, const JsonParserGeneratorRK::jsmntok_t * token)
Constructs are JsonReference for a specific token within a JsonParser.
 JsonReference key (const char *name) const
For JsonReference that refers to a JSON object, gets a new JsonReference to a value with the specified key name.
 JsonReference index (size_t index) const
For a JsonReference that refers to a JSON array, gets a new JsonReference to a value in the array by index.
size_t size () const
For a JsonReference that refers to a JSON array, gets the size of the array.
template<class T >
bool value (T &result) const
Get a value of the specified type for a given value for a specified key, or index for an array.
bool valueBool (bool defaultValue=false) const
Returns a boolean (bool) value for an object value for key, or array index.
int valueInt (int defaultValue=0) const
Returns a integer (int) value for an object value for key, or array index.
unsigned long valueUnsignedLong (unsigned long defaultValue=0) const
Returns a unsigned long integer for an object value for key, or array index.
float valueFloat (float defaultValue=0.0) const
Returns a float value for an object value for key, or array index.
double valueDouble (double defaultValue=0.0) const
Returns a double value for an object value for key, or array index.
 String valueString () const
Returns a String value for an object value for key, or array index.
Private Attributes
const JsonParser * parser
const JsonParserGeneratorRK::jsmntok_t * token
Detailed Description
This class provides a fluent-style API for easily traversing a tree of JSON objects to find a value.
Definition at line 788 of file JsonParserGeneratorRK.h.
Constructor & Destructor Documentation
JsonReference() [1/2]
JsonReference::JsonReference (const JsonParser * parser)
Constructs an object. Normally you use the JsonParser getReference() method to get one of these instead of constructing one.
Parameters
parser The JsonParser object you're traversing
Definition at line 546 of file JsonParserGeneratorRK.cpp.
References parser, and token.
Referenced by JsonParser::getReference(), index(), and key().
                                                     : parser(parser), token(0) {
}
~JsonReference()
JsonReference::~JsonReference () [virtual]
Destructor. This does not affect the lifecycle of the JsonParser.
Definition at line 550 of file JsonParserGeneratorRK.cpp.
                              {
}
JsonReference() [2/2]
JsonReference::JsonReference (const JsonParser * parser, const JsonParserGeneratorRK::jsmntok_t * token)
Constructs are JsonReference for a specific token within a JsonParser.
Definition at line 553 of file JsonParserGeneratorRK.cpp.
References parser, and token.
Referenced by JsonParser::getReference(), index(), and key().
                                                                                                  :
      parser(parser), token(token) {
}
Member Function Documentation
index()
 JsonReference JsonReference::index (size_t index) const
For a JsonReference that refers to a JSON array, gets a new JsonReference to a value in the array by index.
Parameters
index The index to retrieve (0 = first item, 1 = second item, ...).
Returns
A JsonReference to the value for this index.
Definition at line 567 of file JsonParserGeneratorRK.cpp.
References JsonParser::getValueTokenByIndex(), JsonReference(), parser, and token.
Referenced by main().
                                                     {
    const JsonParserGeneratorRK::jsmntok_t *newToken;
    if (token && parser->getValueTokenByIndex(token, index, newToken)) {
        return JsonReference(parser, newToken);
    }
    else {
        return JsonReference(parser);
    }
}
key()
 JsonReference JsonReference::key (const char * name) const
For JsonReference that refers to a JSON object, gets a new JsonReference to a value with the specified key name.
Parameters
name of the key to look for.
Returns
A JsonReference to the value for this key.
Definition at line 556 of file JsonParserGeneratorRK.cpp.
References JsonParser::getValueTokenByKey(), JsonReference(), parser, and token.
Referenced by main().
                                                       {
    const JsonParserGeneratorRK::jsmntok_t *newToken;
    if (token && parser->getValueTokenByKey(token, name, newToken)) {
        return JsonReference(parser, newToken);
    }
    else {
        return JsonReference(parser);
    }
}
size()
size_t JsonReference::size () const
For a JsonReference that refers to a JSON array, gets the size of the array.
Returns
0 = an empty array, 1 = one element, ...
Definition at line 578 of file JsonParserGeneratorRK.cpp.
References JsonParser::getArraySize(), parser, and token.
Referenced by main().
                                 {
    if (token) {
        return parser->getArraySize(token);
    }
    else {
        return 0;
    }
}
value()
template<class T >
bool JsonReference::value (T & result) const [inline]
Get a value of the specified type for a given value for a specified key, or index for an array.
Parameters
result Filled in with the value. The value can be of type: bool, int, unsigned long, float, double, String, or (char *, size_t&).
There are also type-specific versions like valueBool that return the value, instead of having to pass an object to hold the value, as in this call.
Definition at line 843 of file JsonParserGeneratorRK.h.
References parser, and token.
Referenced by valueBool(), valueDouble(), valueFloat(), valueInt(), valueString(), and valueUnsignedLong().
                                {
        if (token && parser->getTokenValue(token, result)) {
            return true;
        }
        else {
            return false;
        }
    }
valueBool()
bool JsonReference::valueBool (bool defaultValue = false) const
Returns a boolean (bool) value for an object value for key, or array index.
Parameters
defaultValue Optional value to use if the key or array index is not found. Default: false.
Definition at line 587 of file JsonParserGeneratorRK.cpp.
References value().
                                               {
    (void) value(result);
    return result;
}
valueDouble()
double JsonReference::valueDouble (double defaultValue = 0.0) const
Returns a double value for an object value for key, or array index.
Parameters
defaultValue Optional value to use if the key or array index is not found. Default: 0.0.
Definition at line 607 of file JsonParserGeneratorRK.cpp.
References value().
Referenced by main().
                                                     {
    (void) value(result);
    return result;
}
valueFloat()
float JsonReference::valueFloat (float defaultValue = 0.0) const
Returns a float value for an object value for key, or array index.
Parameters
defaultValue Optional value to use if the key or array index is not found. Default: 0.0.
Definition at line 602 of file JsonParserGeneratorRK.cpp.
References value().
Referenced by main().
                                                  {
    (void) value(result);
    return result;
}
valueInt()
int JsonReference::valueInt (int defaultValue = 0) const
Returns a integer (int) value for an object value for key, or array index.
Parameters
defaultValue Optional value to use if the key or array index is not found. Default: 0.
Definition at line 592 of file JsonParserGeneratorRK.cpp.
References value().
Referenced by main().
                                            {
    (void) value(result);
    return result;
}
valueString()
 String JsonReference::valueString () const
Returns a String value for an object value for key, or array index.
Returns
The string value, or an empty string if the key or array index is not found.
Definition at line 612 of file JsonParserGeneratorRK.cpp.
References value().
Referenced by main().
                                        {
    String result;
    (void) value(result);
    return result;
}
valueUnsignedLong()
unsigned long JsonReference::valueUnsignedLong (unsigned long defaultValue = 0) const
Returns a unsigned long integer for an object value for key, or array index.
Parameters
defaultValue Optional value to use if the key or array index is not found. Default: 0.
Definition at line 597 of file JsonParserGeneratorRK.cpp.
References value().
Referenced by main().
                                                                         {
    (void) value(result);
    return result;
}
Member Data Documentation
parser
const JsonParser* JsonReference::parser [private]
Definition at line 895 of file JsonParserGeneratorRK.h.
Referenced by index(), JsonReference(), key(), size(), and value().
token
const JsonParserGeneratorRK::jsmntok_t* JsonReference::token [private]
Definition at line 896 of file JsonParserGeneratorRK.h.
Referenced by index(), JsonReference(), key(), size(), and value().
The documentation for this class was generated from the following files:
lib/JsonParserGeneratorRK/src/ JsonParserGeneratorRK.h
lib/JsonParserGeneratorRK/src/ JsonParserGeneratorRK.cpp