JsonWriter Class Reference
Class for building a JSON string.
#include <JsonParserGeneratorRK.h>
Public Member Functions
JsonWriter ()
Construct a JsonWriter with a dynamically allocated buffer.
virtual ~JsonWriter ()
Destroy the object. If the buffer was dynamically allocated it will be freed.
JsonWriter (char *buffer, size_t bufferLen)
Construct a JsonWriter to write to a static buffer.
void init ()
Reset the writer, clearing all data.
bool startObject ()
Start a new JSON object. Make sure you finish it with finishObjectOrArray()
bool startArray ()
Start a new JSON array. Make sure you finish it with finishObjectOrArray()
void finishObjectOrArray ()
Finsh an object or array started with startObject() or startArray()
void insertValue (bool value)
Inserts a boolean value (`true` or `false`).
void insertValue (int value)
Inserts an integer value.
void insertValue (unsigned int value)
Inserts an unsigned integer value.
void insertValue (long value)
Inserts a long integer value.
void insertValue (unsigned long value)
Inserts an unsigned long integer value.
void insertValue (float value)
Inserts a floating point value.
void insertValue (double value)
Inserts a floating point double value.
void insertValue (const char *value)
Inserts a quoted string value. This escapes special characters and encodes utf-8.
void insertValue (const String &value)
Inserts a quoted string value.
void insertKeyObject (const char *key)
Inserts a new key and empty object. You must close the object using finishObjectOrArray()!
void insertKeyArray (const char *key)
Inserts a new key and empty array. You must close the object using finishObjectOrArray()!
template<class T >
void insertKeyValue (const char *key, T value)
Inserts a key/value pair into an object.
template<class T >
void insertArrayValue (T value)
Inserts a value into an array.
template<class T >
void insertArray (T *pArray, size_t numElem)
Inserts an array of values into an array.
template<class T >
void insertKeyArray (const char *key, T *pArray, size_t numElem)
Inserts a new key and vector of values.
template<class T >
void insertVector (std::vector< T > vec)
Inserts an array of values into an array.
template<class T >
void insertKeyVector (const char *key, std::vector< T > vec)
Inserts a new key and vector of values.
bool isTruncated () const
void setFloatPlaces (int floatPlaces)
Sets the number of digits for formatting float and double values.
void insertCheckSeparator ()
Check to see if a separator needs to be inserted. Used internally.
bool startObjectOrArray (char startChar, char endChar)
Used internally to start an object or array.
void insertChar (char ch)
Used internally to insert a character.
void insertString (const char *s, bool quoted=false)
Used internally to insert a string, quoted or not.
void insertsprintf (const char *fmt,...)
Used internally to insert using snprintf formatting.
void insertvsprintf (const char *fmt, va_list ap)
Used internally to insert using snprintf formatting with a va_list.
void setIsFirst (bool isFirst=true)
Used internally to set the current isFirst flag in the context.
Static Public Attributes
static const size_t MAX_NESTED_CONTEXT = 9
Protected Attributes
size_t contextIndex
Index into the context for the current level of nesting.
JsonWriterContext context [MAX_NESTED_CONTEXT]
Structure for managing nested objects.
bool truncated
true if data was added that didn't fit and was truncated
int floatPlaces
default number of places to display for floating point numbers (default is -1, the default for sprintf)
Detailed Description
Class for building a JSON string.
Definition at line 910 of file JsonParserGeneratorRK.h.
Constructor & Destructor Documentation
JsonWriter() [1/2]
JsonWriter::JsonWriter ()
Construct a JsonWriter with a dynamically allocated buffer.
The buffer will be resized as necessary but you can improve efficiency by using the allocate() method of JsonBuffer to pre-allocate space rather than have to incrementally make it bigger as it's written to.
Use getBuffer() to get the pointer to the buffer and getOffset() to get the buffer pointer and size. The buffer is not null-terminated!
Definition at line 655 of file JsonParserGeneratorRK.cpp.
References floatPlaces, init(), and JsonBuffer::JsonBuffer().
 JsonWriter()
JsonWriter::~JsonWriter () [virtual]
Destroy the object. If the buffer was dynamically allocated it will be freed.
If the buffer was passed in using the buffer, bufferLen constructor the buffer is not freed by this call as it's likely statically allocated.
Definition at line 659 of file JsonParserGeneratorRK.cpp.
JsonWriter() [2/2]
JsonWriter::JsonWriter (char * buffer, size_t bufferLen)
Construct a JsonWriter to write to a static buffer.
Parameters
buffer Pointer to the buffer
bufferLen Length of the buffer in bytes
Definition at line 663 of file JsonParserGeneratorRK.cpp.
References floatPlaces, init(), and JsonBuffer::JsonBuffer().
Referenced by main().
Member Function Documentation
finishObjectOrArray()
void JsonWriter::finishObjectOrArray ()
Finsh an object or array started with startObject() or startArray()
Definition at line 695 of file JsonParserGeneratorRK.cpp.
References JsonBuffer::buffer, JsonBuffer::bufferLen, context, contextIndex, insertChar(), JsonBuffer::offset, and JsonWriterContext::terminator.
Referenced by insertKeyArray(), insertKeyVector(), main(), JsonWriterAutoArray::~JsonWriterAutoArray(), and JsonWriterAutoObject::~JsonWriterAutoObject().
init()
void JsonWriter::init ()
Reset the writer, clearing all data.
You do not need to call init() as it's called from the two constructors. You can call it again if you want to reset the writer and reuse it, such as when you use JsonWriterStatic in a global variable.
Definition at line 667 of file JsonParserGeneratorRK.cpp.
References context, contextIndex, JsonWriterContext::isFirst, JsonBuffer::offset, JsonWriterContext::terminator, and truncated.
Referenced by JsonWriter(), JsonModifier::startAppend(), and JsonModifier::startModify().
insertArray()
template<class T >
void JsonWriter::insertArray (T * pArray, size_t numElem) [inline]
Inserts an array of values into an array.
Uses templates so you can pass any type object that's supported by insertValue() overloads, for example: bool, int, float, double, const char *.
Definition at line 1091 of file JsonParserGeneratorRK.h.
insertArrayValue()
template<class T >
void JsonWriter::insertArrayValue (T value) [inline]
Inserts a value into an array.
Uses templates so you can pass any type object that's supported by insertValue() overloads, for example: bool, int, float, double, const char *.
Definition at line 1079 of file JsonParserGeneratorRK.h.
References insertCheckSeparator().
Referenced by main().
insertChar()
void JsonWriter::insertChar (char ch)
Used internally to insert a character.
Used internally. You should use insertKeyValue() or insertArrayValue() with a string instead.
Definition at line 712 of file JsonParserGeneratorRK.cpp.
References JsonBuffer::buffer, JsonBuffer::bufferLen, JsonBuffer::offset, and truncated.
Referenced by finishObjectOrArray(), insertCheckSeparator(), insertKeyArray(), insertKeyObject(), insertKeyValue(), insertString(), and startObjectOrArray().
insertCheckSeparator()
void JsonWriter::insertCheckSeparator ()
Check to see if a separator needs to be inserted. Used internally.
You normally don't need to use this as it's called by insertKeyValue() and insertArrayValue().
Definition at line 823 of file JsonParserGeneratorRK.cpp.
References context, contextIndex, insertChar(), and JsonWriterContext::isFirst.
Referenced by insertArrayValue(), insertKeyArray(), insertKeyObject(), insertKeyValue(), main(), and startObjectOrArray().
insertKeyArray() [1/2]
void JsonWriter::insertKeyArray (const char * key)
Inserts a new key and empty array. You must close the object using finishObjectOrArray()!
Parameters
key the key name to insert
Definition at line 867 of file JsonParserGeneratorRK.cpp.
References insertChar(), insertCheckSeparator(), insertValue(), setIsFirst(), and startArray().
Referenced by insertKeyArray(), insertKeyVector(), and main().
insertKeyArray() [2/2]
template<class T >
void JsonWriter::insertKeyArray (const char * key, T * pArray, size_t numElem) [inline]
Inserts a new key and vector of values.
Parameters
key the key name to insert
vec the vector to insert
Definition at line 1105 of file JsonParserGeneratorRK.h.
References finishObjectOrArray(), and insertKeyArray().
Referenced by main().
insertKeyObject()
void JsonWriter::insertKeyObject (const char * key)
Inserts a new key and empty object. You must close the object using finishObjectOrArray()!
Parameters
key the key name to insert
Definition at line 859 of file JsonParserGeneratorRK.cpp.
References insertChar(), insertCheckSeparator(), insertValue(), setIsFirst(), and startObject().
Referenced by main().
insertKeyValue()
template<class T >
void JsonWriter::insertKeyValue (const char * key, T value) [inline]
Inserts a key/value pair into an object.
Uses templates so you can pass any type object that's supported by insertValue() overloads, for example: bool, int, float, double, const char *.
Definition at line 1065 of file JsonParserGeneratorRK.h.
References insertChar(), insertCheckSeparator(), and insertValue().
Referenced by main(), and runTest().
insertKeyVector()
template<class T >
void JsonWriter::insertKeyVector (const char * key, std::vector< T > vec) [inline]
Inserts a new key and vector of values.
Parameters
key the key name to insert
vec the vector to insert
Definition at line 1132 of file JsonParserGeneratorRK.h.
References finishObjectOrArray(), and insertKeyArray().
Referenced by main().
insertsprintf()
void JsonWriter::insertsprintf (const char * fmt, ...)
Used internally to insert using snprintf formatting.
Used internally. You should use insertKeyValue() or insertArrayValue() with a string, float, or double instead.
This method does not quote or escape the string - it's used mainly for formatting numbers.
Definition at line 802 of file JsonParserGeneratorRK.cpp.
References insertvsprintf().
Referenced by insertString(), insertValue(), and main().
insertString()
void JsonWriter::insertString (const char * s, bool quoted = false)
Used internally to insert a string, quoted or not.
Used internally. You should use insertKeyValue() or insertArrayValue() with a string instead.
Definition at line 721 of file JsonParserGeneratorRK.cpp.
References JsonBuffer::bufferLen, insertChar(), insertsprintf(), and JsonBuffer::offset.
Referenced by insertValue(), and main().
insertValue() [1/9]
void JsonWriter::insertValue (bool value)
Inserts a boolean value (`true` or `false`).
You would normally use insertKeyValue() or insertArrayValue() instead of calling this directly as those functions take care of inserting the separtators between items.
Definition at line 832 of file JsonParserGeneratorRK.cpp.
References insertString().
insertValue() [2/9]
void JsonWriter::insertValue (int value) [inline]
Inserts an integer value.
You would normally use insertKeyValue() or insertArrayValue() instead of calling this directly as those functions take care of inserting the separators between items.
Definition at line 979 of file JsonParserGeneratorRK.h.
References insertsprintf().
Referenced by main().
insertValue() [3/9]
void JsonWriter::insertValue (unsigned int value) [inline]
Inserts an unsigned integer value.
You would normally use insertKeyValue() or insertArrayValue() instead of calling this directly as those functions take care of inserting the separators between items.
Definition at line 987 of file JsonParserGeneratorRK.h.
References insertsprintf().
insertValue() [4/9]
void JsonWriter::insertValue (long value) [inline]
Inserts a long integer value.
You would normally use insertKeyValue() or insertArrayValue() instead of calling this directly as those functions take care of inserting the separators between items.
Definition at line 995 of file JsonParserGeneratorRK.h.
References insertsprintf().
insertValue() [5/9]
void JsonWriter::insertValue (unsigned long value) [inline]
Inserts an unsigned long integer value.
You would normally use insertKeyValue() or insertArrayValue() instead of calling this directly as those functions take care of inserting the separators between items.
Definition at line 1003 of file JsonParserGeneratorRK.h.
References insertsprintf().
insertValue() [6/9]
void JsonWriter::insertValue (float value)
Inserts a floating point value.
Use setFloatPlaces() to set the number of decimal places to include.
You would normally use insertKeyValue() or insertArrayValue() instead of calling this directly as those functions take care of inserting the separtators between items.
Definition at line 841 of file JsonParserGeneratorRK.cpp.
References floatPlaces, and insertsprintf().
insertValue() [7/9]
void JsonWriter::insertValue (double value)
Inserts a floating point double value.
Use setFloatPlaces() to set the number of decimal places to include.
You would normally use insertKeyValue() or insertArrayValue() instead of calling this directly as those functions take care of inserting the separtators between items.
Definition at line 849 of file JsonParserGeneratorRK.cpp.
References floatPlaces, and insertsprintf().
Referenced by main().
insertValue() [8/9]
void JsonWriter::insertValue (const char * value) [inline]
Inserts a quoted string value. This escapes special characters and encodes utf-8.
You would normally use insertKeyValue() or insertArrayValue() instead of calling this directly as those functions take care of inserting the separtators between items.
Definition at line 1031 of file JsonParserGeneratorRK.h.
References insertString().
Referenced by insertKeyArray(), insertKeyObject(), and insertKeyValue().
insertValue() [9/9]
void JsonWriter::insertValue (const String & value) [inline]
Inserts a quoted string value.
This escapes special characters and encodes utf-8. See also the version that takes a plain const char *.
You would normally use insertKeyValue() or insertArrayValue() instead of calling this directly as those functions take care of inserting the separtators between items.
Definition at line 1042 of file JsonParserGeneratorRK.h.
References String::c_str(), and insertString().
insertVector()
template<class T >
void JsonWriter::insertVector (std::vector< T > vec) [inline]
Inserts an array of values into an array.
Uses templates so you can pass any type object that's supported by insertValue() overloads, for example: bool, int, float, double, const char *.
Definition at line 1118 of file JsonParserGeneratorRK.h.
insertvsprintf()
void JsonWriter::insertvsprintf (const char * fmt, va_list ap)
Used internally to insert using snprintf formatting with a va_list.
Used internally. You should use insertKeyValue() or insertArrayValue() with a string, float, or double instead.
This method does not quote or escape the string - it's used mainly for formatting numbers.
Definition at line 809 of file JsonParserGeneratorRK.cpp.
References JsonBuffer::buffer, JsonBuffer::bufferLen, JsonBuffer::offset, and truncated.
Referenced by insertsprintf().
isTruncated()
bool JsonWriter::isTruncated () const [inline]
If you try to insert more data than will fit in the buffer, the isTruncated flag will be set, and the buffer will likely not be valid JSON and should not be used.
Definition at line 1142 of file JsonParserGeneratorRK.h.
References truncated.
setFloatPlaces()
void JsonWriter::setFloatPlaces (int floatPlaces) [inline]
Sets the number of digits for formatting float and double values.
Parameters
floatPlaces The number of decimal places for float and double. Set it to -1 to use the default for snprintf. -1 is the default value if you don't call setFloatPlaces.
Definition at line 1150 of file JsonParserGeneratorRK.h.
References floatPlaces.
Referenced by main().
setIsFirst()
void JsonWriter::setIsFirst (bool isFirst = true)
Used internally to set the current isFirst flag in the context.
Definition at line 875 of file JsonParserGeneratorRK.cpp.
References context, contextIndex, and JsonWriterContext::isFirst.
Referenced by insertKeyArray(), insertKeyObject(), and JsonModifier::startAppend().
startArray()
bool JsonWriter::startArray () [inline]
Start a new JSON array. Make sure you finish it with finishObjectOrArray()
Definition at line 958 of file JsonParserGeneratorRK.h.
References startObjectOrArray().
Referenced by insertKeyArray(), JsonWriterAutoArray::JsonWriterAutoArray(), and main().
startObject()
bool JsonWriter::startObject () [inline]
Start a new JSON object. Make sure you finish it with finishObjectOrArray()
Definition at line 953 of file JsonParserGeneratorRK.h.
References startObjectOrArray().
Referenced by insertKeyObject(), JsonWriterAutoObject::JsonWriterAutoObject(), and main().
startObjectOrArray()
bool JsonWriter::startObjectOrArray (char startChar, char endChar)
Used internally to start an object or array.
Used internally; you should use startObject() or startArray() instead. Make sure you finish any started object or array using finishObjectOrArray().
Definition at line 679 of file JsonParserGeneratorRK.cpp.
References context, contextIndex, insertChar(), insertCheckSeparator(), JsonWriterContext::isFirst, MAX_NESTED_CONTEXT, and JsonWriterContext::terminator.
Referenced by startArray(), and startObject().
Member Data Documentation
context
JsonWriterContext JsonWriter::context[MAX_NESTED_CONTEXT] [protected]
Structure for managing nested objects.
Definition at line 1217 of file JsonParserGeneratorRK.h.
Referenced by finishObjectOrArray(), init(), insertCheckSeparator(), setIsFirst(), and startObjectOrArray().
contextIndex
size_t JsonWriter::contextIndex [protected]
Index into the context for the current level of nesting.
Definition at line 1216 of file JsonParserGeneratorRK.h.
Referenced by finishObjectOrArray(), init(), insertCheckSeparator(), setIsFirst(), and startObjectOrArray().
floatPlaces
int JsonWriter::floatPlaces [protected]
default number of places to display for floating point numbers (default is -1, the default for sprintf)
Definition at line 1219 of file JsonParserGeneratorRK.h.
Referenced by insertValue(), JsonWriter(), and setFloatPlaces().
MAX_NESTED_CONTEXT
const size_t JsonWriter::MAX_NESTED_CONTEXT = 9 [static]
This constant is the maximum number of nested objects that are supported; the actual number is one less than this so when set to 9 you can have eight objects nested in each other.
Overhead is 8 bytes per nested context, so 9 elements is 72 bytes.
Definition at line 1213 of file JsonParserGeneratorRK.h.
Referenced by startObjectOrArray().
truncated
bool JsonWriter::truncated [protected]
true if data was added that didn't fit and was truncated
Definition at line 1218 of file JsonParserGeneratorRK.h.
Referenced by init(), insertChar(), insertvsprintf(), and isTruncated().
The documentation for this class was generated from the following files:
lib/JsonParserGeneratorRK/src/JsonParserGeneratorRK.h
lib/JsonParserGeneratorRK/src/JsonParserGeneratorRK.cpp