JsonModifier Class Reference
Class for modifying a JSON object in place, without needing to make a copy of it.
#include <JsonParserGeneratorRK.h>
Public Member Functions
 JsonModifier (JsonParser & jp)
virtual ~JsonModifier ()
template<class T >
void insertOrUpdateKeyValue (const JsonParserGeneratorRK::jsmntok_t *container, const char *key, T value)
Inserts or updates a key/value pair into an object.
template<class T >
void appendArrayValue (const JsonParserGeneratorRK::jsmntok_t *arrayToken, T value)
Appends a value to an array.
bool removeKeyValue (const JsonParserGeneratorRK::jsmntok_t *container, const char *key)
Removes a key and value from an object.
bool removeArrayIndex (const JsonParserGeneratorRK::jsmntok_t *container, size_t index)
Removes an entry from an array.
bool startModify (const JsonParserGeneratorRK::jsmntok_t *token)
Low level function to modify a token in place.
bool startAppend (const JsonParserGeneratorRK::jsmntok_t *arrayOrObjectToken)
Low level function to append to an object or array.
void finish ()
Finish modifying the object.
 JsonParserGeneratorRK::jsmntok_t tokenWithQuotes (const JsonParserGeneratorRK::jsmntok_t *tok) const
Return a copy of tok, but moving so start and end include the double quotes for strings.
int findLeftComma (const JsonParserGeneratorRK::jsmntok_t *tok) const
Find the offset of the comma to the left of the token, or -1 if there isn't one.
int findRightComma (const JsonParserGeneratorRK::jsmntok_t *tok) const
Find the offset of the comma to the left of the token, or -1 if there isn't one.
Protected Attributes
 JsonParser & jp
The JsonParser object passed to the constructor.
int start = -1
Start offset in the buffer. Set to -1 when startModify() or startAppend() is not in progress.
int origAfter = 0
Number of bytes after the insertion position, saved at saveLoc when start is in progress.
int saveLoc = 0
Location where data is temporarily saved until finish() is called.
Additional Inherited Members
Detailed Description
Class for modifying a JSON object in place, without needing to make a copy of it.
Make sure the underlying JsonParser is big enough to hold the modified object. If you use JsonParserStatic<> make sure you have enough bytes and tokens.
The most commonly used method is insertOrUpdateKeyValue(). This inserts or updates a key in an array. Another is appendArrayValue() which appends a value to an array. Both methods are templated so you can use them with any valid type supported by insertValue() in JsonWriter: bool, int, float, double, const char *.
This class is a subclass of JsonWriter, so you can also use the low-level functions and JsonWriter methods to do unusual object manipulations.
You can also use removeKeyValue() and removeArrayIndex() to remove keys or array entries.
Definition at line 1323 of file JsonParserGeneratorRK.h.
Constructor & Destructor Documentation
JsonModifier()
JsonModifier::JsonModifier (JsonParser & jp)
Definition at line 881 of file JsonParserGeneratorRK.cpp.
References jp.
Referenced by main().
                                         : jp(jp) {
}
~JsonModifier()
JsonModifier::~JsonModifier () [virtual]
Definition at line 885 of file JsonParserGeneratorRK.cpp.
                            {
}
Member Function Documentation
appendArrayValue()
template<class T >
void JsonModifier::appendArrayValue (const JsonParserGeneratorRK::jsmntok_t * arrayToken, T value) [inline]
Appends a value to an array.
Uses templates so you can pass any type object that's supported by insertValue() overloads, for example: bool, int, float, double, const char *.
To modify the outermost array, use jp.getOuterArray() for the arrayToken. You can also modify arrays in an object using getValueTokenByKey().
Note: This method call jp.parse() so any jsmntok_t may be changed by this method. If you've fetched one, such as by using getValueTokenByKey() be sure to fetch it again to be safe.
Definition at line 1363 of file JsonParserGeneratorRK.h.
References finish(), and startAppend().
Referenced by main().
                                                                                     {
        startAppend(arrayToken);
        insertArrayValue(value);
        finish();
    }
findLeftComma()
int JsonModifier::findLeftComma (const JsonParserGeneratorRK::jsmntok_t * tok) const
Find the offset of the comma to the left of the token, or -1 if there isn't one.
Used internally, you probably won't need to use this.
Definition at line 1058 of file JsonParserGeneratorRK.cpp.
References JsonBuffer::getBuffer(), jp, JsonParserGeneratorRK::jsmntok_t::start, and tokenWithQuotes().
Referenced by main(), removeArrayIndex(), and removeKeyValue().
                                                                               {
    JsonParserGeneratorRK::jsmntok_t expandedToken = tokenWithQuotes(tok);
    int ii = expandedToken.start - 1;
    while(ii >= 0 && jp.getBuffer()[ii] == ' ') {
        // Whitespace
        ii--;
    }
    // printf("after whitespace check ii=%d c=%c\n", ii, jp.getBuffer()[ii]);
    if (ii < 0 || jp.getBuffer()[ii] != ',') {
        return -1;
    }
    return ii;
}
findRightComma()
int JsonModifier::findRightComma (const JsonParserGeneratorRK::jsmntok_t * tok) const
Find the offset of the comma to the left of the token, or -1 if there isn't one.
Used internally, you probably won't need to use this.
Definition at line 1077 of file JsonParserGeneratorRK.cpp.
References JsonParserGeneratorRK::jsmntok_t::end, JsonBuffer::getBuffer(), JsonBuffer::getOffset(), jp, and tokenWithQuotes().
Referenced by main(), removeArrayIndex(), and removeKeyValue().
                                                                                {
    JsonParserGeneratorRK::jsmntok_t expandedToken = tokenWithQuotes(tok);
    int ii = expandedToken.end;
    while(ii < jp.getOffset() && jp.getBuffer()[ii] == ' ') {
        // Whitespace
        ii++;
    }
    if (ii < 0 || jp.getBuffer()[ii] != ',') {
        return -1;
    }
    return ii;
}
finish()
void JsonModifier::finish ()
Finish modifying the object.
Finish must be called after startModify or startAppend otherwise the object will be corrupted.
Note: This method call jp.parse() so any jsmntok_t may be changed by this method. If you've fetched one, such as by using getValueTokenByKey() be sure to fetch it again to be safe.
The high level function like insertOrUpdateKeyValue, appendArrayValue, removeKeyValue, and removeArrayIndex internally call finish so you should not call it again with those methods.
Definition at line 1033 of file JsonParserGeneratorRK.cpp.
References JsonBuffer::getBuffer(), JsonBuffer::getOffset(), jp, origAfter, JsonParser::parse(), saveLoc, JsonBuffer::setOffset(), and start.
Referenced by appendArrayValue(), insertOrUpdateKeyValue(), and main().
                          {
    if (start == -1) {
        return;
    }
    //printf("finishing offset=%d\n", getOffset());
    if (origAfter > 0) {
        memmove(jp.getBuffer() + start + getOffset(), jp.getBuffer() + saveLoc,
      origAfter);
    }
    jp.setOffset(start + getOffset() + origAfter);
    jp.parse();
    start = -1;
}
insertOrUpdateKeyValue()
template<class T >
void JsonModifier::insertOrUpdateKeyValue (const JsonParserGeneratorRK::jsmntok_t * container, const char * key, T value) [inline]
Inserts or updates a key/value pair into an object.
Uses templates so you can pass any type object that's supported by insertValue() overloads, for example: bool, int, float, double, const char *.
To modify the outermost object, use jp.getOuterObject() for the container.
Note: This method call jp.parse() so any jsmntok_t may be changed by this method. If you've fetched one, such as by using getValueTokenByKey() be sure to fetch it again to be safe.
Definition at line 1340 of file JsonParserGeneratorRK.h.
References finish(), removeKeyValue(), and startAppend().
Referenced by main().
                                                                                                           
      {
        // Remove existing item (ignore failure, as the key might not exist)
        removeKeyValue(container, key);
        // Create a new key/value pair
        startAppend(container);
        insertKeyValue(key, value);
        finish();
    }
removeArrayIndex()
bool JsonModifier::removeArrayIndex (const JsonParserGeneratorRK::jsmntok_t * container, size_t index)
Removes an entry from an array.
Note: This method call jp.parse() so any jsmntok_t may be changed by this method. If you've fetched one, such as by using getValueTokenByKey() be sure to fetch it again to be safe.
Definition at line 944 of file JsonParserGeneratorRK.cpp.
References JsonParserGeneratorRK::jsmntok_t::end, findLeftComma(), findRightComma(), JsonBuffer::getBuffer(), JsonBuffer::getOffset(), JsonParser::getTokenByIndex(), jp, origAfter, JsonParser::parse(), JsonBuffer::setOffset(), JsonParserGeneratorRK::jsmntok_t::start, and tokenWithQuotes().
Referenced by main().
                                                                                                 {
    const JsonParserGeneratorRK::jsmntok_t *tok = jp.getTokenByIndex(container, index);
    if (!tok) {
        return false;
    }
    const JsonParserGeneratorRK::jsmntok_t expandedToken = tokenWithQuotes(tok);
    int left = findLeftComma(tok);
    int right = findRightComma(tok);
    if (left >= 0 && right >= 0) {
        // Commas on both sides, just remove the one on the right
        left = expandedToken.start;
    }
    else
    if (left >= 0) {
        // Only comma on left, removing the last item so remove the comma
        right = expandedToken.end;
    }
    else
    if (right >= 0) {
        // Only comma on the right, removing the first item so remove the comma
        right++;
        left = expandedToken.start;
    }
    else {
        // Single item, leaving array empty afterwards (both < 0), no commads
        left = expandedToken.start;
        right = expandedToken.end;
    }
    origAfter = jp.getOffset() - right;
    if (origAfter > 0) {
        memmove(jp.getBuffer() + left, jp.getBuffer() + right, origAfter);
    }
    jp.setOffset(left + origAfter);
    jp.parse();
    return true;
}
removeKeyValue()
bool JsonModifier::removeKeyValue (const JsonParserGeneratorRK::jsmntok_t * container, const char * key)
Removes a key and value from an object.
Note: This method call jp.parse() so any jsmntok_t may be changed by this method. If you've fetched one, such as by using getValueTokenByKey() be sure to fetch it again to be safe.
Definition at line 890 of file JsonParserGeneratorRK.cpp.
References JsonParserGeneratorRK::jsmntok_t::end, findLeftComma(), findRightComma(), JsonBuffer::getBuffer(), JsonBuffer::getOffset(), JsonParser::getValueTokenByKey(), jp, origAfter, JsonParser::parse(), JsonBuffer::setOffset(), JsonParserGeneratorRK::jsmntok_t::start, and tokenWithQuotes().
Referenced by insertOrUpdateKeyValue(), and main().
                                                                                                  {
    const JsonParserGeneratorRK::jsmntok_t *keyToken, *valueToken;
    bool bResult = jp.getValueTokenByKey(container, key, valueToken);
    if (!bResult) {
        return false;
    }
    // The key token always proceeds the value token
    keyToken = &valueToken[-1];
    // Include the double quotes
    const JsonParserGeneratorRK::jsmntok_t expandedKeyToken = tokenWithQuotes(keyToken);
    const JsonParserGeneratorRK::jsmntok_t expandedValueToken = tokenWithQuotes(valueToken);
    int left = findLeftComma(keyToken);
    int right = findRightComma(valueToken);
    if (left >= 0 && right >= 0) {
        // Commas on both sides, just remove the one on the right
        left = expandedKeyToken.start;
        right++;
    }
    else
    if (left >= 0) {
        // Only comma on left, removing the last item so remove the comma
        right = expandedValueToken.end;
    }
    else
    if (right >= 0) {
        // Only comma on the right, removing the first item so remove the comma
        right++;
        left = expandedKeyToken.start;
    }
    else {
        // Single item, leaving array empty afterwards (both < 0), no commads
        left = expandedKeyToken.start;
        right = expandedValueToken.end;
    }
    origAfter = jp.getOffset() - right;
    if (origAfter > 0) {
        memmove(jp.getBuffer() + left, jp.getBuffer() + right, origAfter);
    }
    jp.setOffset(left + origAfter);
    jp.parse();
    return true;
}
startAppend()
bool JsonModifier::startAppend (const JsonParserGeneratorRK::jsmntok_t * arrayOrObjectToken)
Low level function to append to an object or array.
Parameters
arrayOrObjectToken the jsmntok_t to append to. This must be an object or array token.
You must call finish() after modification is done to restore the object to a valid state.
Definition at line 1009 of file JsonParserGeneratorRK.cpp.
References JsonParserGeneratorRK::jsmntok_t::end, JsonBuffer::getBuffer(), JsonBuffer::getBufferLen(), JsonBuffer::getOffset(), JsonWriter::init(), jp, origAfter, saveLoc, JsonBuffer::setBuffer(), JsonWriter::setIsFirst(), JsonParserGeneratorRK::jsmntok_t::size, and start.
Referenced by appendArrayValue(), insertOrUpdateKeyValue(), and main().
                                                                                       {
    if (start != -1) {
        // Modification or insertion already in progress
        return false;
    }
    start = arrayOrObjectToken->end - 1; // Before the closing ] or }
    origAfter = jp.getOffset() - start;
    saveLoc = jp.getBufferLen() - origAfter;
    if (origAfter > 0) {
        memmove(jp.getBuffer() + saveLoc, jp.getBuffer() + start, origAfter);
    }
    setBuffer(jp.getBuffer() + start, saveLoc - start);
    init();
    // If array is not empty, add a separator
    setIsFirst(arrayOrObjectToken->size == 0);
    return true;
}
startModify()
bool JsonModifier::startModify (const JsonParserGeneratorRK::jsmntok_t * token)
Low level function to modify a token in place.
Parameters
token the jsmntok_t to modify
You must call finish() after modification is done to restore the object to a valid state!
Note: insertOrUpdateKeyValue() does not use this. Instead it removes then appends the new value. The reason is that startModify does not work if you change the type of the data to or from a string. This is tricky to deal with correctly, so it's easier to just remove and add the item again.
Definition at line 988 of file JsonParserGeneratorRK.cpp.
References JsonParserGeneratorRK::jsmntok_t::end, JsonBuffer::getBuffer(), JsonBuffer::getBufferLen(), JsonBuffer::getOffset(), JsonWriter::init(), jp, origAfter, saveLoc, JsonBuffer::setBuffer(), JsonParserGeneratorRK::jsmntok_t::start, and start.
Referenced by main().
                                                                          {
    if (start != -1) {
        // Modification or insertion already in progress
        return false;
    }
    start = token->start;
    origAfter = jp.getOffset() - token->end;
    saveLoc = jp.getBufferLen() - origAfter;
    //printf("start=%d origAfter=%d saveLoc=%d bufferSize=%d\n", start, origAfter, saveLoc, saveLoc -
       start);
    if (origAfter > 0) {
        memmove(jp.getBuffer() + saveLoc, jp.getBuffer() + token->end, origAfter);
    }
    setBuffer(jp.getBuffer() + start, saveLoc - start);
    init();
    return true;
}
tokenWithQuotes()
 JsonParserGeneratorRK::jsmntok_t JsonModifier::tokenWithQuotes (const JsonParserGeneratorRK::jsmntok_t * tok) const
Return a copy of tok, but moving so start and end include the double quotes for strings.
Used internally, you probably won't need to use this.
Definition at line 1048 of file JsonParserGeneratorRK.cpp.
References JsonParserGeneratorRK::jsmntok_t::end, JsonParserGeneratorRK::JSMN_STRING, JsonParserGeneratorRK::jsmntok_t::start, and JsonParserGeneratorRK::jsmntok_t::type.
Referenced by findLeftComma(), findRightComma(), removeArrayIndex(), and removeKeyValue().
                                                                                                           
       {
    JsonParserGeneratorRK::jsmntok_t expandedToken = *tok;
    if (tok->type == JsonParserGeneratorRK::JSMN_STRING) {
        expandedToken.start--;
        expandedToken.end++;
    }
    return expandedToken;
}
Member Data Documentation
jp
 JsonParser& JsonModifier::jp [protected]
The JsonParser object passed to the constructor.
Definition at line 1447 of file JsonParserGeneratorRK.h.
Referenced by findLeftComma(), findRightComma(), finish(), JsonModifier(), removeArrayIndex(), removeKeyValue(), startAppend(), and startModify().
origAfter
int JsonModifier::origAfter = 0 [protected]
Number of bytes after the insertion position, saved at saveLoc when start is in progress.
Definition at line 1449 of file JsonParserGeneratorRK.h.
Referenced by finish(), removeArrayIndex(), removeKeyValue(), startAppend(), and startModify().
saveLoc
int JsonModifier::saveLoc = 0 [protected]
Location where data is temporarily saved until finish() is called.
Definition at line 1450 of file JsonParserGeneratorRK.h.
Referenced by finish(), startAppend(), and startModify().
start
int JsonModifier::start = -1 [protected]
Start offset in the buffer. Set to -1 when startModify() or startAppend() is not in progress.
Definition at line 1448 of file JsonParserGeneratorRK.h.
Referenced by finish(), startAppend(), and startModify().
The documentation for this class was generated from the following files:
lib/JsonParserGeneratorRK/src/ JsonParserGeneratorRK.h
lib/JsonParserGeneratorRK/src/ JsonParserGeneratorRK.cpp