String Class Reference
Wiring String: A class to hold and manipulate a dynamically allocated string.
#include <spark_wiring_string.h>
Public Member Functions
 String (const char *cstr=``)
Construct a String object from a c-string (null-terminated)
 String (const char *cstr, unsigned int length)
Construct a String object from a pointer and length.
 String (const String &str)
Construct a String object as a copy of another string.
 String (const __FlashStringHelper *pstr)
 String (const Printable &printable)
Construct a String object from any Printable object.
 String (char c)
Construct a String containing a single character.
 String (unsigned char b, unsigned char base=10)
Construct a String from a unsigned char (uint8_t) value, expressed as a number.
 String (int value, unsigned char base=10)
Construct a String from a int (32 bit signed integer) value, expressed as a number.
 String (unsigned int value, unsigned char base=10)
Construct a String from a unsigned int (32 bit unsigned integer) value, expressed as a number.
 String (long value, unsigned char base=10)
Construct a String from a long (32 bit signed integer) value, expressed as a number.
 String (unsigned long value, unsigned char base=10)
Construct a String from a unsigned long (32 bit unsigned integer) value, expressed as a number.
 String (float value, int decimalPlaces=6)
Construct a String from a float (32 bit single precision floating point) value, expressed as a number.
 String (double value, int decimalPlaces=6)
Construct a String from a double (64 bit double precision floating point) value, expressed as a number.
 ~String (void)
Destructor. Also deletes the underlying dynamically allocated string.
unsigned char reserve (unsigned int size)
Reserves a buffer of size.
unsigned int length (void) const
Returns the length of the string in bytes.
 String & operator= (const String &rhs)
Assigns this string to have a copy of String rhs.
 String & operator= (const char *cstr)
Assigns this string to have a copy of c-string (null-terminated) cstr.
 String & operator= (const __FlashStringHelper *pstr)
 operator const char * () const
Returns the contents this String as a c-string (null-terminated)
unsigned char concat (const String &str)
Append (concatenate) a String object to the end of this String, modifying this string in place.
unsigned char concat (const char *cstr)
Append (concatenate) a c-string (null-terminated) to the end of this String, modifying this string in place.
unsigned char concat (const __FlashStringHelper *str)
unsigned char concat (char c)
Append (concatenate) a single character to the end of this String, modifying this string in place.
unsigned char concat (unsigned char c)
Append (concatenate) the byte value c to the end of this String as a decimal number 0 - 255, modifying this string in place.
unsigned char concat (int num)
Append (concatenate) the integer value num to the end of this String as a signed decimal number (base 10), modifying this string in place.
unsigned char concat (unsigned int num)
Append (concatenate) the unsigned integer value num to the end of this String as a unsigned decimal number (base 10), modifying this string in place.
unsigned char concat (long num)
Append (concatenate) the long integer value num to the end of this String as a signed decimal number (base 10), modifying this string in place.
unsigned char concat (unsigned long num)
Append (concatenate) the unsigned long value num to the end of this String as a unsigned decimal number (base 10), modifying this string in place.
unsigned char concat (float num)
Append (concatenate) the float n to the end of this String as a decimal number (base 10), modifying this string in place.
unsigned char concat (double num)
Append (concatenate) the double precision float n to the end of this String as a decimal number (base 10), modifying this string in place.
 String & operator+= (const String &rhs)
Appends (concatenate) a String object to the end of this String, modifying this string in place.
 String & operator+= (const char *cstr)
Appends (concatenate) a c-string (null-terminated) to the end of this String, modifying this string in place.
 String & operator+= (char c)
Appends (concatenate) a single character to the end of this String, modifying this string in place.
 String & operator+= (unsigned char num)
Append (concatenate) the byte value num to the end of this String as a decimal number 0 - 255, modifying this string in place.
 String & operator+= (int num)
Append (concatenate) the integer value num to the end of this String as a signed decimal number (base 10), modifying this string in place.
 String & operator+= (unsigned int num)
Append (concatenate) the unsigned integer value num to the end of this String as a unsigned decimal number (base 10), modifying this string in place.
 String & operator+= (long num)
Append (concatenate) the long integer value num to the end of this String as a signed decimal number (base 10), modifying this string in place.
 String & operator+= (unsigned long num)
Append (concatenate) the unsigned long value num to the end of this String as a unsigned decimal number (base 10), modifying this string in place.
 operator StringIfHelperType () const
int compareTo (const String &s) const
Compares this string to another string using strcmp (case-sensitive)
unsigned char equals (const String &s) const
Returns true if this string is equal to another string (case-sensitive)
unsigned char equals (const char *cstr) const
Returns true if this string equal to another string (case-sensitive)
unsigned char operator== (const String &rhs) const
Returns true if this string is equal to another string (case-sensitive)
unsigned char operator== (const char *cstr) const
Returns true if this string equal to another string (case-sensitive)
unsigned char operator!= (const String &rhs) const
Returns true if this string is greater than to another string (case-sensitive)
unsigned char operator!= (const char *cstr) const
Returns true if this string not equal to another string (case-sensitive)
unsigned char operator< (const String &rhs) const
Returns true if this string is less than to another string (case-sensitive)
unsigned char operator> (const String &rhs) const
Returns true if this string is greater than to another string (case-sensitive)
unsigned char operator<= (const String &rhs) const
Returns true if this string is less than or equal to another string (case-sensitive)
unsigned char operator>= (const String &rhs) const
Returns true if this string is greater than or equal to another string (case-sensitive)
unsigned char equalsIgnoreCase (const String &s) const
Returns true if this string equals another string (case-insensitive)
unsigned char startsWith (const String &prefix) const
Returns true if this string starts with prefix (case-sensitive)
unsigned char startsWith (const String &prefix, unsigned int offset) const
Returns true if this string contains prefix at specified offset (case-sensitive)
unsigned char endsWith (const String &suffix) const
Returns true if this string ends with suffix (case-sensitive)
char charAt (unsigned int index) const
Gets the character at offset index.
void setCharAt (unsigned int index, char c)
Set the character at offset index.
char operator[] (unsigned int index) const
Gets the character at offset index.
char & operator[] (unsigned int index)
Set the character at offset index.
void getBytes (unsigned char *buf, unsigned int bufsize, unsigned int index=0) const
Copy the data out of this String into another buffer.
void toCharArray (char *buf, unsigned int bufsize, unsigned int index=0) const
Copy the data out of this String into another buffer.
const char * c_str () const
Returns a c-string (null-terminated)
int indexOf (char ch) const
Search this string for a given character.
int indexOf (char ch, unsigned int fromIndex) const
Search this string for a given character starting at an offset.
int indexOf (const String &str) const
Search this string for a given String.
int indexOf (const String &str, unsigned int fromIndex) const
Search this string for a given String starting at an offset.
int lastIndexOf (char ch) const
Search this string for a given character, starting at the end.
int lastIndexOf (char ch, unsigned int fromIndex) const
Search this string for a given character, starting at the fromIndex and going toward the beginning.
int lastIndexOf (const String &str) const
Search this string for a last occurrence of str.
int lastIndexOf (const String &str, unsigned int fromIndex) const
Search this string for a last occurrence of str starting at fromIndex.
 String substring (unsigned int beginIndex) const
Returns a String object with a copy of the characters starting at beginIndex through the end of the string.
 String substring (unsigned int beginIndex, unsigned int endIndex) const
Returns a String object with a copy of the characters in the specified range.
 String & replace (char find, char replace)
Replaces every occurrence of a character in the string with another character, modifying it in place.
 String & replace (const String &find, const String &replace)
Replaces every occurrence of a String with another String, modifying it in place.
 String & remove (unsigned int index)
Removes characters from the String, modifying it in place.
 String & remove (unsigned int index, unsigned int count)
Removes characters from the String, modifying it in place.
 String & toLowerCase (void)
Converts this String to lower case, modifying it in place.
 String & toUpperCase (void)
Converts this String to upper case, modifying it in place.
 String & trim (void)
Removes leading an trailing white spaces from this string, modifying it in place.
long toInt (void) const
Converts this string to a signed integer (32-bit)
float toFloat (void) const
Converts this string to a float (single precision floating point value)
Static Public Member Functions
static String format (const char *format,...)
Uses sprintf-style formatting to build a String object [static].
Protected Member Functions
void init (void)
void invalidate (void)
unsigned char changeBuffer (unsigned int maxStrLen)
unsigned char concat (const char *cstr, unsigned int length)
 String & copy (const char *cstr, unsigned int length)
 String & copy (const __FlashStringHelper *pstr, unsigned int length)
Protected Attributes
char * buffer
The buffer containing the data. It is always null-terminated.
unsigned int capacity
The capacity of the buffer. The longest string is one byte less than this.
unsigned int len
The String length (not counting the null terminator).
unsigned char flags
Unused, for future features.
Private Types
typedef void(String::* StringIfHelperType) () const
Private Member Functions
void StringIfHelper () const
Friends
class StringPrintableHelper
 StringSumHelper & operator+ (const StringSumHelper &lhs, const String &rhs)
Append (concatenate) a String to the end of lhs.
 StringSumHelper & operator+ (const StringSumHelper &lhs, const char *cstr)
Append (concatenate) a c-string (null-terminated) to the end of lhs.
 StringSumHelper & operator+ (const StringSumHelper &lhs, char c)
Append (concatenate) the character c the end of lhs a.
 StringSumHelper & operator+ (const StringSumHelper &lhs, unsigned char num)
Append (concatenate) the unsigned char num to the end of lhs as a decimal number (base 10)
 StringSumHelper & operator+ (const StringSumHelper &lhs, int num)
Append (concatenate) the signed int num to the end of lhs as a decimal number (base 10)
 StringSumHelper & operator+ (const StringSumHelper &lhs, unsigned int num)
Append (concatenate) the unsigned int num to the end of lhs as a decimal number (base 10)
 StringSumHelper & operator+ (const StringSumHelper &lhs, long num)
Append (concatenate) the long integer num to the end of lhs as a decimal number (base 10)
 StringSumHelper & operator+ (const StringSumHelper &lhs, unsigned long num)
Append (concatenate) the unsigned long integer to the end of lhs as a decimal number (base 10)
 StringSumHelper & operator+ (const StringSumHelper &lhs, float num)
Append (concatenate) the float num to the end of lhs as a decimal number (base 10)
 StringSumHelper & operator+ (const StringSumHelper &lhs, double num)
Append (concatenate) the double precision float num to the end of lhs as a decimal number (base 10)
Detailed Description
Wiring String: A class to hold and manipulate a dynamically allocated string.
Definition at line 54 of file spark_wiring_string.h.
Member Typedef Documentation
StringIfHelperType
typedef void(String::* String::StringIfHelperType) () const [private]
Definition at line 59 of file spark_wiring_string.h.
Constructor & Destructor Documentation
String() [1/13]
String::String (const char * cstr = ``)
Construct a String object from a c-string (null-terminated)
Parameters
cstr The string to copy, optional. If not specified, starts with an empty string
Definition at line 69 of file spark_wiring_string.cpp.
References copy(), and init().
Referenced by StringSumHelper::StringSumHelper().
{
    init();
    if (cstr) copy(cstr, strlen(cstr));
}
String() [2/13]
String::String (const char * cstr, unsigned int length)
Construct a String object from a pointer and length.
Parameters
cstr Pointer to a bytes, typically ASCII or UTF-8. Does not need to be null-terminated.
length Length in bytes of the string.
String() [3/13]
String::String (const String & str)
Construct a String object as a copy of another string.
Parameters
str The string to copy. Changes made to str in the future won't be reflected in this copy.
Definition at line 75 of file spark_wiring_string.cpp.
References init(), and operator=().
Referenced by StringSumHelper::StringSumHelper().
{
    init();
    *this = value;
}
String() [4/13]
String::String (const __FlashStringHelper * pstr)
String() [5/13]
String::String (const Printable & printable)
Construct a String object from any Printable object.
Parameters
printable The Printable object. The toPrint() method will be called on it to print to this String the textual representation of the object.
For example, IPAddress is printable, so you can pass an IPAddress to this constructor and this string will contain a textual representation of the IPAddress (dotted quad).
Definition at line 780 of file spark_wiring_string.cpp.
References init(), Printable::printTo(), and StringPrintableHelper::StringPrintableHelper().
{
    init();
    StringPrintableHelper help(*this);
    printable.printTo(help);
}
String() [6/13]
String::String (char c) [explicit]
Construct a String containing a single character.
Parameters
c The character to set the String to
Definition at line 94 of file spark_wiring_string.cpp.
References init(), and operator=().
Referenced by StringSumHelper::StringSumHelper().
{
    init();
    char buf[2];
    buf[0] = c;
    buf[1] = 0;
    *this = buf;
}
String() [7/13]
String::String (unsigned char b, unsigned char base = 10) [explicit]
Construct a String from a unsigned char (uint8_t) value, expressed as a number.
Parameters
b The value.
base The number base, default is 10 (decimal). Other values include 8 (octal) and 16 (hexadecimal).
Definition at line 103 of file spark_wiring_string.cpp.
References init(), operator=(), and utoa().
Referenced by StringSumHelper::StringSumHelper().
{
    init();
    char buf[9];
    utoa(value, buf, base);
    *this = buf;
}
String() [8/13]
String::String (int value, unsigned char base = 10) [explicit]
Construct a String from a int (32 bit signed integer) value, expressed as a number.
Parameters
value The value.
base The number base, default is 10 (decimal). Other values include 8 (octal) and 16 (hexadecimal).
Definition at line 111 of file spark_wiring_string.cpp.
References init(), itoa(), and operator=().
Referenced by StringSumHelper::StringSumHelper().
{
    init();
    char buf[34];
    itoa(value, buf, base);
    *this = buf;
}
String() [9/13]
String::String (unsigned int value, unsigned char base = 10) [explicit]
Construct a String from a unsigned int (32 bit unsigned integer) value, expressed as a number.
Parameters
value The value.
base The number base, default is 10 (decimal). Other values include 8 (octal) and 16 (hexadecimal).
Definition at line 119 of file spark_wiring_string.cpp.
References init(), operator=(), and utoa().
Referenced by maxCurrentC1_test(), maxCurrentC2_test(), and StringSumHelper::StringSumHelper().
{
    init();
    char buf[33];
    utoa(value, buf, base);
    *this = buf;
}
String() [10/13]
String::String (long value, unsigned char base = 10) [explicit]
Construct a String from a long (32 bit signed integer) value, expressed as a number.
Parameters
value The value.
base The number base, default is 10 (decimal). Other values include 8 (octal) and 16 (hexadecimal).
Definition at line 127 of file spark_wiring_string.cpp.
References init(), ltoa(), and operator=().
Referenced by StringSumHelper::StringSumHelper().
{
    init();
    char buf[34];
    ltoa(value, buf, base);
    *this = buf;
}
String() [11/13]
String::String (unsigned long value, unsigned char base = 10) [explicit]
Construct a String from a unsigned long (32 bit unsigned integer) value, expressed as a number.
Parameters
value The value.
base The number base, default is 10 (decimal). Other values include 8 (octal) and 16 (hexadecimal).
Definition at line 135 of file spark_wiring_string.cpp.
References init(), operator=(), and ultoa().
Referenced by StringSumHelper::StringSumHelper().
{
    init();
    char buf[33];
    ultoa(value, buf, base);
    *this = buf;
}
String() [12/13]
String::String (float value, int decimalPlaces = 6) [explicit]
Construct a String from a float (32 bit single precision floating point) value, expressed as a number.
Parameters
value The value.
decimalPlaces The number of decimal places to show. Default = 6.
Definition at line 143 of file spark_wiring_string.cpp.
References dtoa(), init(), and operator=().
{
    init();
    char buf[33];
    dtoa(value, decimalPlaces, buf);
        *this = buf;
}
String() [13/13]
String::String (double value, int decimalPlaces = 6) [explicit]
Construct a String from a double (64 bit double precision floating point) value, expressed as a number.
Parameters
value The value.
decimalPlaces The number of decimal places to show. Default = 6.
Definition at line 151 of file spark_wiring_string.cpp.
References dtoa(), init(), and operator=().
{
    init();
    char buf[33];
    dtoa(value, decimalPlaces, buf);
        *this = buf;
}
~String()
String::~String (void)
Destructor. Also deletes the underlying dynamically allocated string.
Definition at line 158 of file spark_wiring_string.cpp.
References buffer.
{
    free(buffer);
}
Member Function Documentation
c_str()
const char* String::c_str () const [inline]
Returns a c-string (null-terminated)
This allows the String object to be passed to anything that requires a c-string. See also operator const char *.
One place where you need to explicitly use c_str() or cast is when passing a String as a variable argument to sprintf:
String str;
snprintf(buf, sizeof(buf), "string=%s", str.c_str());
If you leave off the c_str() the value won't be printed as string. This also applies to things that use sprintf internally, like Log:
Log.info("string=%s", str.c_str());
This method returns a pointer to the internal buffer. If the underlying string is reallocated because the string is appended to, this pointer will be invalid.
Definition at line 819 of file spark_wiring_string.h.
References buffer.
Referenced by JsonWriter::insertValue(), main(), operator const char *(), and operator<<().
{ return buffer; }
changeBuffer()
unsigned char String::changeBuffer (unsigned int maxStrLen) [protected]
Definition at line 192 of file spark_wiring_string.cpp.
References buffer, and capacity.
Referenced by replace(), and reserve().
{
    char *newbuffer = (char *)realloc(buffer, maxStrLen + 1);
    if (newbuffer) {
        buffer = newbuffer;
        capacity = maxStrLen;
        return 1;
    }
    return 0;
}
charAt()
char String::charAt (unsigned int index) const
Gets the character at offset index.
Parameters
index The index to set (0 = first character)
Returns
The character is 0 if the index is larger than the length of the string.
Definition at line 509 of file spark_wiring_string.cpp.
References operator[]().
{
    return operator[](loc);
}
compareTo()
int String::compareTo (const String & s) const
Compares this string to another string using strcmp (case-sensitive)
Parameters
s the string to compare to
Returns
< 0 if s is less than this, == 0 is s equals this, or > 0 if s is greater than this
Uses the C standard library function strcmp which is case-sensitive and does not correctly compare UTF-8 characters.
Definition at line 432 of file spark_wiring_string.cpp.
References buffer, and len.
Referenced by equals(), operator<(), operator<=(), operator>(), and operator>=().
{
    if (!buffer || !s.buffer) {
        if (s.buffer && s.len > 0) return 0 - *(unsigned char *)s.buffer;
        if (buffer && len > 0) return *(unsigned char *)buffer;
        return 0;
    }
    return strcmp(buffer, s.buffer);
}
concat() [1/12]
unsigned char String::concat (const String & str)
Append (concatenate) a String object to the end of this String, modifying this string in place.
Parameters
str The string to copy from. It is not modified.
Returns
true if the append succeeded or false if there was not enough memory or the parameter was invalid.
Definition at line 276 of file spark_wiring_string.cpp.
References buffer, concat(), and len.
Referenced by operator+=().
{
    return concat(s.buffer, s.len);
}
concat() [2/12]
unsigned char String::concat (const char * cstr)
Append (concatenate) a c-string (null-terminated) to the end of this String, modifying this string in place.
Parameters
cstr The string to copy from. It is not modified.
Returns
true if the append succeeded or false if there was not enough memory or the parameter was invalid.
Definition at line 292 of file spark_wiring_string.cpp.
References concat().
Referenced by operator+=().
{
    if (!cstr) return 0;
    return concat(cstr, strlen(cstr));
}
concat() [3/12]
unsigned char String::concat (const __FlashStringHelper * str)
concat() [4/12]
unsigned char String::concat (char c)
Append (concatenate) a single character to the end of this String, modifying this string in place.
Parameters
c The character to append.
Returns
true if the append succeeded or false if there was not enough memory.
Definition at line 298 of file spark_wiring_string.cpp.
References concat().
Referenced by JsonParserString::append(), operator+(), operator+=(), and StringPrintableHelper::write().
{
    char buf[2];
    buf[0] = c;
    buf[1] = 0;
    return concat(buf, 1);
}
concat() [5/12]
unsigned char String::concat (unsigned char c)
Append (concatenate) the byte value c to the end of this String as a decimal number 0 - 255, modifying this string in place.
Parameters
c The value to append.
Returns
true if the append succeeded or false if there was not enough memory.
Definition at line 306 of file spark_wiring_string.cpp.
References concat(), and itoa().
Referenced by operator+(), and operator+=().
{
    char buf[4];
    itoa(num, buf, 10);
    return concat(buf, strlen(buf));
}
concat() [6/12]
unsigned char String::concat (int num)
Append (concatenate) the integer value num to the end of this String as a signed decimal number (base 10), modifying this string in place.
Parameters
num The value to append.
Returns
true if the append succeeded or false if there was not enough memory.
Definition at line 313 of file spark_wiring_string.cpp.
References concat(), and itoa().
Referenced by allowUser_callback(), maxCurrentC1_test(), maxCurrentC2_test(), operator+(), and operator+=().
{
    char buf[7];
    itoa(num, buf, 10);
    return concat(buf, strlen(buf));
}
concat() [7/12]
unsigned char String::concat (unsigned int num)
Append (concatenate) the unsigned integer value num to the end of this String as a unsigned decimal number (base 10), modifying this string in place.
Parameters
num The value to append.
Returns
true if the append succeeded or false if there was not enough memory.
Definition at line 320 of file spark_wiring_string.cpp.
References concat(), and utoa().
Referenced by operator+(), and operator+=().
{
    char buf[6];
    utoa(num, buf, 10);
    return concat(buf, strlen(buf));
}
concat() [8/12]
unsigned char String::concat (long num)
Append (concatenate) the long integer value num to the end of this String as a signed decimal number (base 10), modifying this string in place.
Parameters
num The value to append.
Returns
true if the append succeeded or false if there was not enough memory.
Definition at line 327 of file spark_wiring_string.cpp.
References concat(), and ltoa().
Referenced by operator+(), and operator+=().
{
    char buf[12];
    ltoa(num, buf, 10);
    return concat(buf, strlen(buf));
}
concat() [9/12]
unsigned char String::concat (unsigned long num)
Append (concatenate) the unsigned long value num to the end of this String as a unsigned decimal number (base 10), modifying this string in place.
Parameters
num The value to append.
Returns
true if the append succeeded or false if there was not enough memory.
Definition at line 334 of file spark_wiring_string.cpp.
References concat(), DEC, and ultoa().
Referenced by operator+(), and operator+=().
{
    char buf[11];
    ultoa(num, buf, DEC);
    return concat(buf, strlen(buf));
}
concat() [10/12]
unsigned char String::concat (float num)
Append (concatenate) the float n to the end of this String as a decimal number (base 10), modifying this string in place.
Parameters
num The value to append.
Returns
true if the append succeeded or false if there was not enough memory.
Definition at line 341 of file spark_wiring_string.cpp.
References concat(), and dtoa().
Referenced by operator+().
{
    char buf[20];
    dtoa(num, 6, buf);
    return concat(buf, strlen(buf));
}
concat() [11/12]
unsigned char String::concat (double num)
Append (concatenate) the double precision float n to the end of this String as a decimal number (base 10), modifying this string in place.
Parameters
num The value to append.
Returns
true if the append succeeded or false if there was not enough memory.
Definition at line 348 of file spark_wiring_string.cpp.
References concat(), and dtoa().
Referenced by operator+().
{
    char buf[20];
    dtoa(num, 6, buf);
    return concat(buf, strlen(buf));
}
concat() [12/12]
unsigned char String::concat (const char * cstr, unsigned int length) [protected]
Definition at line 281 of file spark_wiring_string.cpp.
References buffer, len, and reserve().
Referenced by concat(), operator+(), and StringPrintableHelper::write().
{
    unsigned int newlen = len + length;
    if (!cstr) return 0;
    if (length == 0) return 1;
    if (!reserve(newlen)) return 0;
    strcpy(buffer + len, cstr);
    len = newlen;
    return 1;
}
copy() [1/2]
 String & String::copy (const char * cstr, unsigned int length) [protected]
Definition at line 207 of file spark_wiring_string.cpp.
References buffer, invalidate(), len, and reserve().
Referenced by operator=(), and String().
{
    if (!reserve(length)) {
        invalidate();
        return *this;
    }
    len = length;
    strcpy(buffer, cstr);
    return *this;
}
copy() [2/2]
 String& String::copy (const __FlashStringHelper * pstr, unsigned int length) [protected]
endsWith()
unsigned char String::endsWith (const String & suffix) const
Returns true if this string ends with suffix (case-sensitive)
Parameters
suffix the string containing the suffix to test
Uses the C standard library function strcmp which is case-sensitive and may not work properly with UTF-8 characters.
Definition at line 499 of file spark_wiring_string.cpp.
References buffer, and len.
{
    if (len < s2.len || !buffer || !s2.buffer) return 0;
    return strcmp(&buffer[len - s2.len], s2.buffer) == 0;
}
equals() [1/2]
unsigned char String::equals (const String & s) const
Returns true if this string is equal to another string (case-sensitive)
Parameters
s the string to compare to
Returns
true if the other string is equal to this string.
Uses the C standard library function strcmp which is case-sensitive and does not correctly compare UTF-8 characters.
Definition at line 442 of file spark_wiring_string.cpp.
References compareTo(), and len.
Referenced by operator!=(), and operator==().
{
    return (len == s2.len && compareTo(s2) == 0);
}
equals() [2/2]
unsigned char String::equals (const char * cstr) const
Returns true if this string equal to another string (case-sensitive)
Parameters
cstr the c-string (null-terminated) to compare to
Returns
true if the other string is equal to this string.
Uses the C standard library function strcmp which is case-sensitive and does not correctly compare UTF-8 characters.
Definition at line 447 of file spark_wiring_string.cpp.
References buffer, and len.
Referenced by operator!=(), and operator==().
{
    if (len == 0) return (cstr == NULL || *cstr == 0);
    if (cstr == NULL) return buffer[0] == 0;
    return strcmp(buffer, cstr) == 0;
}
equalsIgnoreCase()
unsigned char String::equalsIgnoreCase (const String & s) const
Returns true if this string equals another string (case-insensitive)
Parameters
s the string to compare to
Returns
true if equal, false if not
Uses the C standard library function strcmp which is case-sensitive and does not correctly compare UTF-8 characters.
Definition at line 474 of file spark_wiring_string.cpp.
References buffer, and len.
{
    if (this == &s2) return 1;
    if (len != s2.len) return 0;
    if (len == 0) return 1;
    const char *p1 = buffer;
    const char *p2 = s2.buffer;
    while (*p1) {
        if (tolower(*p1++) != tolower(*p2++)) return 0;
    }
    return 1;
}
format()
 String String::format (const char * format, ...) [static]
Uses sprintf-style formatting to build a String object [static].
Parameters
format The formatting string
... Variable arguments corresponding to the formatting string
Returns
Returns a String object formatted as specified
Definition at line 787 of file spark_wiring_string.cpp.
References buffer, len, and reserve().
{
    va_list marker;
    va_start(marker, fmt);
    const int bufsize = 5;
    char test[bufsize];
    size_t n = vsnprintf(test, bufsize, fmt, marker);
    va_end(marker);
    String result;
    result.reserve(n); // internally adds +1 for null terminator
    if (result.buffer) {
        va_start(marker, fmt);
        n = vsnprintf(result.buffer, n+1, fmt, marker);
        va_end(marker);
        result.len = n;
    }
    return result;
}
getBytes()
void String::getBytes (unsigned char * buf, unsigned int bufsize, unsigned int index = 0) const
Copy the data out of this String into another buffer.
Parameters
buf The buffer to copy into
bufsize The size of the buffer. The buffer will contain a null-terminted string so the maximum string length is bufsize - 1.
index The index to start copying from (0 = first character). Optional. Default is from 0, the start of the string.
If bufsize is smaller than the string the string will be truncated and still null-terminated. If the string is truncated and UTF-8, it may break a multi-byte character sequence in the middle, resulting in invalid UTF-8.
Definition at line 535 of file spark_wiring_string.cpp.
References buffer, and len.
Referenced by toCharArray().
{
    if (!bufsize || !buf) return;
    if (index >= len) {
        buf[0] = 0;
        return;
    }
    unsigned int n = bufsize - 1;
    if (n > len - index) n = len - index;
    strncpy((char *)buf, buffer + index, n);
    buf[n] = 0;
}
indexOf() [1/4]
int String::indexOf (char ch) const
Search this string for a given character.
Parameters
ch The ASCII character to search for
Returns
index of the character or -1 if not found. 0 = the first character.
This uses the C standard library function strchr and is only compatible with ASCII characters. It can return invalid results for UTF-8 strings.
Definition at line 552 of file spark_wiring_string.cpp.
References indexOf().
{
    return indexOf(c, 0);
}
indexOf() [2/4]
int String::indexOf (char ch, unsigned int fromIndex) const
Search this string for a given character starting at an offset.
Parameters
ch The ASCII character to t search for
fromIndex The index to start from (0 = first character)
Returns
index of the character or -1 if not found. 0 = the first character.
This uses the C standard library function strchr and is only compatible with ASCII characters. It can return invalid results for UTF-8 strings.
Definition at line 557 of file spark_wiring_string.cpp.
References buffer, and len.
Referenced by indexOf().
{
    if (fromIndex >= len) return -1;
    const char* temp = strchr(buffer + fromIndex, ch);
    if (temp == NULL) return -1;
    return temp - buffer;
}
indexOf() [3/4]
int String::indexOf (const String & str) const
Search this string for a given String.
Parameters
str The string to search for
Returns
index of the string or -1 if not found. 0 = the first character.
This uses the C standard library function strstr and is only compatible with ASCII characters. It can return invalid results for UTF-8 strings. It is case-sensitive.
Definition at line 565 of file spark_wiring_string.cpp.
References indexOf().
{
    return indexOf(s2, 0);
}
indexOf() [4/4]
int String::indexOf (const String & str, unsigned int fromIndex) const
Search this string for a given String starting at an offset.
Parameters
str The string to search for
fromIndex The index to start from (0 = first character)
Returns
index of the string or -1 if not found. 0 = the first character.
This uses the C standard library function strstr and is only compatible with ASCII characters. It can return invalid results for UTF-8 strings. It is case-sensitive.
Definition at line 570 of file spark_wiring_string.cpp.
References buffer, and len.
Referenced by indexOf().
{
    if (fromIndex >= len) return -1;
    const char *found = strstr(buffer + fromIndex, s2.buffer);
    if (found == NULL) return -1;
    return found - buffer;
}
init()
void String::init (void) [inline], [protected]
Definition at line 167 of file spark_wiring_string.cpp.
References buffer, capacity, flags, and len.
Referenced by String().
{
    buffer = NULL;
    capacity = 0;
    len = 0;
    flags = 0;
}
invalidate()
void String::invalidate (void) [protected]
Definition at line 175 of file spark_wiring_string.cpp.
References buffer, capacity, and len.
Referenced by copy(), operator+(), and operator=().
{
    if (buffer) free(buffer);
    buffer = NULL;
    capacity = len = 0;
}
lastIndexOf() [1/4]
int String::lastIndexOf (char ch) const
Search this string for a given character, starting at the end.
Parameters
ch The ASCII character to search for
Returns
index of the character or -1 if not found. 0 = the first character.
This uses the C standard library function strrchr and is only compatible with ASCII characters. It can return invalid results for UTF-8 strings.
Definition at line 578 of file spark_wiring_string.cpp.
References lastIndexOf(), and len.
{
    return lastIndexOf(theChar, len - 1);
}
lastIndexOf() [2/4]
int String::lastIndexOf (char ch, unsigned int fromIndex) const
Search this string for a given character, starting at the fromIndex and going toward the beginning.
Parameters
ch The ASCII character to search for
fromIndex The index to start from (0 = first character)
Returns
index of the character or -1 if not found. 0 = the first character.
This uses the C standard library function strrchr and is only compatible with ASCII characters. It can return invalid results for UTF-8 strings.
Definition at line 583 of file spark_wiring_string.cpp.
References buffer, and len.
Referenced by lastIndexOf().
{
    if (fromIndex >= len) return -1;
    char tempchar = buffer[fromIndex + 1];
    buffer[fromIndex + 1] = '\0';
    char* temp = strrchr(buffer, ch);
    buffer[fromIndex + 1] = tempchar;
    if (temp == NULL) return -1;
    return temp - buffer;
}
lastIndexOf() [3/4]
int String::lastIndexOf (const String & str) const
Search this string for a last occurrence of str.
Parameters
str The string to search for
Returns
index of the start of the string or -1 if not found. 0 = the first character.
This uses the C standard library function strstr and is only compatible with ASCII characters. It can return invalid results for UTF-8 strings. It is case-sensitive.
Definition at line 594 of file spark_wiring_string.cpp.
References lastIndexOf(), and len.
{
    return lastIndexOf(s2, len - s2.len);
}
lastIndexOf() [4/4]
int String::lastIndexOf (const String & str, unsigned int fromIndex) const
Search this string for a last occurrence of str starting at fromIndex.
Parameters
str The string to search for
fromIndex The index to start from (0 = first character)
Returns
index of the start of the string or -1 if not found. 0 = the first character.
This uses the C standard library function strstr and is only compatible with ASCII characters. It can return invalid results for UTF-8 strings. It is case-sensitive.
Definition at line 599 of file spark_wiring_string.cpp.
References buffer, and len.
Referenced by lastIndexOf(), and replace().
{
    if (s2.len == 0 || len == 0 || s2.len > len) return -1;
    if (fromIndex >= len) fromIndex = len - 1;
    int found = -1;
    for (char *p = buffer; p <= buffer + fromIndex; p++) {
        p = strstr(p, s2.buffer);
        if (!p) break;
        if ((unsigned int)(p - buffer) <= fromIndex) found = p - buffer;
    }
    return found;
}
length()
unsigned int String::length (void) const [inline]
Returns the length of the string in bytes.
Note that for UTF-8 strings, this is the number of bytes, not characters.
Definition at line 208 of file spark_wiring_string.h.
References len.
Referenced by StringPrintableHelper::write().
{return len;}
operator const char *()
String::operator const char * () const [inline]
Returns the contents this String as a c-string (null-terminated)
See also c_str() which is another way to do this.
Definition at line 241 of file spark_wiring_string.h.
References c_str().
{ return c_str(); }
operator StringIfHelperType()
String::operator StringIfHelperType () const [inline]
Definition at line 536 of file spark_wiring_string.h.
References buffer, and StringIfHelper().
{ return buffer ? &String::StringIfHelper : 0; }
operator"!=() [1/2]
unsigned char String::operator!= (const String & rhs) const [inline]
Returns true if this string is greater than to another string (case-sensitive)
Parameters
rhs the string to compare to
Returns
true if the other string is greater than this string.
Uses the C standard library function strcmp which is case-sensitive and does not correctly compare UTF-8 characters.
Definition at line 610 of file spark_wiring_string.h.
References equals().
{return !equals(rhs);}
operator"!=() [2/2]
unsigned char String::operator!= (const char * cstr) const [inline]
Returns true if this string not equal to another string (case-sensitive)
Parameters
cstr the c-string (null-terminated) to compare to
Returns
true if the other string is not equal to this string.
Uses the C standard library function strcmp which is case-sensitive and does not correctly compare UTF-8 characters.
Definition at line 622 of file spark_wiring_string.h.
References equals().
Referenced by runTest().
{return !equals(cstr);}
operator+=() [1/8]
 String& String::operator+= (const String & rhs) [inline]
Appends (concatenate) a String object to the end of this String, modifying this string in place.
Parameters
rhs The string to copy from. It is not modified.
Returns
This string to you can chain operations together. If there was not enough memory or other error occurs, this String will be left unmodified.
Definition at line 352 of file spark_wiring_string.h.
References concat().
{concat(rhs); return (*this);}
operator+=() [2/8]
 String& String::operator+= (const char * cstr) [inline]
Appends (concatenate) a c-string (null-terminated) to the end of this String, modifying this string in place.
Parameters
cstr The string to copy from. It is not modified.
Returns
This string to you can chain operations together. If there was not enough memory or other error occurs, this String will be left unmodified.
Definition at line 362 of file spark_wiring_string.h.
References concat().
{concat(cstr); return (*this);}
operator+=() [3/8]
 String& String::operator+= (char c) [inline]
Appends (concatenate) a single character to the end of this String, modifying this string in place.
Parameters
c The character to append.
Returns
This string to you can chain operations together. If there was not enough memory or other error occurs, this String will be left unmodified.
Definition at line 372 of file spark_wiring_string.h.
References concat().
{concat(c); return (*this);}
operator+=() [4/8]
 String& String::operator+= (unsigned char num) [inline]
Append (concatenate) the byte value num to the end of this String as a decimal number 0 - 255, modifying this string in place.
Parameters
num The value to append.
Returns
This string to you can chain operations together. If there was not enough memory or other error occurs, this String will be left unmodified.
Definition at line 382 of file spark_wiring_string.h.
References concat().
{concat(num); return (*this);}
operator+=() [5/8]
 String& String::operator+= (int num) [inline]
Append (concatenate) the integer value num to the end of this String as a signed decimal number (base 10), modifying this string in place.
Parameters
num The value to append.
Returns
This string to you can chain operations together. If there was not enough memory or other error occurs, this String will be left unmodified.
Definition at line 392 of file spark_wiring_string.h.
References concat().
{concat(num); return (*this);}
operator+=() [6/8]
 String& String::operator+= (unsigned int num) [inline]
Append (concatenate) the unsigned integer value num to the end of this String as a unsigned decimal number (base 10), modifying this string in place.
Parameters
num The value to append.
Returns
This string to you can chain operations together. If there was not enough memory or other error occurs, this String will be left unmodified.
Definition at line 402 of file spark_wiring_string.h.
References concat().
{concat(num); return (*this);}
operator+=() [7/8]
 String& String::operator+= (long num) [inline]
Append (concatenate) the long integer value num to the end of this String as a signed decimal number (base 10), modifying this string in place.
Parameters
num The value to append.
Returns
This string to you can chain operations together. If there was not enough memory or other error occurs, this String will be left unmodified.
Definition at line 412 of file spark_wiring_string.h.
References concat().
{concat(num); return (*this);}
operator+=() [8/8]
 String& String::operator+= (unsigned long num) [inline]
Append (concatenate) the unsigned long value num to the end of this String as a unsigned decimal number (base 10), modifying this string in place.
Parameters
num The value to append.
Returns
This string to you can chain operations together. If there was not enough memory or other error occurs, this String will be left unmodified.
Definition at line 422 of file spark_wiring_string.h.
References concat().
{concat(num); return (*this);}
operator<()
unsigned char String::operator< (const String & rhs) const
Returns true if this string is less than to another string (case-sensitive)
Parameters
rhs the string to compare to
Returns
true if the other string is less than this string.
Uses the C standard library function strcmp which is case-sensitive and does not correctly compare UTF-8 characters.
Definition at line 454 of file spark_wiring_string.cpp.
References compareTo().
{
    return compareTo(rhs) < 0;
}
operator<=()
unsigned char String::operator<= (const String & rhs) const
Returns true if this string is less than or equal to another string (case-sensitive)
Parameters
rhs the string to compare to
Returns
true if the other string is less than or equal to this string.
Uses the C standard library function strcmp which is case-sensitive and does not correctly compare UTF-8 characters.
Definition at line 464 of file spark_wiring_string.cpp.
References compareTo().
{
    return compareTo(rhs) <= 0;
}
operator=() [1/3]
 String & String::operator= (const String & rhs)
Assigns this string to have a copy of String rhs.
Parameters
rhs The string to copy from.
Definition at line 240 of file spark_wiring_string.cpp.
References buffer, copy(), invalidate(), and len.
Referenced by String().
{
    if (this == &rhs) return *this;
    if (rhs.buffer) copy(rhs.buffer, rhs.len);
    else invalidate();
    return *this;
}
operator=() [2/3]
 String & String::operator= (const char * cstr)
Assigns this string to have a copy of c-string (null-terminated) cstr.
Parameters
cstr The string to copy from.
Definition at line 264 of file spark_wiring_string.cpp.
References copy(), and invalidate().
Referenced by allowUser_callback(), callback(), charToString(), JsonParser::getTokenJsonString(), JsonParser::getTokenValue(), MQTT::initialize(), loop(), MQTT::setBroker(), String(), and substring().
{
    if (cstr) copy(cstr, strlen(cstr));
    else invalidate();
    return *this;
}
operator=() [3/3]
 String& String::operator= (const __FlashStringHelper * pstr)
operator==() [1/2]
unsigned char String::operator== (const String & rhs) const [inline]
Returns true if this string is equal to another string (case-sensitive)
Parameters
rhs the string to compare to
Returns
true if the other string is equal to this string.
Uses the C standard library function strcmp which is case-sensitive and does not correctly compare UTF-8 characters.
Definition at line 585 of file spark_wiring_string.h.
References equals().
{return equals(rhs);}
operator==() [2/2]
unsigned char String::operator== (const char * cstr) const [inline]
Returns true if this string equal to another string (case-sensitive)
Parameters
cstr the c-string (null-terminated) to compare to
Returns
true if the other string is equal to this string.
Uses the C standard library function strcmp which is case-sensitive and does not correctly compare UTF-8 characters.
Definition at line 597 of file spark_wiring_string.h.
References equals().
Referenced by JsonParser::getValueTokenByKey(), main(), and switchTest().
{return equals(cstr);}
operator>()
unsigned char String::operator> (const String & rhs) const
Returns true if this string is greater than to another string (case-sensitive)
Parameters
rhs the string to compare to
Returns
true if the other string is greater than this string.
Uses the C standard library function strcmp which is case-sensitive and does not correctly compare UTF-8 characters.
Definition at line 459 of file spark_wiring_string.cpp.
References compareTo().
{
    return compareTo(rhs) > 0;
}
operator>=()
unsigned char String::operator>= (const String & rhs) const
Returns true if this string is greater than or equal to another string (case-sensitive)
Parameters
rhs the string to compare to
Returns
true if the other string is greater than or equal to this string.
Uses the C standard library function strcmp which is case-sensitive and does not correctly compare UTF-8 characters.
Definition at line 469 of file spark_wiring_string.cpp.
References compareTo().
{
    return compareTo(rhs) >= 0;
}
operator[]() [1/2]
char String::operator[] (unsigned int index) const
Gets the character at offset index.
Parameters
index The index to set (0 = first character)
Returns
The character is 0 if the index is larger than the length of the string.
Definition at line 529 of file spark_wiring_string.cpp.
References buffer, and len.
Referenced by charAt().
{
    if (index >= len || !buffer) return 0;
    return buffer[index];
}
operator[]() [2/2]
char & String::operator[] (unsigned int index)
Set the character at offset index.
Parameters
index The index to set (0 = first character)
Returns
A reference to set.
If index is greater than the length of the string, a dummy reference is returned instead. This allows operation to execute without error, but also discards the change. In other words, you cannot use this to append to the string, only modify an existing character.
Definition at line 519 of file spark_wiring_string.cpp.
References buffer, and len.
{
    static char dummy_writable_char;
    if (index >= len || !buffer) {
        dummy_writable_char = 0;
        return dummy_writable_char;
    }
    return buffer[index];
}
remove() [1/2]
 String & String::remove (unsigned int index)
Removes characters from the String, modifying it in place.
Parameters
index Index to start removing from, inclusive. 0 = first character of the string through the end of the string.
Returns
this String, so you can chain multiple operations
Definition at line 691 of file spark_wiring_string.cpp.
References len, and remove().
                                        {
        int count = len - index;
        return remove(index, count);
}
remove() [2/2]
 String & String::remove (unsigned int index, unsigned int count)
Removes characters from the String, modifying it in place.
Parameters
index Index to start removing from, inclusive. 0 = first character of the string.
count Number of characters to remove. Typically 1 (remove one character) or more. Removes to the end of the string if count is larger than the size of the string.
Returns
this String, so you can chain multiple operations
Definition at line 696 of file spark_wiring_string.cpp.
References buffer, and len.
Referenced by remove().
                                                            {
    if (index >= len) { return *this; }
    if (count <= 0) { return *this; }
    if (index + count > len) { count = len - index; }
    char *writeTo = buffer + index;
    len = len - count;
    strncpy(writeTo, buffer + index + count,len - index);
    buffer[len] = 0;
        return *this;
}
replace() [1/2]
 String & String::replace (char find, char replace)
Replaces every occurrence of a character in the string with another character, modifying it in place.
Parameters
find the character to look for
replace the character to replace it with
Returns
this String, so you can chain multiple operations
Definition at line 638 of file spark_wiring_string.cpp.
References buffer.
{
    if (buffer)
            for (char *p = buffer; *p; p++) {
                    if (*p == find) *p = replace;
            }
        return *this;
}
replace() [2/2]
 String & String::replace (const String & find, const String & replace)
Replaces every occurrence of a String with another String, modifying it in place.
Parameters
find the string to look for (case-sensitive)
replace the string to replace it with
Returns
this String, so you can chain multiple operations
Definition at line 647 of file spark_wiring_string.cpp.
References buffer, capacity, changeBuffer(), lastIndexOf(), and len.
{
    if (len == 0 || find.len == 0) return *this;
    int diff = replace.len - find.len;
    char *readFrom = buffer;
    char *foundAt;
    if (diff == 0) {
        while ((foundAt = strstr(readFrom, find.buffer)) != NULL) {
            memcpy(foundAt, replace.buffer, replace.len);
            readFrom = foundAt + replace.len;
        }
    } else if (diff < 0) {
        char *writeTo = buffer;
        while ((foundAt = strstr(readFrom, find.buffer)) != NULL) {
            unsigned int n = foundAt - readFrom;
            memcpy(writeTo, readFrom, n);
            writeTo += n;
            memcpy(writeTo, replace.buffer, replace.len);
            writeTo += replace.len;
            readFrom = foundAt + find.len;
            len += diff;
        }
        strcpy(writeTo, readFrom);
    } else {
        unsigned int size = len; // compute size needed for result
        while ((foundAt = strstr(readFrom, find.buffer)) != NULL) {
            readFrom = foundAt + find.len;
            size += diff;
        }
        if (size == len) return *this;;
        if (size > capacity && !changeBuffer(size)) return *this; // XXX: tell user!
        int index = len - 1;
        while (index >= 0 && (index = lastIndexOf(find, index)) >= 0) {
            readFrom = buffer + index + find.len;
            memmove(readFrom + diff, readFrom, len - (readFrom - buffer));
            len += diff;
            buffer[len] = 0;
            memcpy(buffer + index, replace.buffer, replace.len);
            index--;
        }
    }
        return *this;
}
reserve()
unsigned char String::reserve (unsigned int size)
Reserves a buffer of size.
This can improve the efficiency if you know approximately how big your string will be. Otherwise, the string is made larger in increments, which is much less efficient.
If, for example you reserve 100 bytes in a new empty string, the length will still be 0 until you append characters to it. It just will be able to append 100 bytes until it has to expand the internal dynamically allocated buffer.
Definition at line 182 of file spark_wiring_string.cpp.
References buffer, capacity, changeBuffer(), and len.
Referenced by concat(), copy(), format(), JsonParser::getTokenJsonString(), JsonParser::getTokenValue(), and StringPrintableHelper::StringPrintableHelper().
{
    if (buffer && capacity >= size) return 1;
    if (changeBuffer(size)) {
        if (len == 0) buffer[0] = 0;
        return 1;
    }
    return 0;
}
setCharAt()
void String::setCharAt (unsigned int index, char c)
Set the character at offset index.
Parameters
index The index to set (0 = first character)
c The value to set the character to.
If index is greater than the length of the string, nothing is done. In other words, you cannot use this to append to the string, only modify an existing character.
Definition at line 514 of file spark_wiring_string.cpp.
References buffer, and len.
{
    if (loc < len) buffer[loc] = c;
}
startsWith() [1/2]
unsigned char String::startsWith (const String & prefix) const
Returns true if this string starts with prefix (case-sensitive)
Parameters
prefix the string containing the string to test against
Uses the C standard library function strcmp which is case-sensitive and may not work properly with UTF-8 characters.
Definition at line 487 of file spark_wiring_string.cpp.
References len, and startsWith().
{
    if (len < s2.len) return 0;
    return startsWith(s2, 0);
}
startsWith() [2/2]
unsigned char String::startsWith (const String & prefix, unsigned int offset) const
Returns true if this string contains prefix at specified offset (case-sensitive)
Parameters
prefix the string containing the string to test against
offset the offset to check at (0 = first characters)
Uses the C standard library function strcmp which is case-sensitive and may not work properly with UTF-8 characters.
Definition at line 493 of file spark_wiring_string.cpp.
References buffer, and len.
Referenced by startsWith().
{
    if (offset > len - s2.len || !buffer || !s2.buffer) return 0;
    return strncmp(&buffer[offset], s2.buffer, s2.len) == 0;
}
StringIfHelper()
void String::StringIfHelper () const [inline], [private]
Definition at line 60 of file spark_wiring_string.h.
Referenced by operator StringIfHelperType().
{}
substring() [1/2]
 String String::substring (unsigned int beginIndex) const
Returns a String object with a copy of the characters starting at beginIndex through the end of the string.
Parameters
beginIndex The index to start copying from, inclusive (0 = first byte, 1 = second byte, ...)
Returns
A copy of the specified substring
Note: If the String contains UTF-8 characters, beginIndex and endIndex are in bytes, not characters! It does not prevent splitting a UTF-8 multi-byte sequence.
Definition at line 612 of file spark_wiring_string.cpp.
References len, and substring().
Referenced by readRFIDCard().
{
    return substring(left, len);
}
substring() [2/2]
 String String::substring (unsigned int beginIndex, unsigned int endIndex) const
Returns a String object with a copy of the characters in the specified range.
Parameters
beginIndex The index to start copying from, inclusive (0 = first byte, 1 = second byte, ...)
endIndex The index to stop at, exclusive. The last character copied is the one before this one.
Returns
A copy of the specified substring
Note: If the String contains UTF-8 characters, beginIndex and endIndex are in bytes, not characters! It does not prevent splitting a UTF-8 multi-byte sequence.
Definition at line 617 of file spark_wiring_string.cpp.
References buffer, len, and operator=().
Referenced by substring().
{
    if (left > right) {
        unsigned int temp = right;
        right = left;
        left = temp;
    }
    String out;
    if (left > len) return out;
    if (right > len) right = len;
    char temp = buffer[right]; // save the replaced character
    buffer[right] = '\0';
    out = buffer + left; // pointer arithmetic
    buffer[right] = temp; //restore character
    return out;
}
toCharArray()
void String::toCharArray (char * buf, unsigned int bufsize, unsigned int index = 0) const [inline]
Copy the data out of this String into another buffer.
Parameters
buf The buffer to copy into
bufsize The size of the buffer. The buffer will contain a null-terminted string so the maximum string length is bufsize - 1.
index The index to start copying from (0 = first character). Optional. Default is from 0, the start of the string.
If bufsize is smaller than the string the string will be truncated and still null-terminated. If the string is truncated and UTF-8, it may break a multi-byte character sequence in the middle, resulting in invalid UTF-8.
Definition at line 792 of file spark_wiring_string.h.
References getBytes().
        {getBytes((unsigned char *)buf, bufsize, index);}
toFloat()
float String::toFloat (void) const
Converts this string to a float (single precision floating point value)
Returns
a float value or 0.0 if a parsing error occurs (not a float).
Definition at line 751 of file spark_wiring_string.cpp.
References buffer.
{
    if (buffer) return float(atof(buffer));
    return 0;
}
toInt()
long String::toInt (void) const
Converts this string to a signed integer (32-bit)
Returns
An integer value or 0 if a parsing error occurs (not an integer).
Definition at line 744 of file spark_wiring_string.cpp.
References buffer.
Referenced by maxCurrentC1(), and maxCurrentC2().
{
    if (buffer) return atol(buffer);
    return 0;
}
toLowerCase()
 String & String::toLowerCase (void)
Converts this String to lower case, modifying it in place.
Returns
this String, so you can chain multiple operations
This is done using the C standard library function tolower() on each character. It only works with 7-bit ASCII characters and will corrupt UTF-8 data.
Definition at line 707 of file spark_wiring_string.cpp.
References buffer.
{
    if (buffer) {
            for (char *p = buffer; *p; p++) {
                    *p = tolower(*p);
            }
        }
        return *this;
}
toUpperCase()
 String & String::toUpperCase (void)
Converts this String to upper case, modifying it in place.
Returns
this String, so you can chain multiple operations
This is done using the C standard library function toupper() on each character. It only works with 7-bit ASCII characters and will corrupt UTF-8 data.
Definition at line 717 of file spark_wiring_string.cpp.
References buffer.
{
    if (buffer) {
            for (char *p = buffer; *p; p++) {
                    *p = toupper(*p);
            }
        }
        return *this;
}
trim()
 String & String::trim (void)
Removes leading an trailing white spaces from this string, modifying it in place.
Returns
this String, so you can chain multiple operations
Whitespace is determined by the C standard library function isspace().
Definition at line 727 of file spark_wiring_string.cpp.
References buffer, and len.
{
    if (!buffer || len == 0) return *this;
    char *begin = buffer;
    while (isspace(*begin)) begin++;
    char *end = buffer + len - 1;
    while (isspace(*end) && end >= begin) end--;
    len = end + 1 - begin;
    if (begin > buffer) memcpy(buffer, begin, len);
    buffer[len] = 0;
        return *this;
}
Friends And Related Function Documentation
operator+ [1/10]
 StringSumHelper& operator+ (const StringSumHelper & lhs, const String & rhs) [friend]
Append (concatenate) a String to the end of lhs.
Parameters
lhs The string to append to. String lhs is not modified.
rhs The value to append.
Returns
the combined string
Definition at line 359 of file spark_wiring_string.cpp.
{
    StringSumHelper &a = const_cast<StringSumHelper&>(lhs);
    if (!a.concat(rhs.buffer, rhs.len)) a.invalidate();
    return a;
}
operator+ [2/10]
 StringSumHelper& operator+ (const StringSumHelper & lhs, const char * cstr) [friend]
Append (concatenate) a c-string (null-terminated) to the end of lhs.
Parameters
lhs The string to append to. String lhs is not modified.
cstr The value to append.
Returns
the combined string
Definition at line 366 of file spark_wiring_string.cpp.
{
    StringSumHelper &a = const_cast<StringSumHelper&>(lhs);
    if (!cstr || !a.concat(cstr, strlen(cstr))) a.invalidate();
    return a;
}
operator+ [3/10]
 StringSumHelper& operator+ (const StringSumHelper & lhs, char c) [friend]
Append (concatenate) the character c the end of lhs a.
Parameters
lhs The string to append to. String lhs is not modified.
c The character to append
Returns
the combined string
Definition at line 373 of file spark_wiring_string.cpp.
{
    StringSumHelper &a = const_cast<StringSumHelper&>(lhs);
    if (!a.concat(c)) a.invalidate();
    return a;
}
operator+ [4/10]
 StringSumHelper& operator+ (const StringSumHelper & lhs, unsigned char num) [friend]
Append (concatenate) the unsigned char num to the end of lhs as a decimal number (base 10)
Parameters
lhs The string to append to. String lhs is not modified.
num The value to append.
Returns
the combined string
Definition at line 380 of file spark_wiring_string.cpp.
{
    StringSumHelper &a = const_cast<StringSumHelper&>(lhs);
    if (!a.concat(num)) a.invalidate();
    return a;
}
operator+ [5/10]
 StringSumHelper& operator+ (const StringSumHelper & lhs, int num) [friend]
Append (concatenate) the signed int num to the end of lhs as a decimal number (base 10)
Parameters
lhs The string to append to. String lhs is not modified.
num The value to append.
Returns
the combined string
Definition at line 387 of file spark_wiring_string.cpp.
{
    StringSumHelper &a = const_cast<StringSumHelper&>(lhs);
    if (!a.concat(num)) a.invalidate();
    return a;
}
operator+ [6/10]
 StringSumHelper& operator+ (const StringSumHelper & lhs, unsigned int num) [friend]
Append (concatenate) the unsigned int num to the end of lhs as a decimal number (base 10)
Parameters
lhs The string to append to. String lhs is not modified.
num The value to append.
Returns
the combined string
Definition at line 394 of file spark_wiring_string.cpp.
{
    StringSumHelper &a = const_cast<StringSumHelper&>(lhs);
    if (!a.concat(num)) a.invalidate();
    return a;
}
operator+ [7/10]
 StringSumHelper& operator+ (const StringSumHelper & lhs, long num) [friend]
Append (concatenate) the long integer num to the end of lhs as a decimal number (base 10)
Parameters
lhs The string to append to. String lhs is not modified.
num The value to append.
Returns
the combined string
Definition at line 401 of file spark_wiring_string.cpp.
{
    StringSumHelper &a = const_cast<StringSumHelper&>(lhs);
    if (!a.concat(num)) a.invalidate();
    return a;
}
operator+ [8/10]
 StringSumHelper& operator+ (const StringSumHelper & lhs, unsigned long num) [friend]
Append (concatenate) the unsigned long integer to the end of lhs as a decimal number (base 10)
Parameters
lhs The string to append to. String lhs is not modified.
num The value to append.
Returns
the combined string
Definition at line 408 of file spark_wiring_string.cpp.
{
    StringSumHelper &a = const_cast<StringSumHelper&>(lhs);
    if (!a.concat(num)) a.invalidate();
    return a;
}
operator+ [9/10]
 StringSumHelper& operator+ (const StringSumHelper & lhs, float num) [friend]
Append (concatenate) the float num to the end of lhs as a decimal number (base 10)
Parameters
lhs The string to append to. String lhs is not modified.
num The value to append.
Returns
the combined string
Definition at line 415 of file spark_wiring_string.cpp.
{
    StringSumHelper &a = const_cast<StringSumHelper&>(lhs);
    if (!a.concat(num)) a.invalidate();
    return a;
}
operator+ [10/10]
 StringSumHelper& operator+ (const StringSumHelper & lhs, double num) [friend]
Append (concatenate) the double precision float num to the end of lhs as a decimal number (base 10)
Parameters
lhs The string to append to. String lhs is not modified.
num The value to append.
Returns
the combined string
Definition at line 422 of file spark_wiring_string.cpp.
{
    StringSumHelper &a = const_cast<StringSumHelper&>(lhs);
    if (!a.concat(num)) a.invalidate();
    return a;
}
StringPrintableHelper
friend class StringPrintableHelper [friend]
Definition at line 1078 of file spark_wiring_string.h.
Member Data Documentation
buffer
char* String::buffer [protected]
The buffer containing the data. It is always null-terminated.
Definition at line 1058 of file spark_wiring_string.h.
Referenced by c_str(), changeBuffer(), compareTo(), concat(), copy(), endsWith(), equals(), equalsIgnoreCase(), format(), getBytes(), indexOf(), init(), invalidate(), lastIndexOf(), operator StringIfHelperType(), operator+(), operator=(), operator[](), remove(), replace(), reserve(), setCharAt(), startsWith(), substring(), toFloat(), toInt(), toLowerCase(), toUpperCase(), trim(), and ~String().
capacity
unsigned int String::capacity [protected]
The capacity of the buffer. The longest string is one byte less than this.
Definition at line 1059 of file spark_wiring_string.h.
Referenced by changeBuffer(), init(), invalidate(), replace(), and reserve().
flags
unsigned char String::flags [protected]
Unused, for future features.
Definition at line 1061 of file spark_wiring_string.h.
Referenced by init().
len
unsigned int String::len [protected]
The String length (not counting the null terminator).
Definition at line 1060 of file spark_wiring_string.h.
Referenced by compareTo(), concat(), copy(), endsWith(), equals(), equalsIgnoreCase(), format(), getBytes(), indexOf(), init(), invalidate(), lastIndexOf(), length(), operator+(), operator=(), operator[](), remove(), replace(), reserve(), setCharAt(), startsWith(), substring(), and trim().
The documentation for this class was generated from the following files:
lib/JsonParserGeneratorRK/docs/src/ spark_wiring_string.h
lib/JsonParserGeneratorRK/test/gcclib/ spark_wiring_string.cpp