StringPrintableHelper Class Reference
Public Member Functions
 StringPrintableHelper (String &s_)
virtual size_t write (const uint8_t *buffer, size_t size) override
virtual size_t write (uint8_t c) override
Private Attributes
 String & s
Additional Inherited Members
Detailed Description
Definition at line 757 of file spark_wiring_string.cpp.
Constructor & Destructor Documentation
StringPrintableHelper()
StringPrintableHelper::StringPrintableHelper (String & s_) [inline]
Definition at line 763 of file spark_wiring_string.cpp.
References String::reserve(), and s.
Referenced by String::String().
                                      : s(s_) {
        s.reserve(20);
    }
Member Function Documentation
write() [1/2]
virtual size_t StringPrintableHelper::write (const uint8_t * buffer, size_t size) [inline], [override], [virtual]
Reimplemented from Print .
Definition at line 767 of file spark_wiring_string.cpp.
References String::concat(), String::length(), and s.
    {
        unsigned len = s.length();
        s.concat((const char*)buffer, size);
        return s.length()-len;
    }
write() [2/2]
virtual size_t StringPrintableHelper::write (uint8_t c) [inline], [override], [virtual]
Implements Print .
Definition at line 774 of file spark_wiring_string.cpp.
References String::concat(), and s.
    {
        return s.concat((char)c);
    }
Member Data Documentation
s
 String& StringPrintableHelper::s [private]
Definition at line 759 of file spark_wiring_string.cpp.
Referenced by StringPrintableHelper(), and write().
The documentation for this class was generated from the following file:
lib/JsonParserGeneratorRK/test/gcclib/ spark_wiring_string.cpp