JsonWriterAutoObject Class Reference
Class for creating a JSON object with JsonWriter.
#include <JsonParserGeneratorRK.h>
Public Member Functions
 JsonWriterAutoObject (JsonWriter * jw)
Start a new object.
 ~JsonWriterAutoObject ()
End the object.
Protected Attributes
 JsonWriter * jw
JsonWriter to write to.
Detailed Description
Class for creating a JSON object with JsonWriter.
When you create an object, you must call startObject() to start and finishObjectOrArray() to complete it.
This class is instantiated on the stack to automatically start and finish for you.
Definition at line 1256 of file JsonParserGeneratorRK.h.
Constructor & Destructor Documentation
JsonWriterAutoObject()
JsonWriterAutoObject::JsonWriterAutoObject (JsonWriter * jw) [inline]
Start a new object.
Parameters
jw The JsonWriter object to insert the object into
Definition at line 1263 of file JsonParserGeneratorRK.h.
References jw, and JsonWriter::startObject().
Referenced by runTest().
                                         : jw(jw) {
        jw->startObject();
    }
~JsonWriterAutoObject()
JsonWriterAutoObject::~JsonWriterAutoObject () [inline]
End the object.
Definition at line 1270 of file JsonParserGeneratorRK.h.
References JsonWriter::finishObjectOrArray(), and jw.
                            {
        jw->finishObjectOrArray();
    }
Member Data Documentation
jw
 JsonWriter* JsonWriterAutoObject::jw [protected]
JsonWriter to write to.
Definition at line 1275 of file JsonParserGeneratorRK.h.
Referenced by JsonWriterAutoObject(), and ~JsonWriterAutoObject().
The documentation for this class was generated from the following file:
lib/JsonParserGeneratorRK/src/ JsonParserGeneratorRK.h