MQTT Class Reference
#include <MQTT.h>
Public Types
enum EMQTT_QOS { QOS0 = 0,
 QOS1 = 1,
 QOS2 = 2
 }
enum MQTT_VERSION { MQTT_V31 = 3,
 MQTT_V311 = 4
 }
enum EMQTT_CONNACK_RESPONSE {
 CONN_ACCEPT = 0,
 CONN_UNACCEPTABLE_PROCOTOL = 1,
 CONN_ID_REJECT = 2,
 CONN_SERVER_UNAVAILALE = 3,
 CONN_BAD_USER_PASSWORD = 4,
 CONN_NOT_AUTHORIZED = 5
 }
Public Member Functions
 MQTT ()
 MQTT (char * domain, uint16_t port, void(* callback)(char *, uint8_t *, unsigned int))
 MQTT (char * domain, uint16_t port, void(* callback)(char *, uint8_t *, unsigned int), int maxpacketsize)
 MQTT (uint8_t * ip, uint16_t port, void(* callback)(char *, uint8_t *, unsigned int))
 MQTT (uint8_t * ip, uint16_t port, void(* callback)(char *, uint8_t *, unsigned int), int maxpacketsize)
 MQTT (char * domain, uint16_t port, int keepalive, void(* callback)(char *, uint8_t *, unsigned int))
 MQTT (char * domain, uint16_t port, int keepalive, void(* callback)(char *, uint8_t *, unsigned int), int maxpacketsize)
 MQTT (uint8_t * ip, uint16_t port, int keepalive, void(* callback)(char *, uint8_t *, unsigned int))
 MQTT (uint8_t * ip, uint16_t port, int keepalive, void(* callback)(char *, uint8_t *, unsigned int), int maxpacketsize)
 ~MQTT ()
void setBroker (char * domain, uint16_t port)
void setBroker (uint8_t * ip, uint16_t port)
bool connect (const char *id)
bool connect (const char *id, const char *user, const char *pass)
bool connect (const char *id, const char *user, const char *pass, const char *willTopic, EMQTT_QOS willQos, uint8_t willRetain, const char *willMessage, bool cleanSession, MQTT_VERSION version= MQTT_V311)
void disconnect ()
void clear ()
bool publish (const char *topic, const char *payload)
bool publish (const char *topic, const char *payload, bool retain)
bool publish (const char *topic, const char *payload, EMQTT_QOS qos, uint16_t *messageid=NULL)
bool publish (const char *topic, const char *payload, EMQTT_QOS qos, bool dup, uint16_t *messageid=NULL)
bool publish (const char *topic, const uint8_t *pyaload, unsigned int plength)
bool publish (const char *topic, const uint8_t *payload, unsigned int plength, EMQTT_QOS qos, uint16_t *messageid=NULL)
bool publish (const char *topic, const uint8_t *payload, unsigned int plength, EMQTT_QOS qos, bool dup, uint16_t *messageid=NULL)
bool publish (const char *topic, const uint8_t *payload, unsigned int plength, bool retain)
bool publish (const char *topic, const uint8_t *payload, unsigned int plength, bool retain, EMQTT_QOS qos, uint16_t *messageid=NULL)
bool publish (const char *topic, const uint8_t *payload, unsigned int plength, bool retain, EMQTT_QOS qos, bool dup, uint16_t *messageid)
void addQosCallback (void(* qoscallback)(unsigned int))
bool subscribe (const char *topic)
bool subscribe (const char *topic, EMQTT_QOS)
bool unsubscribe (const char *topic)
bool loop ()
bool isConnected ()
Private Member Functions
uint16_t readPacket (uint8_t *)
uint8_t readByte ()
bool write (uint8_t header, uint8_t *buf, uint16_t length)
uint16_t writeString (const char *string, uint8_t *buf, uint16_t pos)
void initialize (char * domain, uint8_t * ip, uint16_t port, int keepalive, void(* callback)(char *, uint8_t *, unsigned int), int maxpacketsize)
bool publishRelease (uint16_t messageid)
bool publishComplete (uint16_t messageid)
Private Attributes
TCPClient _client
uint8_t * buffer = NULL
uint16_t nextMsgId
unsigned long lastOutActivity
unsigned long lastInActivity
bool pingOutstanding
void(* callback)(char *, uint8_t *, unsigned int)
void(* qoscallback)(unsigned int)
 String domain
uint8_t * ip = NULL
uint16_t port
int keepalive
uint16_t maxpacketsize
Detailed Description
Definition at line 105 of file MQTT.h.
Member Enumeration Documentation
EMQTT_CONNACK_RESPONSE
enum MQTT::EMQTT_CONNACK_RESPONSE
Enumerator
CONN_ACCEPT
CONN_UNACCEPTABLE_PROCOTOL
CONN_ID_REJECT
CONN_SERVER_UNAVAILALE
CONN_BAD_USER_PASSWORD
CONN_NOT_AUTHORIZED
Definition at line 119 of file MQTT.h.
             {
    CONN_ACCEPT = 0,
    CONN_UNACCEPTABLE_PROCOTOL = 1,
    CONN_ID_REJECT = 2,
    CONN_SERVER_UNAVAILALE = 3,
    CONN_BAD_USER_PASSWORD = 4,
    CONN_NOT_AUTHORIZED = 5
} EMQTT_CONNACK_RESPONSE;
EMQTT_QOS
enum MQTT::EMQTT_QOS
types
Enumerator
QOS0
QOS1
QOS2
Definition at line 108 of file MQTT.h.
             {
    QOS0 = 0,
    QOS1 = 1,
    QOS2 = 2,
} EMQTT_QOS;
MQTT_VERSION
enum MQTT::MQTT_VERSION
Enumerator
MQTT_V31
MQTT_V311
Definition at line 114 of file MQTT.h.
            {
    MQTT_V31 = 3,
    MQTT_V311 = 4
} MQTT_VERSION;
Constructor & Destructor Documentation
MQTT() [1/9]
MQTT::MQTT () [inline]
Definition at line 152 of file MQTT.h.
{};
MQTT() [2/9]
MQTT::MQTT (char * domain, uint16_t port, void(*)(char *, uint8_t *, unsigned int) callback)
Definition at line 12 of file MQTT.cpp.
References initialize().
                                                                                     {
    this->initialize(domain, NULL, port, MQTT_DEFAULT_KEEPALIVE, callback,
      MQTT_MAX_PACKET_SIZE);
}
MQTT() [3/9]
MQTT::MQTT (char * domain, uint16_t port, void(*)(char *, uint8_t *, unsigned int) callback, int maxpacketsize)
Definition at line 16 of file MQTT.cpp.
References initialize().
                                                                                                        {
    this->initialize(domain, NULL, port, MQTT_DEFAULT_KEEPALIVE, callback,
      maxpacketsize);
}
MQTT() [4/9]
MQTT::MQTT (uint8_t * ip, uint16_t port, void(*)(char *, uint8_t *, unsigned int) callback)
Definition at line 20 of file MQTT.cpp.
References initialize().
                                                                                    {
    this->initialize(NULL, ip, port, MQTT_DEFAULT_KEEPALIVE, callback,
      MQTT_MAX_PACKET_SIZE);
}
MQTT() [5/9]
MQTT::MQTT (uint8_t * ip, uint16_t port, void(*)(char *, uint8_t *, unsigned int) callback, int maxpacketsize)
Definition at line 24 of file MQTT.cpp.
References initialize().
                                                                                                       {
    this->initialize(NULL, ip, port, MQTT_DEFAULT_KEEPALIVE, callback,
      maxpacketsize);
}
MQTT() [6/9]
MQTT::MQTT (char * domain, uint16_t port, int keepalive, void(*)(char *, uint8_t *, unsigned int) callback)
Definition at line 28 of file MQTT.cpp.
References initialize().
                                                                                                    {
    this->initialize(domain, NULL, port, keepalive, callback,
      MQTT_MAX_PACKET_SIZE);
}
MQTT() [7/9]
MQTT::MQTT (char * domain, uint16_t port, int keepalive, void(*)(char *, uint8_t *, unsigned int) callback, int maxpacketsize)
Definition at line 32 of file MQTT.cpp.
References initialize().
                                                                                                           
                  {
    this->initialize(domain, NULL, port, keepalive, callback, maxpacketsize);
}
MQTT() [8/9]
MQTT::MQTT (uint8_t * ip, uint16_t port, int keepalive, void(*)(char *, uint8_t *, unsigned int) callback)
Definition at line 36 of file MQTT.cpp.
References initialize().
                                                                                                   {
    this->initialize(NULL, ip, port, keepalive, callback, MQTT_MAX_PACKET_SIZE);
}
MQTT() [9/9]
MQTT::MQTT (uint8_t * ip, uint16_t port, int keepalive, void(*)(char *, uint8_t *, unsigned int) callback, int maxpacketsize)
Definition at line 40 of file MQTT.cpp.
References initialize().
                                                                                                           
                 {
    this->initialize(NULL, ip, port, keepalive, callback, maxpacketsize);
}
~MQTT()
MQTT::~MQTT ()
Definition at line 44 of file MQTT.cpp.
References buffer, disconnect(), and isConnected().
            {
    if (isConnected()) {
        disconnect();
    }
    if (buffer != NULL)
      delete[] buffer;
}
Member Function Documentation
addQosCallback()
void MQTT::addQosCallback (void(*)(unsigned int) qoscallback)
Definition at line 89 of file MQTT.cpp.
References qoscallback.
                                                           {
    this->qoscallback = qoscallback;
}
clear()
void MQTT::clear ()
Definition at line 534 of file MQTT.cpp.
                 {
  _client.stop();
  lastInActivity = lastOutActivity = millis();
}
connect() [1/3]
bool MQTT::connect (const char * id)
Definition at line 94 of file MQTT.cpp.
References connect(), and QOS0.
                                 {
    return connect(id, NULL, NULL, 0, QOS0, 0, 0, true);
}
connect() [2/3]
bool MQTT::connect (const char * id, const char * user, const char * pass)
Definition at line 98 of file MQTT.cpp.
References connect(), and QOS0.
                                                                     {
    return connect(id, user, pass, 0, QOS0, 0, 0, true);
}
connect() [3/3]
bool MQTT::connect (const char * id, const char * user, const char * pass, const char * willTopic, EMQTT_QOS willQos, uint8_t willRetain, const char * willMessage, bool cleanSession, MQTT_VERSION version = MQTT_V311)
Definition at line 102 of file MQTT.cpp.
References buffer, CONN_ACCEPT, isConnected(), keepalive, MQTT_V31, MQTT_V311, nextMsgId, pingOutstanding, readPacket(), write(), and writeString().
Referenced by connect().
                                                                                                           
                                                                                                {
    if (!isConnected()) {
        int result = 0;
        if (ip == NULL)
            result = _client.connect(this->domain.c_str(), this->port);
        else
            result = _client.connect(this->ip, this->port);
        if (result) {
            nextMsgId = 1;
            uint16_t length = 5;
            if (version == MQTT_V311) {
                const uint8_t MQTT_HEADER_V311[] = {0x00,0x04,'M','Q','T','T',
      MQTT_V311};
                memcpy(buffer + length, MQTT_HEADER_V311, sizeof(MQTT_HEADER_V311));
                length+=sizeof(MQTT_HEADER_V311);
            } else {
                const uint8_t MQTT_HEADER_V31[] = {0x00,0x06,'M','Q','I','s','d','p',
      MQTT_V31};
                memcpy(buffer + length, MQTT_HEADER_V31, sizeof(MQTT_HEADER_V31));
                length+=sizeof(MQTT_HEADER_V31);
            }
            uint8_t v = 0;
            if (willTopic) {
                v = 0x06|(willQos<<3)|(willRetain<<5);
            } else {
                v = 0x02;
            }
            if (!cleanSession) {
              v = v&0xfd;
            }
            if(user != NULL) {
                v = v|0x80;
                if(pass != NULL) {
                    v = v|(0x80>>1);
                }
            }
            buffer[length++] = v;
            buffer[length++] = ((this->keepalive) >> 8);
            buffer[length++] = ((this->keepalive) & 0xFF);
            length = writeString(id, buffer, length);
            if (willTopic) {
                length = writeString(willTopic, buffer, length);
                length = writeString(willMessage, buffer, length);
            }
            if(user != NULL) {
                length = writeString(user,buffer,length);
                if(pass != NULL) {
                    length = writeString(pass,buffer,length);
                }
            }
            write(MQTTCONNECT, buffer, length-5);
            lastInActivity = lastOutActivity = millis();
            while (!_client.available()) {
                unsigned long t = millis();
                if (t-lastInActivity > this->keepalive*1000UL) {
                    _client.stop();
                    return false;
                }
            }
            uint8_t llen;
            uint16_t len = readPacket(&llen);
            if (len == 4) {
                if (buffer[3] == CONN_ACCEPT) {
                    lastInActivity = millis();
                    pingOutstanding = false;
                    debug_print(" Connect success\n");
                    return true;
                } else {
                    // check EMQTT_CONNACK_RESPONSE code.
                    debug_print(" Connect fail. code = [%d]\n", buffer[3]);
                }
            }
        }
        _client.stop();
    }
    return false;
}
disconnect()
void MQTT::disconnect ()
Definition at line 506 of file MQTT.cpp.
References buffer.
Referenced by setBroker(), and ~MQTT().
                      {
    buffer[0] = MQTTDISCONNECT;
    buffer[1] = 0;
    _client.write(buffer,2);
    _client.stop();
    lastInActivity = lastOutActivity = millis();
}
initialize()
void MQTT::initialize (char * domain, uint8_t * ip, uint16_t port, int keepalive, void(*)(char *, uint8_t *, unsigned int) callback, int maxpacketsize) [private]
Definition at line 53 of file MQTT.cpp.
References buffer, callback, domain, ip, keepalive, maxpacketsize, String::operator=(), port, and qoscallback.
Referenced by MQTT().
                                                                                                           
                                          {
    this->callback = callback;
    this->qoscallback = NULL;
    if (ip != NULL)
        this->ip = ip;
    if (domain != NULL)
        this->domain = domain;
    this->port = port;
    this->keepalive = keepalive;
    // if maxpacketsize is over MQTT_MAX_PACKET_SIZE.
    this->maxpacketsize = (maxpacketsize <= MQTT_MAX_PACKET_SIZE ?
      MQTT_MAX_PACKET_SIZE : maxpacketsize);
    if (buffer != NULL)
      delete[] buffer;
    buffer = new uint8_t[this->maxpacketsize];
}
isConnected()
bool MQTT::isConnected ()
Definition at line 528 of file MQTT.cpp.
Referenced by connect(), loop(), publish(), publishComplete(), publishRelease(), setBroker(), subscribe(), unsubscribe(), and ~MQTT().
                       {
    bool rc = (int)_client.connected();
    if (!rc) _client.stop();
    return rc;
}
loop()
bool MQTT::loop ()
Definition at line 240 of file MQTT.cpp.
References buffer, callback, isConnected(), keepalive, lastInActivity, lastOutActivity, pingOutstanding, publishComplete(), publishRelease(), qoscallback, and readPacket().
                {
    if (isConnected()) {
        unsigned long t = millis();
        if ((t - lastInActivity > this->keepalive*1000UL) || (t -
      lastOutActivity > this->keepalive*1000UL)) {
            if (pingOutstanding) {
                _client.stop();
                return false;
            } else {
                buffer[0] = MQTTPINGREQ;
                buffer[1] = 0;
                _client.write(buffer,2);
                lastOutActivity = t;
                lastInActivity = t;
                pingOutstanding = true;
            }
        }
        if (_client.available()) {
            uint8_t llen;
            uint16_t len = readPacket(&llen);
            uint16_t msgId = 0;
            uint8_t *payload;
            if (len > 0) {
                lastInActivity = t;
                uint8_t type = buffer[0]&0xF0;
                if (type == MQTTPUBLISH) {
                    if (callback) {
                        uint16_t tl = (buffer[llen+1]<<8)+buffer[llen+2]; // topic length
                        char topic[tl+1];
                        for (uint16_t i=0;i<tl;i++) {
                            topic[i] = buffer[llen+3+i];
                        }
                        topic[tl] = 0;
                        // msgId only present for QOS>0
                        if ((buffer[0]&0x06) == MQTTQOS1_HEADER_MASK) { // QoS=1
                            msgId = (buffer[llen+3+tl]<<8)+buffer[llen+3+tl+1];
                            payload = buffer+llen+3+tl+2;
                            callback(topic,payload,len-llen-3-tl-2);
                            buffer[0] = MQTTPUBACK; // respond with PUBACK
                            buffer[1] = 2;
                            buffer[2] = (msgId >> 8);
                            buffer[3] = (msgId & 0xFF);
                            _client.write(buffer,4);
                            lastOutActivity = t;
                                    } else if ((buffer[0] & 0x06) ==
      MQTTQOS2_HEADER_MASK) { // QoS=2
                                          msgId = (buffer[llen + 3 + tl] << 8) +
      buffer[llen + 3 + tl + 1];
                                          payload = buffer + llen + 3 + tl + 2;
                                          callback(topic, payload, len - llen - 3 - tl - 2);
                                        buffer[0] = MQTTPUBREC; // respond with PUBREC
                                        buffer[1] = 2;
                                        buffer[2] = (msgId >> 8);
                                        buffer[3] = (msgId & 0xFF);
                                        _client.write(buffer, 4);
                                        lastOutActivity = t;
                                    } else {
                            payload = buffer+llen+3+tl;
                            callback(topic,payload,len-llen-3-tl);
                        }
                    }
                } else if (type == MQTTPUBREC) {
                    // check for the situation that QoS2 receive PUBREC, should return PUBREL
                    msgId = (buffer[2] << 8) + buffer[3];
                    this->publishRelease(msgId);
                } else if (type == MQTTPUBACK) {
                    if (qoscallback) {
                        // this case QOS==1
                        if (len == 4 && (buffer[0]&0x06) == MQTTQOS0_HEADER_MASK) {
                            msgId = (buffer[2]<<8)+buffer[3];
                            this->qoscallback(msgId);
                        }
                    }
                } else if (type == MQTTPUBREL) {
                  msgId = (buffer[2] << 8) + buffer[3];
                  this->publishComplete(msgId);
                } else if (type == MQTTPUBCOMP) {
                  if (qoscallback) {
                      // msgId only present for QOS==0
                      if (len == 4 && (buffer[0]&0x06) == MQTTQOS0_HEADER_MASK) {
                          msgId = (buffer[2]<<8)+buffer[3];
                          this->qoscallback(msgId);
                      }
                  }
                } else if (type == MQTTSUBACK) {
                    // if something...
                } else if (type == MQTTPINGREQ) {
                    buffer[0] = MQTTPINGRESP;
                    buffer[1] = 0;
                    _client.write(buffer,2);
                } else if (type == MQTTPINGRESP) {
                    pingOutstanding = false;
                }
            }
        }
        return true;
    }
    return false;
}
publish() [1/10]
bool MQTT::publish (const char * topic, const char * payload)
Definition at line 339 of file MQTT.cpp.
References publish(), and QOS0.
                                                         {
    return publish(topic, (uint8_t*)payload, strlen(payload), false, QOS0, NULL);
}
publish() [2/10]
bool MQTT::publish (const char * topic, const char * payload, bool retain)
Definition at line 343 of file MQTT.cpp.
References publish(), and QOS0.
                                                                      {
    return publish(topic, (uint8_t*)payload, strlen(payload), retain, QOS0, NULL);
}
publish() [3/10]
bool MQTT::publish (const char * topic, const char * payload, EMQTT_QOS qos, uint16_t * messageid = NULL)
Definition at line 351 of file MQTT.cpp.
References publish().
                                                                                              {
    return publish(topic, (uint8_t*)payload, strlen(payload), false, qos, messageid);
}
publish() [4/10]
bool MQTT::publish (const char * topic, const char * payload, EMQTT_QOS qos, bool dup, uint16_t * messageid = NULL)
Definition at line 347 of file MQTT.cpp.
References publish().
                                                                                                        {
    return publish(topic, (uint8_t*)payload, strlen(payload), false, qos, dup, messageid);
}
publish() [5/10]
bool MQTT::publish (const char * topic, const uint8_t * pyaload, unsigned int plength)
Definition at line 355 of file MQTT.cpp.
References publish(), and QOS0.
                                                                                  {
    return publish(topic, payload, plength, false, QOS0, NULL);
}
publish() [6/10]
bool MQTT::publish (const char * topic, const uint8_t * payload, unsigned int plength, EMQTT_QOS qos, uint16_t * messageid = NULL)
Definition at line 363 of file MQTT.cpp.
References publish().
                                                                                                           
                 {
    return publish(topic, payload, plength, false, qos, messageid);
}
publish() [7/10]
bool MQTT::publish (const char * topic, const uint8_t * payload, unsigned int plength, EMQTT_QOS qos, bool dup, uint16_t * messageid = NULL)
Definition at line 359 of file MQTT.cpp.
References publish().
                                                                                                           
                           {
    return publish(topic, payload, plength, false, qos, dup, messageid);
}
publish() [8/10]
bool MQTT::publish (const char * topic, const uint8_t * payload, unsigned int plength, bool retain)
Definition at line 367 of file MQTT.cpp.
References publish(), and QOS0.
                                                                                               {
    return publish(topic, payload, plength, retain, QOS0, NULL);
}
publish() [9/10]
bool MQTT::publish (const char * topic, const uint8_t * payload, unsigned int plength, bool retain, EMQTT_QOS qos, uint16_t * messageid = NULL)
Definition at line 371 of file MQTT.cpp.
References publish().
Referenced by publish().
                                                                                                           
                              {
    return publish(topic, payload, plength, retain, qos, false, messageid);
}
publish() [10/10]
bool MQTT::publish (const char * topic, const uint8_t * payload, unsigned int plength, bool retain, EMQTT_QOS qos, bool dup, uint16_t * messageid)
Definition at line 375 of file MQTT.cpp.
References buffer, isConnected(), maxpacketsize, nextMsgId, QOS1, QOS2, write(), and writeString().
Referenced by publish().
                                                                                                           
                                        {
    if (isConnected()) {
        // Leave room in the buffer for header and variable length field
        uint16_t length = 5;
        memset(buffer, 0, this->maxpacketsize);
        length = writeString(topic, buffer, length);
        if (qos == QOS2 || qos == QOS1) {
            nextMsgId += 1;
            buffer[length++] = (nextMsgId >> 8);
            buffer[length++] = (nextMsgId & 0xFF);
            if (messageid != NULL)
                *messageid = nextMsgId++;
        }
        for (uint16_t i=0; i < plength && length < this->maxpacketsize; i++) {
            buffer[length++] = payload[i];
        }
        uint8_t header = MQTTPUBLISH;
        if (retain) {
            header |= 1;
        }
        if (dup) {
            header |= DUP_FLAG_ON_MASK;
        }
        if (qos == QOS2)
            header |= MQTTQOS2_HEADER_MASK;
        else if (qos == QOS1)
            header |= MQTTQOS1_HEADER_MASK;
        else
            header |= MQTTQOS0_HEADER_MASK;
        return write(header, buffer, length-5);
    }
    return false;
}
publishComplete()
bool MQTT::publishComplete (uint16_t messageid) [private]
Definition at line 429 of file MQTT.cpp.
References buffer, and isConnected().
Referenced by loop().
                                             {
    if (isConnected()) {
        uint16_t length = 0;
        // reserved bits in MQTT v3.1.1
        buffer[length++] = MQTTPUBCOMP | MQTTQOS1_HEADER_MASK;
        buffer[length++] = 2;
        buffer[length++] = (messageid >> 8);
        buffer[length++] = (messageid & 0xFF);
        return _client.write(buffer, length);
    }
    return false;
}
publishRelease()
bool MQTT::publishRelease (uint16_t messageid) [private]
Definition at line 416 of file MQTT.cpp.
References buffer, and isConnected().
Referenced by loop().
                                            {
    if (isConnected()) {
        uint16_t length = 0;
        // reserved bits in MQTT v3.1.1
        buffer[length++] = MQTTPUBREL | MQTTQOS1_HEADER_MASK;
        buffer[length++] = 2;
        buffer[length++] = (messageid >> 8);
        buffer[length++] = (messageid & 0xFF);
        return _client.write(buffer, length);
    }
    return false;
}
readByte()
uint8_t MQTT::readByte () [private]
Definition at line 190 of file MQTT.cpp.
Referenced by readPacket().
                       {
    while(!_client.available()) {}
    return _client.read();
}
readPacket()
uint16_t MQTT::readPacket (uint8_t * lengthLength) [private]
Definition at line 195 of file MQTT.cpp.
References buffer, maxpacketsize, and readByte().
Referenced by connect(), and loop().
                                               {
    uint16_t len = 0;
    buffer[len++] = readByte();
    bool isPublish = (buffer[0]&0xF0) == MQTTPUBLISH;
    uint32_t multiplier = 1;
    uint16_t length = 0;
    uint8_t digit = 0;
    uint16_t skip = 0;
    uint8_t start = 0;
    do {
        digit = readByte();
        buffer[len++] = digit;
        length += (digit & 127) * multiplier;
        multiplier *= 128;
    } while ((digit & 128) != 0);
    *lengthLength = len-1;
    if (isPublish) {
        // Read in topic length to calculate bytes to skip over for Stream writing
        buffer[len++] = readByte();
        buffer[len++] = readByte();
        skip = (buffer[*lengthLength+1]<<8)+buffer[*lengthLength+2];
        start = 2;
        if (buffer[0] & MQTTQOS1_HEADER_MASK) {
            // skip message id
            skip += 2;
        }
    }
    for (uint16_t i = start;i<length;i++) {
        digit = readByte();
        if (len < this->maxpacketsize) {
            buffer[len] = digit;
        }
        len++;
    }
    if (len > this->maxpacketsize) {
        len = 0; // This will cause the packet to be ignored.
    }
    return len;
}
setBroker() [1/2]
void MQTT::setBroker (char * domain, uint16_t port)
Definition at line 70 of file MQTT.cpp.
References disconnect(), domain, ip, isConnected(), String::operator=(), and port.
                                                {
    if(isConnected()) {
        disconnect();
    }
    this->domain = domain;
    this->ip = NULL;
    this->port = port;
}
setBroker() [2/2]
void MQTT::setBroker (uint8_t * ip, uint16_t port)
Definition at line 79 of file MQTT.cpp.
References disconnect(), domain, ip, isConnected(), String::operator=(), and port.
                                               {
    if(isConnected()) {
        disconnect();
    }
    this->domain = "";
    this->ip = ip;
    this->port = port;
}
subscribe() [1/2]
bool MQTT::subscribe (const char * topic)
Definition at line 469 of file MQTT.cpp.
References QOS0, and subscribe().
                                      {
    return subscribe(topic, QOS0);
}
subscribe() [2/2]
bool MQTT::subscribe (const char * topic, EMQTT_QOS qos)
Definition at line 473 of file MQTT.cpp.
References buffer, isConnected(), nextMsgId, write(), and writeString().
Referenced by subscribe().
                                                     {
    if (isConnected()) {
        // Leave room in the buffer for header and variable length field
        uint16_t length = 5;
        nextMsgId++;
        if (nextMsgId == 0) {
            nextMsgId = 1;
        }
        buffer[length++] = (nextMsgId >> 8);
        buffer[length++] = (nextMsgId & 0xFF);
        length = writeString(topic, buffer,length);
        buffer[length++] = qos;
        return write(MQTTSUBSCRIBE | MQTTQOS1_HEADER_MASK,buffer,length-5);
    }
    return false;
}
unsubscribe()
bool MQTT::unsubscribe (const char * topic)
Definition at line 491 of file MQTT.cpp.
References buffer, isConnected(), nextMsgId, write(), and writeString().
                                        {
    if (isConnected()) {
        uint16_t length = 5;
        nextMsgId++;
        if (nextMsgId == 0) {
            nextMsgId = 1;
        }
        buffer[length++] = (nextMsgId >> 8);
        buffer[length++] = (nextMsgId & 0xFF);
        length = writeString(topic, buffer,length);
        return write(MQTTUNSUBSCRIBE | MQTTQOS1_HEADER_MASK,buffer,length-5);
    }
    return false;
}
write()
bool MQTT::write (uint8_t header, uint8_t * buf, uint16_t length) [private]
Definition at line 442 of file MQTT.cpp.
Referenced by connect(), publish(), subscribe(), and unsubscribe().
                                                              {
    uint8_t lenBuf[4];
    uint8_t llen = 0;
    uint8_t digit;
    uint8_t pos = 0;
    uint16_t rc;
    uint16_t len = length;
    do {
        digit = len % 128;
        len = len / 128;
        if (len > 0) {
            digit |= 0x80;
        }
        lenBuf[pos++] = digit;
        llen++;
    } while(len > 0);
    buf[4-llen] = header;
    for (int i = 0; i < llen; i++) {
        buf[5-llen+i] = lenBuf[i];
    }
    rc = _client.write(buf+(4-llen), length+1+llen);
    lastOutActivity = millis();
    return (rc == 1+llen+length);
}
writeString()
uint16_t MQTT::writeString (const char * string, uint8_t * buf, uint16_t pos) [private]
Definition at line 514 of file MQTT.cpp.
References maxpacketsize.
Referenced by connect(), publish(), subscribe(), and unsubscribe().
                                                                         {
    const char* idp = string;
    uint16_t i = 0;
    pos += 2;
    while (*idp && pos < this->maxpacketsize) {
        buf[pos++] = *idp++;
        i++;
    }
    buf[pos-i-2] = (i >> 8);
    buf[pos-i-1] = (i & 0xFF);
    return pos;
}
Member Data Documentation
_client
TCPClient MQTT::_client [private]
Definition at line 129 of file MQTT.h.
buffer
uint8_t* MQTT::buffer = NULL [private]
Definition at line 130 of file MQTT.h.
Referenced by connect(), disconnect(), initialize(), loop(), publish(), publishComplete(), publishRelease(), readPacket(), subscribe(), unsubscribe(), and ~MQTT().
callback
void(* MQTT::callback) (char *, uint8_t *, unsigned int) [private]
Definition at line 135 of file MQTT.h.
Referenced by initialize(), and loop().
domain
 String MQTT::domain [private]
Definition at line 141 of file MQTT.h.
Referenced by initialize(), and setBroker().
ip
uint8_t* MQTT::ip = NULL [private]
Definition at line 142 of file MQTT.h.
Referenced by initialize(), and setBroker().
keepalive
int MQTT::keepalive [private]
Definition at line 144 of file MQTT.h.
Referenced by connect(), initialize(), and loop().
lastInActivity
unsigned long MQTT::lastInActivity [private]
Definition at line 133 of file MQTT.h.
Referenced by loop().
lastOutActivity
unsigned long MQTT::lastOutActivity [private]
Definition at line 132 of file MQTT.h.
Referenced by loop().
maxpacketsize
uint16_t MQTT::maxpacketsize [private]
Definition at line 145 of file MQTT.h.
Referenced by initialize(), publish(), readPacket(), and writeString().
nextMsgId
uint16_t MQTT::nextMsgId [private]
Definition at line 131 of file MQTT.h.
Referenced by connect(), publish(), subscribe(), and unsubscribe().
pingOutstanding
bool MQTT::pingOutstanding [private]
Definition at line 134 of file MQTT.h.
Referenced by connect(), and loop().
port
uint16_t MQTT::port [private]
Definition at line 143 of file MQTT.h.
Referenced by initialize(), and setBroker().
qoscallback
void(* MQTT::qoscallback) (unsigned int) [private]
Definition at line 136 of file MQTT.h.
Referenced by addQosCallback(), initialize(), and loop().
The documentation for this class was generated from the following files:
lib/MQTT/src/ MQTT.h
lib/MQTT/src/ MQTT.cpp