Print Class Reference
Class for printing to a stream or file.
#include <spark_wiring_print.h>
Public Member Functions
 Print ()
virtual ~Print ()
int getWriteError ()
void clearWriteError ()
virtual size_t write (uint8_t)=0
size_t write (const char *str)
virtual size_t write (const uint8_t *buffer, size_t size)
size_t print (const char[])
size_t print (char)
size_t print (unsigned char, int= DEC)
size_t print (int, int= DEC)
size_t print (unsigned int, int= DEC)
size_t print (long, int= DEC)
size_t print (unsigned long, int= DEC)
size_t print (double, int=2)
size_t print (const Printable &)
size_t println (const char[])
size_t println (char)
size_t println (unsigned char, int= DEC)
size_t println (int, int= DEC)
size_t println (unsigned int, int= DEC)
size_t println (long, int= DEC)
size_t println (unsigned long, int= DEC)
size_t println (double, int=2)
size_t println (const Printable &)
size_t println (void)
template<typename... Args>
size_t printf (const char *format, Args... args)
template<typename... Args>
size_t printlnf (const char *format, Args... args)
 Print ()
virtual ~Print ()
int getWriteError ()
Return the last error code. 0 means no error.
void clearWriteError ()
Clear the last error code to 0.
virtual size_t write (uint8_t c)=0
Write a single byte to the stream or file.
size_t write (const char *str)
Write a null-terminated c-string the stream or file.
virtual size_t write (const uint8_t *buffer, size_t size)
Write a bytes specified by a buffer and length to the stream or file.
size_t print (const char[])
Print a null-terminated array of char variables (a c-string) to the stream or file.
size_t print (char)
Print a single character to the stream or file.
size_t print (unsigned char value, int base= DEC)
Print an unsigned char (byte value, 8 bits) in the specified base to the stream or file.
size_t print (int value, int base= DEC)
Print an int (32 bit integer) the specified base to the stream or file.
size_t print (unsigned int value, int base= DEC)
Print an unsigned int (32 bit unsigned integer) the specified base to the stream or file.
size_t print (long value, int base= DEC)
Print a long (32 bit integer) the specified base to the stream or file.
size_t print (unsigned long value, int base= DEC)
Print a unsigned long (32 bit unsigned integer) the specified base to the stream or file.
size_t print (double value, int dec=2)
Print a double floating point value to the stream or file.
size_t print (const Printable &)
Print an object derived from Printable to the stream or file.
size_t print (const __FlashStringHelper *)
size_t println (const char[])
Print a null-terminated array of char variables (a c-string) plus a CRLF end-of-line terminator to the stream or file.
size_t println (char value)
Print a single character plus a CRLF end-of-line terminator to the stream or file.
size_t println (unsigned char value, int base= DEC)
Print an unsigned char (byte value. 8 bits) in the specified base plus a CRLF end-of-line terminator to the stream or file.
size_t println (int value, int base= DEC)
Print an int (32 bit integer) the specified base to plus a CRLF end-of-line terminator the stream or file.
size_t println (unsigned int value, int base= DEC)
Print an unsigned int (32 bit unsigned integer) the specified base plus a CRLF end-of-line terminator to the stream or file.
size_t println (long value, int base= DEC)
Print a long (32 bit signed integer) the specified base plus a CRLF end-of-line terminator to the stream or file.
size_t println (unsigned long value, int base= DEC)
Print a unsigned long (32 bit unsigned integer) the specified base plus a CRLF end-of-line terminator to the stream or file.
size_t println (double value, int dec=2)
Print a double floating point value plus a CRLF end-of-line terminator to the stream or file.
size_t println (const Printable &)
Print an object derived from Printable plus a CRLF end-of-line terminator to the stream or file.
size_t println (void)
Print a CRLF end-of-line terminator to the stream or file.
size_t println (const __FlashStringHelper *)
template<typename... Args>
size_t printf (const char *format, Args... args)
Print using printf-style formatting to the stream or file.
template<typename... Args>
size_t printlnf (const char *format, Args... args)
Print using printf-style formatting plus a CRLF end-of-line terminator to the stream or file.
Protected Member Functions
void setWriteError (int err=1)
size_t printf_impl (bool newline, const char *format,...)
void setWriteError (int err=1)
size_t printf_impl (bool newline, const char *format,...)
Private Member Functions
size_t printNumber (unsigned long, uint8_t)
size_t printFloat (double, uint8_t)
size_t printNumber (unsigned long, uint8_t)
size_t printFloat (double, uint8_t)
Private Attributes
int write_error
Detailed Description
Class for printing to a stream or file.
Various classes include serial, TCP network streams, and files inherit from this and can use these methods.
Definition at line 44 of file spark_wiring_print.h.
Constructor & Destructor Documentation
Print() [1/2]
Print::Print () [inline]
Definition at line 55 of file spark_wiring_print.h.
References write_error.
: write_error(0) {}
~Print() [1/2]
virtual Print::~Print () [inline], [virtual]
Definition at line 56 of file spark_wiring_print.h.
{}
Print() [2/2]
Print::Print () [inline]
Definition at line 64 of file spark_wiring_print.h.
: write_error(0) {}
~Print() [2/2]
virtual Print::~Print () [inline], [virtual]
Definition at line 66 of file spark_wiring_print.h.
{}
Member Function Documentation
clearWriteError() [1/2]
void Print::clearWriteError () [inline]
Definition at line 59 of file spark_wiring_print.h.
References setWriteError().
{ setWriteError(0); }
clearWriteError() [2/2]
void Print::clearWriteError () [inline]
Clear the last error code to 0.
Definition at line 76 of file spark_wiring_print.h.
{ setWriteError(0); }
getWriteError() [1/2]
int Print::getWriteError () [inline]
Definition at line 58 of file spark_wiring_print.h.
References write_error.
{ return write_error; }
getWriteError() [2/2]
int Print::getWriteError () [inline]
Return the last error code. 0 means no error.
Definition at line 71 of file spark_wiring_print.h.
{ return write_error; }
print() [1/19]
size_t Print::print (const char str[])
Definition at line 53 of file spark_wiring_print.cpp.
References write().
Referenced by printf_impl(), printFloat(), and println().
{
  return write(str);
}
print() [2/19]
size_t Print::print (char c)
Definition at line 58 of file spark_wiring_print.cpp.
References write().
Referenced by print(), printFloat(), and println().
{
  return write(c);
}
print() [3/19]
size_t Print::print (unsigned char b, int base = DEC)
Definition at line 63 of file spark_wiring_print.cpp.
References print().
Referenced by println().
{
  return print((unsigned long) b, base);
}
print() [4/19]
size_t Print::print (int n, int base = DEC)
Definition at line 68 of file spark_wiring_print.cpp.
References print().
Referenced by printFloat(), and println().
{
  return print((long) n, base);
}
print() [5/19]
size_t Print::print (unsigned int n, int base = DEC)
Definition at line 73 of file spark_wiring_print.cpp.
References print().
Referenced by println().
{
  return print((unsigned long) n, base);
}
print() [6/19]
size_t Print::print (long n, int base = DEC)
Definition at line 78 of file spark_wiring_print.cpp.
References print(), printNumber(), and write().
Referenced by print(), and println().
{
  if (base == 0) {
    return write(n);
  } else if (base == 10) {
    if (n < 0) {
      int t = print('-');
      n = -n;
      return printNumber(n, 10) + t;
    }
    return printNumber(n, 10);
  } else {
    return printNumber(n, base);
  }
}
print() [7/19]
size_t Print::print (unsigned long n, int base = DEC)
Definition at line 94 of file spark_wiring_print.cpp.
References printNumber(), and write().
Referenced by print(), printFloat(), and println().
{
  if (base == 0) return write(n);
  else return printNumber(n, base);
}
print() [8/19]
size_t Print::print (double n, int digits = 2)
Definition at line 100 of file spark_wiring_print.cpp.
References printFloat().
Referenced by println().
{
  return printFloat(n, digits);
}
print() [9/19]
size_t Print::print (const Printable & x)
Definition at line 105 of file spark_wiring_print.cpp.
References Printable::printTo().
Referenced by println().
 {
   return x.printTo(*this);
 }
print() [10/19]
size_t Print::print (const char [])
Print a null-terminated array of char variables (a c-string) to the stream or file.
print() [11/19]
size_t Print::print (char)
Print a single character to the stream or file.
print() [12/19]
size_t Print::print (unsigned char value, int base = DEC)
Print an unsigned char (byte value, 8 bits) in the specified base to the stream or file.
Parameters
value The value to print.
base The base to print. Default is DEC (decimal). Other values are HEX (hexadecimal), OCT (octal), and BIN (binary).
print() [13/19]
size_t Print::print (int value, int base = DEC)
Print an int (32 bit integer) the specified base to the stream or file.
Parameters
value The value to print.
base The base to print. Default is DEC (decimal). Other values are HEX (hexadecimal), OCT (octal), and BIN (binary).
print() [14/19]
size_t Print::print (unsigned int value, int base = DEC)
Print an unsigned int (32 bit unsigned integer) the specified base to the stream or file.
Parameters
value The value to print.
base The base to print. Default is DEC (decimal). Other values are HEX (hexadecimal), OCT (octal), and BIN (binary).
print() [15/19]
size_t Print::print (long value, int base = DEC)
Print a long (32 bit integer) the specified base to the stream or file.
Parameters
value The value to print.
base The base to print. Default is DEC (decimal). Other values are HEX (hexadecimal), OCT (octal), and BIN (binary).
print() [16/19]
size_t Print::print (unsigned long value, int base = DEC)
Print a unsigned long (32 bit unsigned integer) the specified base to the stream or file.
Parameters
value The value to print.
base The base to print. Default is DEC (decimal). Other values are HEX (hexadecimal), OCT (octal), and BIN (binary).
print() [17/19]
size_t Print::print (double value, int dec = 2)
Print a double floating point value to the stream or file.
Parameters
value The value to print.
dec The number of decimal places to include for the fractional part. Default: 2
print() [18/19]
size_t Print::print (const Printable &)
Print an object derived from Printable to the stream or file.
print() [19/19]
size_t Print::print (const __FlashStringHelper *)
printf() [1/2]
template<typename... Args>
size_t Print::printf (const char * format, Args... args) [inline]
Definition at line 90 of file spark_wiring_print.h.
References printf_impl().
    {
        return this->printf_impl(false, format, args...);
    }
printf() [2/2]
template<typename... Args>
size_t Print::printf (const char * format, Args... args) [inline]
Print using printf-style formatting to the stream or file.
Parameters
format printf-style formatting string
args variable arguments
Definition at line 256 of file spark_wiring_print.h.
    {
        return this->printf_impl(false, format, args...);
    }
printf_impl() [1/2]
size_t Print::printf_impl (bool newline, const char * format, ...) [protected]
Definition at line 246 of file spark_wiring_print.cpp.
References print(), and println().
Referenced by printf(), and printlnf().
{
    const int bufsize = 20;
    char test[bufsize];
    va_list marker;
    va_start(marker, format);
    size_t n = vsnprintf(test, bufsize, format, marker);
    va_end(marker);
    if (n<bufsize)
    {
        n = print(test);
    }
    else
    {
        char bigger[n+1];
        va_start(marker, format);
        n = vsnprintf(bigger, n+1, format, marker);
        va_end(marker);
        n = print(bigger);
    }
    if (newline)
        n += println();
    return n;
}
printf_impl() [2/2]
size_t Print::printf_impl (bool newline, const char * format, ...) [protected]
printFloat() [1/2]
size_t Print::printFloat (double number, uint8_t digits) [private]
Definition at line 201 of file spark_wiring_print.cpp.
References print().
Referenced by print().
{
  size_t n = 0;
  if (isnan(number)) return print("nan");
  if (isinf(number)) return print("inf");
  if (number > 4294967040.0) return print ("ovf"); // constant determined empirically
  if (number <-4294967040.0) return print ("ovf"); // constant determined empirically
  // Handle negative numbers
  if (number < 0.0)
  {
     n += print('-');
     number = -number;
  }
  // Round correctly so that print(1.999, 2) prints as "2.00"
  double rounding = 0.5;
  for (uint8_t i=0; i<digits; ++i)
    rounding /= 10.0;
  number += rounding;
  // Extract the integer part of the number and print it
  unsigned long int_part = (unsigned long)number;
  double remainder = number - (double)int_part;
  n += print(int_part);
  // Print the decimal point, but only if there are digits beyond
  if (digits > 0) {
    n += print(".");
  }
  // Extract digits from the remainder one at a time
  while (digits-- > 0)
  {
    remainder *= 10.0;
    int toPrint = int(remainder);
    n += print(toPrint);
    remainder -= toPrint;
  }
  return n;
}
printFloat() [2/2]
size_t Print::printFloat (double , uint8_t) [private]
println() [1/21]
size_t Print::println (const char c[])
Definition at line 117 of file spark_wiring_print.cpp.
References print(), and println().
{
  size_t n = print(c);
  n += println();
  return n;
}
println() [2/21]
size_t Print::println (char c)
Definition at line 124 of file spark_wiring_print.cpp.
References print(), and println().
{
  size_t n = print(c);
  n += println();
  return n;
}
println() [3/21]
size_t Print::println (unsigned char b, int base = DEC)
Definition at line 131 of file spark_wiring_print.cpp.
References print(), and println().
{
  size_t n = print(b, base);
  n += println();
  return n;
}
println() [4/21]
size_t Print::println (int num, int base = DEC)
Definition at line 138 of file spark_wiring_print.cpp.
References print(), and println().
{
  size_t n = print(num, base);
  n += println();
  return n;
}
println() [5/21]
size_t Print::println (unsigned int num, int base = DEC)
Definition at line 145 of file spark_wiring_print.cpp.
References print(), and println().
{
  size_t n = print(num, base);
  n += println();
  return n;
}
println() [6/21]
size_t Print::println (long num, int base = DEC)
Definition at line 152 of file spark_wiring_print.cpp.
References print(), and println().
{
  size_t n = print(num, base);
  n += println();
  return n;
}
println() [7/21]
size_t Print::println (unsigned long num, int base = DEC)
Definition at line 159 of file spark_wiring_print.cpp.
References print(), and println().
{
  size_t n = print(num, base);
  n += println();
  return n;
}
println() [8/21]
size_t Print::println (double num, int digits = 2)
Definition at line 166 of file spark_wiring_print.cpp.
References print(), and println().
{
  size_t n = print(num, digits);
  n += println();
  return n;
}
println() [9/21]
size_t Print::println (const Printable & x)
Definition at line 173 of file spark_wiring_print.cpp.
References print(), and println().
 {
   size_t n = print(x);
   n += println();
   return n;
 }
println() [10/21]
size_t Print::println (void)
Definition at line 110 of file spark_wiring_print.cpp.
References print().
Referenced by printf_impl(), and println().
{
  size_t n = print('\r');
  n += print('\n');
  return n;
}
println() [11/21]
size_t Print::println (const char [])
Print a null-terminated array of char variables (a c-string) plus a CRLF end-of-line terminator to the stream or file.
println() [12/21]
size_t Print::println (char value)
Print a single character plus a CRLF end-of-line terminator to the stream or file.
println() [13/21]
size_t Print::println (unsigned char value, int base = DEC)
Print an unsigned char (byte value. 8 bits) in the specified base plus a CRLF end-of-line terminator to the stream or file.
Parameters
value The value to print.
base The base to print. Default is DEC (decimal). Other values are HEX (hexadecimal), OCT (octal), and BIN (binary).
println() [14/21]
size_t Print::println (int value, int base = DEC)
Print an int (32 bit integer) the specified base to plus a CRLF end-of-line terminator the stream or file.
Parameters
value The value to print
base The base to print. Default is DEC (decimal). Other values are HEX (hexadecimal), OCT (octal), and BIN (binary).
println() [15/21]
size_t Print::println (unsigned int value, int base = DEC)
Print an unsigned int (32 bit unsigned integer) the specified base plus a CRLF end-of-line terminator to the stream or file.
Parameters
value The value to print
base The base to print. Default is DEC (decimal). Other values are HEX (hexadecimal), OCT (octal), and BIN (binary).
println() [16/21]
size_t Print::println (long value, int base = DEC)
Print a long (32 bit signed integer) the specified base plus a CRLF end-of-line terminator to the stream or file.
Parameters
value The value to print
base The base to print. Default is DEC (decimal). Other values are HEX (hexadecimal), OCT (octal), and BIN (binary).
println() [17/21]
size_t Print::println (unsigned long value, int base = DEC)
Print a unsigned long (32 bit unsigned integer) the specified base plus a CRLF end-of-line terminator to the stream or file.
Parameters
value The value to print.
base The base to print. Default is DEC (decimal). Other values are HEX (hexadecimal), OCT (octal), and BIN (binary).
println() [18/21]
size_t Print::println (double value, int dec = 2)
Print a double floating point value plus a CRLF end-of-line terminator to the stream or file.
Parameters
value The value to print.
dec The number of decimal places to include for the fractional part. Default: 2
println() [19/21]
size_t Print::println (const Printable &)
Print an object derived from Printable plus a CRLF end-of-line terminator to the stream or file.
println() [20/21]
size_t Print::println (void)
Print a CRLF end-of-line terminator to the stream or file.
println() [21/21]
size_t Print::println (const __FlashStringHelper *)
printlnf() [1/2]
template<typename... Args>
size_t Print::printlnf (const char * format, Args... args) [inline]
Definition at line 96 of file spark_wiring_print.h.
References printf_impl().
    {
        return this->printf_impl(true, format, args...);
    }
printlnf() [2/2]
template<typename... Args>
size_t Print::printlnf (const char * format, Args... args) [inline]
Print using printf-style formatting plus a CRLF end-of-line terminator to the stream or file.
Parameters
format printf-style formatting string
args variable arguments
Definition at line 269 of file spark_wiring_print.h.
    {
        return this->printf_impl(true, format, args...);
    }
printNumber() [1/2]
size_t Print::printNumber (unsigned long n, uint8_t base) [private]
Definition at line 182 of file spark_wiring_print.cpp.
References write().
Referenced by print().
                                                       {
  char buf[8 * sizeof(long) + 1]; // Assumes 8-bit chars plus zero byte.
  char *str = &buf[sizeof(buf) - 1];
  *str = '\0';
  // prevent crash if called with base == 1
  if (base < 2) base = 10;
  do {
    unsigned long m = n;
    n /= base;
    char c = m - base * n;
    *--str = c < 10 ? c + '0' : c + 'A' - 10;
  } while(n);
  return write(str);
}
printNumber() [2/2]
size_t Print::printNumber (unsigned long, uint8_t) [private]
setWriteError() [1/2]
void Print::setWriteError (int err = 1) [inline], [protected]
Definition at line 51 of file spark_wiring_print.h.
References write_error.
Referenced by clearWriteError().
{ write_error = err; }
setWriteError() [2/2]
void Print::setWriteError (int err = 1) [inline], [protected]
Definition at line 58 of file spark_wiring_print.h.
{ write_error = err; }
write() [1/6]
virtual size_t Print::write (uint8_t) [pure virtual]
Implemented in StringPrintableHelper .
Referenced by print(), and write().
write() [2/6]
size_t Print::write (const char * str) [inline]
Definition at line 62 of file spark_wiring_print.h.
References write().
Referenced by print(), and printNumber().
                                  {
      if (str == NULL) return 0;
      return write((const uint8_t *)str, strlen(str));
    }
write() [3/6]
size_t Print::write (const uint8_t * buffer, size_t size) [virtual]
Reimplemented in StringPrintableHelper .
Definition at line 37 of file spark_wiring_print.cpp.
References write().
Referenced by write().
{
  size_t n = 0;
  while (size--) {
     int chunk = write(*buffer++);
     if (chunk>=0)
         n += chunk;
     else {
         if (n==0)
             n = chunk;
         break;
     }
  }
  return n;
}
write() [4/6]
virtual size_t Print::write (uint8_t c) [pure virtual]
Write a single byte to the stream or file.
Parameters
c The byte to write. All values 0 - 255 are allowed.
Implemented in StringPrintableHelper .
write() [5/6]
size_t Print::write (const char * str) [inline]
Write a null-terminated c-string the stream or file.
Parameters
str point to a null-terminated c-string.
Definition at line 90 of file spark_wiring_print.h.
                                  {
      if (str == NULL) return 0;
      return write((const uint8_t *)str, strlen(str));
    }
write() [6/6]
virtual size_t Print::write (const uint8_t * buffer, size_t size) [virtual]
Write a bytes specified by a buffer and length to the stream or file.
Parameters
buffer pointer to the buffer. The data does not need to be null-terminated.
size size in bytes
Reimplemented in StringPrintableHelper .
Member Data Documentation
write_error
int Print::write_error [private]
Definition at line 47 of file spark_wiring_print.h.
Referenced by getWriteError(), Print(), and setWriteError().
The documentation for this class was generated from the following files:
lib/JsonParserGeneratorRK/test/gcclib/ spark_wiring_print.h
lib/JsonParserGeneratorRK/test/gcclib/ spark_wiring_print.cpp