JsonParserString Class Reference
Class used internally for writing to strings.
#include <JsonParserGeneratorRK.h>
Public Member Functions
 JsonParserString (String * str)
Construct a JsonParserString wrapping a Wiring String.
 JsonParserString (char * buf, size_t bufLen)
Construct a JsonParserString wrapping a buffer and length.
void append (char ch)
Append a single char to the underlying string.
void append (const char * str, size_t len)
Append a buffer and length to the underlying string.
size_t getLength () const
Get the length of the string.
Protected Attributes
 String * str
When writing to a String, the String object.
char * buf
When writing to a buffer, the pointer to the buffer. Not used for String.
size_t bufLen
When writing to a buffer, the length of the buffer in bytes. Not used for String.
size_t length
The current offset being written to.
Detailed Description
Class used internally for writing to strings.
This is a wrapper around either String (the Wiring version) or a buffer and length. This allows writing to a static buffer with no dynamic memory allocation at all.
One of the things about String is that while you can pre-allocate reserve space for data, you can't get access to the internal length field, so you can't write to raw bytes then resize it to the correct size. This wrapper is that allows appending to either a String or buffer to get around this limitation of String.
You can also use it for sizing only by passing NULL for buf.
Definition at line 92 of file JsonParserGeneratorRK.h.
Constructor & Destructor Documentation
JsonParserString() [1/2]
JsonParserString::JsonParserString (String * str)
Construct a JsonParserString wrapping a Wiring String.
Parameters
str A pointer Wiring String object to write to.
Definition at line 623 of file JsonParserGeneratorRK.cpp.
References buf, bufLen, length, and str.
Referenced by JsonParser::getTokenJsonString(), and JsonParser::getTokenValue().
                                              : str(str), buf(0), bufLen(0),
      length(0){
}
JsonParserString() [2/2]
JsonParserString::JsonParserString (char * buf, size_t bufLen)
Construct a JsonParserString wrapping a buffer and length.
Parameters
buf A pointer to a buffer
bufLen The length of the buffer in bytes
Definition at line 626 of file JsonParserGeneratorRK.cpp.
References buf, bufLen, length, and str.
Referenced by JsonParser::getTokenJsonString(), and JsonParser::getTokenValue().
                                                           : str(0), buf(buf),
      bufLen(bufLen), length(0){
    if (buf && bufLen) {
        memset(buf, 0, bufLen);
    }
}
Member Function Documentation
append() [1/2]
void JsonParserString::append (char ch)
Append a single char to the underlying string.
Parameters
ch The char to append.
Definition at line 632 of file JsonParserGeneratorRK.cpp.
References buf, bufLen, String::concat(), length, and str.
Referenced by append(), JsonParser::appendUtf8(), and JsonParser::getTokenValue().
                                     {
    if (str) {
        str->concat(ch);
        length++;
    }
    else {
        if (buf && length < (bufLen - 1)) {
            buf[length] = ch;
        }
        length++;
    }
}
append() [2/2]
void JsonParserString::append (const char * str, size_t len)
Append a buffer and length to the underlying string.
Parameters
str A pointer to the character to add. Does not need to be null-terminated.
len Length of the string to append in bytes.
Definition at line 645 of file JsonParserGeneratorRK.cpp.
References append().
Referenced by JsonParser::getTokenJsonString().
                                                         {
    for(size_t ii = 0; ii < len; ii++) {
        append(str[ii]);
    }
}
getLength()
size_t JsonParserString::getLength () const [inline]
Get the length of the string.
Returns
The string length in bytes. If the string contains UTF-8 characters, it will be the number of bytes, not characters.
For buffer and bufLenb, the maximum string length will be bufLen - 1 to leave room for the null terminator.
Definition at line 134 of file JsonParserGeneratorRK.h.
References length.
Referenced by JsonParser::getTokenJsonString(), and JsonParser::getTokenValue().
{ return length; }
Member Data Documentation
buf
char* JsonParserString::buf [protected]
When writing to a buffer, the pointer to the buffer. Not used for String.
Definition at line 138 of file JsonParserGeneratorRK.h.
Referenced by append(), and JsonParserString().
bufLen
size_t JsonParserString::bufLen [protected]
When writing to a buffer, the length of the buffer in bytes. Not used for String.
Definition at line 139 of file JsonParserGeneratorRK.h.
Referenced by append(), and JsonParserString().
length
size_t JsonParserString::length [protected]
The current offset being written to.
Definition at line 140 of file JsonParserGeneratorRK.h.
Referenced by append(), getLength(), and JsonParserString().
str
 String* JsonParserString::str [protected]
When writing to a String, the String object.
Definition at line 137 of file JsonParserGeneratorRK.h.
Referenced by append(), and JsonParserString().
The documentation for this class was generated from the following files:
lib/JsonParserGeneratorRK/src/ JsonParserGeneratorRK.h
lib/JsonParserGeneratorRK/src/ JsonParserGeneratorRK.cpp