StringSumHelper Class Reference
Class used when appending mutiple String and other values using +.
#include <spark_wiring_string.h>
Public Member Functions
 StringSumHelper (const String &s)
Append a String object.
 StringSumHelper (const char *p)
Append a const char * (c-string, null terminated)
 StringSumHelper (char c)
Append a single character.
 StringSumHelper (unsigned char num)
Append a byte as a decimal number 0 - 255.
 StringSumHelper (int num)
Append a 32-bit signed integer as a decimal number.
 StringSumHelper (unsigned int num)
Append a 32-bit unsigned integer as a decimal number.
 StringSumHelper (long num)
Append a 32-bit long integer as a decimal number.
 StringSumHelper (unsigned long num)
Append a 32-bit unsigned long as a decimal number.
Additional Inherited Members
Detailed Description
Class used when appending mutiple String and other values using +.
Definition at line 1085 of file spark_wiring_string.h.
Constructor & Destructor Documentation
StringSumHelper() [1/8]
StringSumHelper::StringSumHelper (const String & s) [inline]
Append a String object.
Parameters
s The string to append.
Returns
StringSumHelper object that encapsulates a copy of that string for appending to another string.
Definition at line 1095 of file spark_wiring_string.h.
References String::String().
: String(s) {}
StringSumHelper() [2/8]
StringSumHelper::StringSumHelper (const char * p) [inline]
Append a const char * (c-string, null terminated)
Parameters
p The string to append.
Returns
StringSumHelper object that encapsulates a copy of that string for appending to another string.
Definition at line 1104 of file spark_wiring_string.h.
References String::String().
: String(p) {}
StringSumHelper() [3/8]
StringSumHelper::StringSumHelper (char c) [inline]
Append a single character.
Parameters
c The character to append.
Returns
StringSumHelper object that encapsulates a copy of that character for appending to another string.
Definition at line 1113 of file spark_wiring_string.h.
References String::String().
: String(c) {}
StringSumHelper() [4/8]
StringSumHelper::StringSumHelper (unsigned char num) [inline]
Append a byte as a decimal number 0 - 255.
Parameters
num The byte value to append.
Returns
StringSumHelper object that encapsulates the textual representation of the number for appending to another string.
Definition at line 1122 of file spark_wiring_string.h.
References String::String().
: String(num) {}
StringSumHelper() [5/8]
StringSumHelper::StringSumHelper (int num) [inline]
Append a 32-bit signed integer as a decimal number.
Parameters
num The byte value to append.
Returns
StringSumHelper object that encapsulates the textual representation of the number for appending to another string.
Definition at line 1131 of file spark_wiring_string.h.
References String::String().
: String(num) {}
StringSumHelper() [6/8]
StringSumHelper::StringSumHelper (unsigned int num) [inline]
Append a 32-bit unsigned integer as a decimal number.
Parameters
num The byte value to append.
Returns
StringSumHelper object that encapsulates the textual representation of the number for appending to another string.
Definition at line 1140 of file spark_wiring_string.h.
References String::String().
: String(num) {}
StringSumHelper() [7/8]
StringSumHelper::StringSumHelper (long num) [inline]
Append a 32-bit long integer as a decimal number.
Parameters
num The byte value to append.
Returns
StringSumHelper object that encapsulates the textual representation of the number for appending to another string.
Definition at line 1149 of file spark_wiring_string.h.
References String::String().
: String(num) {}
StringSumHelper() [8/8]
StringSumHelper::StringSumHelper (unsigned long num) [inline]
Append a 32-bit unsigned long as a decimal number.
Parameters
num The byte value to append.
Returns
StringSumHelper object that encapsulates the textual representation of the number for appending to another string.
Definition at line 1158 of file spark_wiring_string.h.
References String::String().
: String(num) {}
The documentation for this class was generated from the following file:
lib/JsonParserGeneratorRK/docs/src/ spark_wiring_string.h