JsonParser Class Reference
API to the JsonParser.
#include <JsonParserGeneratorRK.h>
Public Member Functions
 JsonParser ()
Construct a parser object.
virtual ~JsonParser ()
Destroy a parser object.
 JsonParser (char * buffer, size_t bufferLen, JsonParserGeneratorRK::jsmntok_t * tokens, size_t maxTokens)
Static buffers constructor.
bool allocateTokens (size_t maxTokens)
Preallocates a specific number of tokens.
bool parse ()
Parses the data you have added using addData() or addString().
 JsonReference getReference () const
Get a JsonReference object. This is used for fluent-style access to the data.
const JsonParserGeneratorRK::jsmntok_t * getOuterObject () const
Gets the outer JSON object token.
const JsonParserGeneratorRK::jsmntok_t * getOuterArray () const
Gets the outer JSON array token.
const JsonParserGeneratorRK::jsmntok_t * getOuterToken () const
Gets the outer JSON object or array token.
size_t getArraySize (const JsonParserGeneratorRK::jsmntok_t *arrayContainer) const
Given a token for an JSON array in arrayContainer, gets the number of elements in the array.
template<class T >
bool getValueByKey (const JsonParserGeneratorRK::jsmntok_t *container, const char *name, T &result) const
Given an object token in container, gets the value with the specified key name.
template<class T >
bool getOuterValueByKey (const char *name, T &result) const
Gets the value with the specified key name out of the outer object.
template<class T >
bool getKeyValueByIndex (const JsonParserGeneratorRK::jsmntok_t *container, size_t index, String &key, T &result) const
Gets the key/value pair of an object by index.
template<class T >
bool getOuterKeyValueByIndex (size_t index, String &key, T &result) const
Gets the key/value pair of the outer object by index (0 = first, 1 = second, ...)
template<class T >
bool getValueByIndex (const JsonParserGeneratorRK::jsmntok_t *arrayContainer, size_t index, T &result) const
Given an array token in arrayContainer, gets the value with the specified index.
template<class T >
bool getValueByColRow (const JsonParserGeneratorRK::jsmntok_t *arrayContainer, size_t col, size_t row, T &result) const
This method is used to extract data from a 2-dimensional JSON array, an array of arrays of values.
bool getValueTokenByKey (const JsonParserGeneratorRK::jsmntok_t *container, const char *key, const JsonParserGeneratorRK::jsmntok_t *&value) const
Given an object token in container, gets the token value with the specified key name.
bool getValueTokenByIndex (const JsonParserGeneratorRK::jsmntok_t *container, size_t desiredIndex, const JsonParserGeneratorRK::jsmntok_t *&value) const
Given an array token in container, gets the token value with the specified index.
bool getValueTokenByColRow (const JsonParserGeneratorRK::jsmntok_t *container, size_t col, size_t row, const JsonParserGeneratorRK::jsmntok_t *&value) const
This method is used to extract data from a 2-dimensional JSON array, an array of arrays of values.
const JsonParserGeneratorRK::jsmntok_t * getTokenByIndex (const JsonParserGeneratorRK::jsmntok_t *container, size_t desiredIndex) const
Given a containing object, finds the nth token in the object. Internal use only.
bool getKeyValueTokenByIndex (const JsonParserGeneratorRK::jsmntok_t *container, const JsonParserGeneratorRK::jsmntok_t *&key, const JsonParserGeneratorRK::jsmntok_t *&value, size_t index) const
Given a JSON object in container, gets the key/value pair specified by index. Internal use only.
bool skipObject (const JsonParserGeneratorRK::jsmntok_t *container, const JsonParserGeneratorRK::jsmntok_t *&obj) const
Used internally to skip over the token in obj.
void copyTokenValue (const JsonParserGeneratorRK::jsmntok_t *token, char *dst, size_t dstLen) const
Copies the value of the token into a buffer, making it a null-terminated cstring.
bool getTokenValue (const JsonParserGeneratorRK::jsmntok_t *token, bool &result) const
Gets a bool (boolean) value.
bool getTokenValue (const JsonParserGeneratorRK::jsmntok_t *token, int &result) const
Gets an integer value.
bool getTokenValue (const JsonParserGeneratorRK::jsmntok_t *token, unsigned long &result) const
Gets an unsigned long value.
bool getTokenValue (const JsonParserGeneratorRK::jsmntok_t *token, float &result) const
Gets a float (single precision floating point) value.
bool getTokenValue (const JsonParserGeneratorRK::jsmntok_t *token, double &result) const
Gets a double (double precision floating point) value.
bool getTokenValue (const JsonParserGeneratorRK::jsmntok_t *token, String &result) const
Gets a String value into a Wiring String object.
bool getTokenValue (const JsonParserGeneratorRK::jsmntok_t *token, char *str, size_t &strLen) const
Gets a string as a c-string into the specified buffer.
bool getTokenValue (const JsonParserGeneratorRK::jsmntok_t *token, JsonParserString &str) const
Gets a string as a JsonParserString object.
bool getTokenJsonString (const JsonParserGeneratorRK::jsmntok_t *token, String &result) const
Converts a token (object, array, string, or primitive) back into JSON in a Wiring String.
bool getTokenJsonString (const JsonParserGeneratorRK::jsmntok_t *token, char *str, size_t &strLen) const
Converts a token (object, array, string, or primitive) back into JSON in a buffer.
bool getTokenJsonString (const JsonParserGeneratorRK::jsmntok_t *token, JsonParserString &str) const
Gets a token as a JSON string.
 JsonParserGeneratorRK::jsmntok_t * getTokens ()
Used internally in the test suite for printing the token list.
 JsonParserGeneratorRK::jsmntok_t * getTokensEnd ()
Used internally in the test suite for printing the token list.
size_t getMaxTokens () const
Used internally in the test suite for printing the token list.
Static Public Member Functions
static void appendUtf8 (uint16_t unicode, JsonParserString &str)
Given a Unicode UTF-16 code point, converts it to UTF-8 and appends it to str.
Protected Attributes
 JsonParserGeneratorRK::jsmntok_t * tokens
Array of tokens after parsing.
 JsonParserGeneratorRK::jsmntok_t * tokensEnd
Pointer into tokens, points after last used token.
size_t maxTokens
Number of tokens that can be stored in tokens.
 JsonParserGeneratorRK::jsmn_parser parser
The JSMN parser object.
Friends
class JsonModifier
Detailed Description
API to the JsonParser.
This is a memory-efficient JSON parser based on jsmn. It only keeps one copy of the data in raw format and an array of tokens. You make calls to read values out.
Definition at line 262 of file JsonParserGeneratorRK.h.
Constructor & Destructor Documentation
JsonParser() [1/2]
JsonParser::JsonParser ()
Construct a parser object.
This version dynamically allocates the buffer and token storage. If you want to minimize memory allocations you can pass in a static buffer and array of tokens to use instead.
Definition at line 80 of file JsonParserGeneratorRK.cpp.
References JsonBuffer::JsonBuffer(), maxTokens, tokens, and tokensEnd.
                       : JsonBuffer(), tokens(0), tokensEnd(0), maxTokens(0) {
}
~JsonParser()
JsonParser::~JsonParser () [virtual]
Destroy a parser object.
If the buffer was allocated dynamically it will be deleted. If you passed in a static buffer the static buffer is not deleted.
Definition at line 89 of file JsonParserGeneratorRK.cpp.
References JsonBuffer::staticBuffers, and tokens.
                        {
    if (!staticBuffers && tokens) {
        free(tokens);
    }
}
JsonParser() [2/2]
JsonParser::JsonParser (char * buffer, size_t bufferLen, JsonParserGeneratorRK::jsmntok_t * tokens, size_t maxTokens)
Static buffers constructor.
Definition at line 83 of file JsonParserGeneratorRK.cpp.
References JsonBuffer::JsonBuffer(), maxTokens, and tokens.
                                                                                                           
          :
        JsonBuffer(buffer, bufferLen), tokens(tokens), maxTokens(maxTokens) {
}
Member Function Documentation
allocateTokens()
bool JsonParser::allocateTokens (size_t maxTokens)
Preallocates a specific number of tokens.
Optional: You should set this larger than the expected number of tokens for efficiency, but if you are not using the static allocator it will resize the token storage space if it's too small.
Definition at line 95 of file JsonParserGeneratorRK.cpp.
References JsonBuffer::buffer, maxTokens, JsonBuffer::staticBuffers, and tokens.
                                                {
    if (!staticBuffers) {
        JsonParserGeneratorRK::jsmntok_t *newTokens;
        if (tokens) {
            newTokens = (JsonParserGeneratorRK::jsmntok_t *)realloc(buffer, sizeof(
      JsonParserGeneratorRK::jsmntok_t) * maxTokens);
        }
        else {
            newTokens = (JsonParserGeneratorRK::jsmntok_t *)malloc(sizeof(
      JsonParserGeneratorRK::jsmntok_t) * maxTokens);
        }
        if (newTokens) {
            tokens = newTokens;
            this->maxTokens = maxTokens;
            return true;
        }
        else {
            return false;
        }
    }
    else {
        return false;
    }
}
appendUtf8()
void JsonParser::appendUtf8 (uint16_t unicode, JsonParserString & str) [static]
Given a Unicode UTF-16 code point, converts it to UTF-8 and appends it to str.
Definition at line 509 of file JsonParserGeneratorRK.cpp.
References JsonParserString::append().
Referenced by getTokenValue().
                                                                   {
    unsigned char value;
    if (unicode <= 0x007f) {
        // 0x00000000 - 0x0000007F:
        str.append((char)unicode);
    }
    else
    if (unicode <= 0x7ff) {
        // 0x00000080 - 0x000007FF:
        // 110xxxxx 10xxxxxx
        value = (0b11000000 | ((unicode >> 6) & 0b11111));
        str.append((char)value);
        value = (0b10000000 | (unicode & 0b111111));
        str.append((char)value);
    }
    else {
        // 0x00000800 - 0x0000FFFF:
        // 1110xxxx 10xxxxxx 10xxxxxx
        value = 0b11100000 | ((unicode >> 12) & 0b1111);
        str.append((char)value);
        value = 0b10000000 | ((unicode >> 6) & 0b111111);
        str.append((char)value);
        value = 0b10000000 | (unicode & 0b111111);
        str.append((char)value);
    }
}
copyTokenValue()
void JsonParser::copyTokenValue (const JsonParserGeneratorRK::jsmntok_t * token, char * dst, size_t dstLen) const
Copies the value of the token into a buffer, making it a null-terminated cstring.
If the string is longer than dstLen - 1 bytes, it will be truncated and the result will still be a valid cstring.
This is used internally because the token data is not null-terminated, and doing things like sscanf or strtoul on it can read past the end of the buffer. This assures that only null-terminated data is passed to these functions.
Definition at line 327 of file JsonParserGeneratorRK.cpp.
References JsonBuffer::buffer, JsonParserGeneratorRK::jsmntok_t::end, and JsonParserGeneratorRK::jsmntok_t::start.
Referenced by getTokenValue().
                                                                                                           
      {
    int ii;
    for(ii = 0; ii < (token->end - token->start) && ii < ((int)dstLen - 1); ii++) {
        dst[ii] = buffer[token->start + ii];
    }
    dst[ii] = 0;
}
getArraySize()
size_t JsonParser::getArraySize (const JsonParserGeneratorRK::jsmntok_t * arrayContainer) const
Given a token for an JSON array in arrayContainer, gets the number of elements in the array.
0 = no elements, 1 = one element, ...
The index values for getValueByIndex(), etc. are 0-based, so the last index you pass in is less than getArraySize().
Definition at line 315 of file JsonParserGeneratorRK.cpp.
References JsonParserGeneratorRK::jsmntok_t::end, skipObject(), and tokensEnd.
Referenced by main(), and JsonReference::size().
                                                                                          {
    size_t index = 0;
    const JsonParserGeneratorRK::jsmntok_t *token = arrayContainer + 1;
    while(token < tokensEnd && token->end < arrayContainer->end) {
        index++;
        skipObject(arrayContainer, token);
    }
    return index;
}
getKeyValueByIndex()
template<class T >
bool JsonParser::getKeyValueByIndex (const JsonParserGeneratorRK::jsmntok_t * container, size_t index, String & key, T & result) const [inline]
Gets the key/value pair of an object by index.
Parameters
container The object to look in (see getOuterKeyValueByIndex if you want to the outermost object you parsed)
index 0 = first, 1 = second, ...
key Filled in with the name of the key
result Filled in with the value. The value can be of type: bool, int, unsigned long, float, double, String, or (char *, size_t&).
Returns
true if the call succeeded or false if it failed.
Normally you get a value in an object by its key, but if you want to iterate all of the keys you can use this method. Call it until it returns false.
This should only be used for things like string, numbers, booleans, etc.. If you want to get a JSON array or object within an object, use getValueTokenByKey() instead.
Definition at line 425 of file JsonParserGeneratorRK.h.
References getKeyValueTokenByIndex(), and getTokenValue().
                                                                                                           
                    {
        const JsonParserGeneratorRK::jsmntok_t *keyToken;
        const JsonParserGeneratorRK::jsmntok_t *valueToken;
        if (getKeyValueTokenByIndex(container, keyToken, valueToken, index)) {
            getTokenValue(keyToken, key);
            return getTokenValue(valueToken, result);
        }
        else {
            return false;
        }
    }
getKeyValueTokenByIndex()
bool JsonParser::getKeyValueTokenByIndex (const JsonParserGeneratorRK::jsmntok_t * container, const JsonParserGeneratorRK::jsmntok_t *& key, const JsonParserGeneratorRK::jsmntok_t *& value, size_t index) const
Given a JSON object in container, gets the key/value pair specified by index. Internal use only.
Parameters
container The array token to look in.
key Filled in with the key token for nth key value pair.
value Filled in with the value token for then nth key value pair.
index The index to retrieve (0 = first, 1 = second, ...).
This is a low-level function; you will typically use getValueByIndex() or getValueByKey() instead.
Definition at line 250 of file JsonParserGeneratorRK.cpp.
References JsonParserGeneratorRK::jsmntok_t::end, skipObject(), and tokensEnd.
Referenced by getKeyValueByIndex(), getValueTokenByKey(), main(), and printJsonInner().
                                                                                                           
                                                                                                        {
    size_t index = 0;
    const JsonParserGeneratorRK::jsmntok_t *token = container + 1;
    while(token < tokensEnd && token->end < container->end) {
        if (desiredIndex == index) {
            key = token;
            if (skipObject(container, token)) {
                value = token;
                return true;
            }
        }
        index++;
        skipObject(container, token);
        skipObject(container, token);
    }
    return false;
}
getMaxTokens()
size_t JsonParser::getMaxTokens () const [inline]
Used internally in the test suite for printing the token list.
Definition at line 743 of file JsonParserGeneratorRK.h.
References maxTokens.
{ return maxTokens; };
getOuterArray()
const JsonParserGeneratorRK::jsmntok_t * JsonParser::getOuterArray () const
Gets the outer JSON array token.
Sometimes the JSON will contain an array of values (or objects) instead of starting with an object. This gets the outermost array.
A token (JsonParserGeneratorRK::jsmntok_t) identifies a particular piece of data in the JSON data, such as an object, array, or element within an object or array, such as a string, integer, boolean, etc..
Definition at line 192 of file JsonParserGeneratorRK.cpp.
References JsonParserGeneratorRK::JSMN_ARRAY, tokens, tokensEnd, and JsonParserGeneratorRK::jsmntok_t::type.
Referenced by main().
                                                                      {
    for(const JsonParserGeneratorRK::jsmntok_t *token = tokens; token <
      tokensEnd; token++) {
        if (token->type == JsonParserGeneratorRK::JSMN_ARRAY) {
            return token;
        }
    }
    return 0;
}
getOuterKeyValueByIndex()
template<class T >
bool JsonParser::getOuterKeyValueByIndex (size_t index, String & key, T & result) const [inline]
Gets the key/value pair of the outer object by index (0 = first, 1 = second, ...)
Normally you get a value in an object by its key, but if you want to iterate all of the keys you can use this method.
Parameters
index 0 = first, 1 = second, ...
key Filled in with the name of the key
result Filled in with the value. The value can be of type: bool, int, unsigned long, float, double, String, or (char *, size_t&).
Returns
true if the call succeeded or false if it failed.
This should only be used for things like string, numbers, booleans, etc.. If you want to get a JSON array or object within an object, use getValueTokenByKey() instead.
Definition at line 457 of file JsonParserGeneratorRK.h.
References getOuterObject().
Referenced by runTest().
                                                                             {
        return getKeyValueByIndex(getOuterObject(), index, key, result);
    }
getOuterObject()
const JsonParserGeneratorRK::jsmntok_t * JsonParser::getOuterObject () const
Gets the outer JSON object token.
Typically JSON will contain an object that contains values and possibly other objects. This method gets the token for the outer object.
A token (JsonParserGeneratorRK::jsmntok_t) identifies a particular piece of data in the JSON data, such as an object, array, or element within an object or array, such as a string, integer, boolean, etc..
Definition at line 218 of file JsonParserGeneratorRK.cpp.
References JsonParserGeneratorRK::JSMN_OBJECT, tokens, tokensEnd, and JsonParserGeneratorRK::jsmntok_t::type.
Referenced by getOuterKeyValueByIndex(), getOuterValueByKey(), and main().
                                                                       {
    if (tokens < tokensEnd && tokens[0].type ==
      JsonParserGeneratorRK::JSMN_OBJECT) {
        return &tokens[0];
    }
    else {
        return 0;
    }
}
getOuterToken()
const JsonParserGeneratorRK::jsmntok_t * JsonParser::getOuterToken () const
Gets the outer JSON object or array token.
A token (JsonParserGeneratorRK::jsmntok_t) identifies a particular piece of data in the JSON data, such as an object, array, or element within an object or array, such as a string, integer, boolean, etc..
Definition at line 227 of file JsonParserGeneratorRK.cpp.
References JsonParserGeneratorRK::JSMN_ARRAY, JsonParserGeneratorRK::JSMN_OBJECT, tokens, tokensEnd, and JsonParserGeneratorRK::jsmntok_t::type.
Referenced by main(), and printJson().
                                                                      {
    for(const JsonParserGeneratorRK::jsmntok_t *token = tokens; token <
      tokensEnd; token++) {
        if (token->type == JsonParserGeneratorRK::JSMN_OBJECT || token->type ==
      JsonParserGeneratorRK::JSMN_ARRAY) {
            return token;
        }
    }
    return 0;
}
getOuterValueByKey()
template<class T >
bool JsonParser::getOuterValueByKey (const char * name, T & result) const [inline]
Gets the value with the specified key name out of the outer object.
Parameters
name The name of the key to retrieve
result The returned data.
Returns
true if the data was retrieved successfully, false if not (key not present or incompatible data type).
The outer object must be a JSON object, not an array.
This should only be used for things like string, numbers, booleans, etc.. If you want to get a JSON array or object within an object, use getValueTokenByKey() instead.
Definition at line 393 of file JsonParserGeneratorRK.h.
References getOuterObject(), and getValueTokenByKey().
Referenced by main(), and runTest().
                                                               {
        const JsonParserGeneratorRK::jsmntok_t *value;
        if (getValueTokenByKey(getOuterObject(), name, value)) {
            return getTokenValue(value, result);
        }
        else {
            return false;
        }
    }
getReference()
 JsonReference JsonParser::getReference () const
Get a JsonReference object. This is used for fluent-style access to the data.
Definition at line 182 of file JsonParserGeneratorRK.cpp.
References JsonReference::JsonReference(), tokens, and tokensEnd.
Referenced by main().
                                             {
    if (tokens < tokensEnd) {
        return JsonReference(this, &tokens[0]);
    }
    else {
        return JsonReference(this);
    }
}
getTokenByIndex()
const JsonParserGeneratorRK::jsmntok_t * JsonParser::getTokenByIndex (const JsonParserGeneratorRK::jsmntok_t * container, size_t desiredIndex) const
Given a containing object, finds the nth token in the object. Internal use only.
Parameters
container The array token to look in.
desiredIndex The index to retrieve (0 = first, 1 = second, ...).
Returns
The token
This is used internally. It should not be used to get the nth array value, use getValueTokenByIndex instead.
Definition at line 201 of file JsonParserGeneratorRK.cpp.
References JsonParserGeneratorRK::jsmntok_t::end, skipObject(), and tokensEnd.
Referenced by main(), and JsonModifier::removeArrayIndex().
                                                                                                           
                                       {
    size_t index = 0;
    const JsonParserGeneratorRK::jsmntok_t *token = container + 1;
    while(token < tokensEnd && token->end < container->end) {
        if (desiredIndex == index) {
            return token;
        }
        index++;
        skipObject(container, token);
    }
    return 0;
}
getTokenJsonString() [1/3]
bool JsonParser::getTokenJsonString (const JsonParserGeneratorRK::jsmntok_t * token, String & result) const
Converts a token (object, array, string, or primitive) back into JSON in a Wiring String.
Parameters
token The token to convert back to a string
result Filled in with the string. Any previous contents in the string are cleared first.
Definition at line 487 of file JsonParserGeneratorRK.cpp.
References JsonParserGeneratorRK::jsmntok_t::end, getTokenJsonString(), JsonParserString::JsonParserString(), String::operator=(), String::reserve(), and JsonParserGeneratorRK::jsmntok_t::start.
Referenced by main().
                                                                                                     {
    result = "";
    result.reserve(token->end - token->start + 3);
    JsonParserString strWrapper(&result);
    return getTokenJsonString(token, strWrapper);
}
getTokenJsonString() [2/3]
bool JsonParser::getTokenJsonString (const JsonParserGeneratorRK::jsmntok_t * token, char * str, size_t & strLen) const
Converts a token (object, array, string, or primitive) back into JSON in a buffer.
Parameters
token The token to convert back to a string
str The buffer to be written to
strLen The length of the buffer on entry, set to the number of bytes written on exit.
Definition at line 495 of file JsonParserGeneratorRK.cpp.
References JsonParserString::getLength(), getTokenJsonString(), and JsonParserString::JsonParserString().
Referenced by main().
                                                                                                           
           {
    JsonParserString strWrapper(str, bufLen);
    bool result = getTokenJsonString(token, strWrapper);
    bufLen = strWrapper.getLength() + 1;
    return result;
}
getTokenJsonString() [3/3]
bool JsonParser::getTokenJsonString (const JsonParserGeneratorRK::jsmntok_t * token, JsonParserString & str) const
Gets a token as a JSON string.
Parameters
token The token to convert back to a string
str The JsonParserString object to write to
This overload is typically used internally, normally you'd use the version that takes a String& or char *, size_t.
Definition at line 502 of file JsonParserGeneratorRK.cpp.
References JsonParserString::append(), JsonBuffer::buffer, JsonParserGeneratorRK::jsmntok_t::end, and JsonParserGeneratorRK::jsmntok_t::start.
Referenced by getTokenJsonString().
                                                                                                           
       {
    str.append(&buffer[token->start], token->end - token->start);
    return true;
}
getTokens()
 JsonParserGeneratorRK::jsmntok_t* JsonParser::getTokens () [inline]
Used internally in the test suite for printing the token list.
Definition at line 733 of file JsonParserGeneratorRK.h.
References tokens.
Referenced by printTokens().
{ return tokens; };
getTokensEnd()
 JsonParserGeneratorRK::jsmntok_t* JsonParser::getTokensEnd () [inline]
Used internally in the test suite for printing the token list.
Definition at line 738 of file JsonParserGeneratorRK.h.
References tokensEnd.
Referenced by printTokens().
{ return tokensEnd; };
getTokenValue() [1/8]
bool JsonParser::getTokenValue (const JsonParserGeneratorRK::jsmntok_t * token, bool & result) const
Gets a bool (boolean) value.
Normally you'd use getValueByKey(), getValueByIndex() or getValueByColRow() which will automatically use this when the result parameter is a bool variable.
Definition at line 338 of file JsonParserGeneratorRK.cpp.
References JsonBuffer::buffer, JsonParserGeneratorRK::jsmntok_t::end, and JsonParserGeneratorRK::jsmntok_t::start.
Referenced by main().
                                                                                              {
    if (token->end > token->start) {
        switch(buffer[token->start]) {
        case 't': // should be this
        case 'T':
        case 'y':
        case 'Y':
        case '1':
            result = true;
            break;
        default:
            result = false;
            break;
        }
        return true;
    }
    else {
        return false;
    }
}
getTokenValue() [2/8]
bool JsonParser::getTokenValue (const JsonParserGeneratorRK::jsmntok_t * token, int & result) const
Gets an integer value.
Normally you'd use getValueByKey(), getValueByIndex() or getValueByColRow() which will automatically use this when the result parameter is an int variable.
Definition at line 360 of file JsonParserGeneratorRK.cpp.
References copyTokenValue().
Referenced by main().
                                                                                             {
    // Copy data here, because tokens are not null terminated
    char tmp[16];
    copyTokenValue(token, tmp, sizeof(tmp));
    if (sscanf(tmp, "%d", &result) == 1) {
        return true;
    }
    else {
        return false;
    }
}
getTokenValue() [3/8]
bool JsonParser::getTokenValue (const JsonParserGeneratorRK::jsmntok_t * token, unsigned long & result) const
Gets an unsigned long value.
Normally you'd use getValueByKey(), getValueByIndex() or getValueByColRow() which will automatically use this when the result parameter is an unsigned long variable.
Definition at line 373 of file JsonParserGeneratorRK.cpp.
References copyTokenValue().
                                                                                                       {
    // Copy data here, because tokens are not null terminated
    char tmp[16];
    copyTokenValue(token, tmp, sizeof(tmp));
    if (sscanf(tmp, "%lu", &result) == 1) {
        return true;
    }
    else {
        return false;
    }
}
getTokenValue() [4/8]
bool JsonParser::getTokenValue (const JsonParserGeneratorRK::jsmntok_t * token, float & result) const
Gets a float (single precision floating point) value.
Normally you'd use getValueByKey(), getValueByIndex() or getValueByColRow() which will automatically use this when the result parameter is a float variable.
Definition at line 388 of file JsonParserGeneratorRK.cpp.
References copyTokenValue().
Referenced by main().
                                                                                               {
    // Copy data here, because tokens are not null terminated
    char tmp[16];
    copyTokenValue(token, tmp, sizeof(tmp));
    result = strtof(tmp, 0);
    return true;
}
getTokenValue() [5/8]
bool JsonParser::getTokenValue (const JsonParserGeneratorRK::jsmntok_t * token, double & result) const
Gets a double (double precision floating point) value.
Normally you'd use getValueByKey(), getValueByIndex() or getValueByColRow() which will automatically use this when the result parameter is a double variable.
Definition at line 397 of file JsonParserGeneratorRK.cpp.
References copyTokenValue().
Referenced by main().
                                                                                                {
    // Copy data here, because tokens are not null terminated
    char tmp[16];
    copyTokenValue(token, tmp, sizeof(tmp));
    result = strtod(tmp, 0);
    return true;
}
getTokenValue() [6/8]
bool JsonParser::getTokenValue (const JsonParserGeneratorRK::jsmntok_t * token, String & result) const
Gets a String value into a Wiring String object.
This will automatically decode Unicode character escapes in the data and the returned String will contain UTF-8.
Normally you'd use getValueByKey(), getValueByIndex() or getValueByColRow() which will automatically use this when the result parameter is a String variable.
Definition at line 408 of file JsonParserGeneratorRK.cpp.
References JsonParserGeneratorRK::jsmntok_t::end, getTokenValue(), JsonParserString::JsonParserString(), String::operator=(), String::reserve(), and JsonParserGeneratorRK::jsmntok_t::start.
Referenced by getKeyValueByIndex(), getValueTokenByKey(), main(), and printJsonInner().
                                                                                                {
    result = "";
    result.reserve(token->end - token->start + 1);
    JsonParserString strWrapper(&result);
    return getTokenValue(token, strWrapper);
}
getTokenValue() [7/8]
bool JsonParser::getTokenValue (const JsonParserGeneratorRK::jsmntok_t * token, char * str, size_t & strLen) const
Gets a string as a c-string into the specified buffer.
If the token specifies too large of a string it will be truncated. This will automatically decode Unicode character escapes in the data and the returned string will contain UTF-8.
Definition at line 417 of file JsonParserGeneratorRK.cpp.
References JsonParserString::getLength(), getTokenValue(), and JsonParserString::JsonParserString().
Referenced by main().
                                                                                                           
      {
    JsonParserString strWrapper(str, bufLen);
    bool result = getTokenValue(token, strWrapper);
    bufLen = strWrapper.getLength() + 1;
    return result;
}
getTokenValue() [8/8]
bool JsonParser::getTokenValue (const JsonParserGeneratorRK::jsmntok_t * token, JsonParserString & str) const
Gets a string as a JsonParserString object.
This is used internally by getTokenValue() overloads that take a String or buffer and length; you will normally not need to use this directly.
This will automatically decode Unicode character escapes in the data and the returned string will contain UTF-8.
Definition at line 425 of file JsonParserGeneratorRK.cpp.
References JsonParserString::append(), appendUtf8(), JsonBuffer::buffer, JsonParserGeneratorRK::jsmntok_t::end, and JsonParserGeneratorRK::jsmntok_t::start.
Referenced by getTokenValue().
                                                                                                       {
    int unicode;
    bool escape = false;
    for(int ii = token->start; ii < token->end; ii++) {
        if (escape) {
            escape = false;
            switch(buffer[ii]) {
            case 'b':
                str.append('\b');
                break;
            case 'f':
                str.append('\f');
                break;
            case 'n':
                str.append('\n');
                break;
            case 'r':
                str.append('\r');
                break;
            case 't':
                str.append('\t');
                break;
            case 'u':
                if ((ii + 4) < token->end) {
                    // Copy data here because buffer is not null terminated and this could
                    // read past the end otherwise
                    char tmp[5];
                    for(size_t jj = 0; jj < 4; jj++) {
                        tmp[jj] = buffer[ii + jj + 1];
                    }
                    tmp[4] = 0;
                    if (sscanf(tmp, "%04x", &unicode) == 1) {
                        appendUtf8((uint16_t)unicode, str);
                        ii += 5; // also increments in loop
                    }
                }
                break;
            default:
                str.append(buffer[ii]);
                break;
            }
        }
        else
        if (buffer[ii] == '\\') {
            escape = true;
        }
        else {
            str.append(buffer[ii]);
        }
    }
    return true;
}
getValueByColRow()
template<class T >
bool JsonParser::getValueByColRow (const JsonParserGeneratorRK::jsmntok_t * arrayContainer, size_t col, size_t row, T & result) const [inline]
This method is used to extract data from a 2-dimensional JSON array, an array of arrays of values.
Parameters
arrayContainer A token for an array containing another array
col The column (outer array index, 0 = first column, 1 = second column, ...)
row The row (inner array index, 0 = first row, 1 = second row, ...)
result Filled in with the value. The value can be of type: bool, int, unsigned long, float, double, String, or (char *, size_t&).
Returns
true if the call succeeded or false if it failed. You can call this repeatedly until it returns false to iterate the array.
This should only be used for things like string, numbers, booleans, etc.. If you want to get a JSON array or object within a two-dimensional array, use getValueTokenByColRow() instead.
Definition at line 509 of file JsonParserGeneratorRK.h.
References getValueTokenByColRow().
Referenced by main().
                                                                                                           
                    {
        const JsonParserGeneratorRK::jsmntok_t *value;
        if (getValueTokenByColRow(arrayContainer, col, row, value)) {
            return getTokenValue(value, result);
        }
        else {
            return false;
        }
    }
getValueByIndex()
template<class T >
bool JsonParser::getValueByIndex (const JsonParserGeneratorRK::jsmntok_t * arrayContainer, size_t index, T & result) const [inline]
Given an array token in arrayContainer, gets the value with the specified index.
Parameters
arrayContainer A token for an array
index The index in the array. 0 = first item, 1 = second item, ...
result Filled in with the value. The value can be of type: bool, int, unsigned long, float, double, String, or (char *, size_t&).
Returns
true if the call succeeded or false if it failed. You can call this repeatedly until it returns false to iterate the array.
This should only be used for things like string, numbers, booleans, etc.. If you want to get a JSON array or object within an array, use getValueTokenByIndex() instead.
Definition at line 479 of file JsonParserGeneratorRK.h.
References getValueTokenByIndex().
Referenced by main().
                                                                                                           
         {
        const JsonParserGeneratorRK::jsmntok_t *value;
        if (getValueTokenByIndex(arrayContainer, index, value)) {
            return getTokenValue(value, result);
        }
        else {
            return false;
        }
    }
getValueByKey()
template<class T >
bool JsonParser::getValueByKey (const JsonParserGeneratorRK::jsmntok_t * container, const char * name, T & result) const [inline]
Given an object token in container, gets the value with the specified key name.
Parameters
container The token for the object to obtain the data from.
name The name of the key to retrieve
result The returned data. The value can be of type: bool, int, unsigned long, float, double, String, or (char *, size_t&).
Returns
true if the data was retrieved successfully, false if not (key not present or incompatible data type).
This should only be used for things like string, numbers, booleans, etc.. If you want to get a JSON array or object within an object, use getValueTokenByKey() instead.
Definition at line 367 of file JsonParserGeneratorRK.h.
References getValueTokenByKey().
Referenced by main().
                                                                                                           
      {
        const JsonParserGeneratorRK::jsmntok_t *value;
        if (getValueTokenByKey(container, name, value)) {
            return getTokenValue(value, result);
        }
        else {
            return false;
        }
    }
getValueTokenByColRow()
bool JsonParser::getValueTokenByColRow (const JsonParserGeneratorRK::jsmntok_t * container, size_t col, size_t row, const JsonParserGeneratorRK::jsmntok_t *& value) const
This method is used to extract data from a 2-dimensional JSON array, an array of arrays of values.
Parameters
container A token for an array containing another array
col The column (outer array index, 0 = first column, 1 = second column, ...)
row The row (inner array index, 0 = first row, 1 = second row, ...)
value Filled in with the token for the value for key.
Returns
true if the index row and column are valid or false if either is out of range.
This can be used for 2-dimensional arrays whose values are arrays or objects, to get the token for the container. It can also be used for values, but normally you'd use getValueByColRow() instead, which is generally more convenient.
Definition at line 301 of file JsonParserGeneratorRK.cpp.
References getValueTokenByIndex().
Referenced by getValueByColRow().
                                                                                                           
                                                             {
    const JsonParserGeneratorRK::jsmntok_t *columnContainer;
    if (getValueTokenByIndex(container, col, columnContainer)) {
        return getValueTokenByIndex(columnContainer, row, value);
    }
    else {
        return false;
    }
}
getValueTokenByIndex()
bool JsonParser::getValueTokenByIndex (const JsonParserGeneratorRK::jsmntok_t * container, size_t desiredIndex, const JsonParserGeneratorRK::jsmntok_t *& value) const
Given an array token in container, gets the token value with the specified index.
Parameters
container The array token to look in.
desiredIndex The index to retrieve (0 = first, 1 = second, ...).
value Filled in with the token for the value for key.
Returns
true if the index is valid or false if the index exceeds the size of the array.
This can be used for arrays whose values are arrays or objects, to get the token for the container. It can also be used for values, but normally you'd use getValueByIndex() instead, which is generally more convenient.
Definition at line 285 of file JsonParserGeneratorRK.cpp.
References JsonParserGeneratorRK::jsmntok_t::end, skipObject(), and tokensEnd.
Referenced by getValueByIndex(), getValueTokenByColRow(), JsonReference::index(), main(), and printJsonInner().
                                                                                                           
                                                         {
    size_t index = 0;
    const JsonParserGeneratorRK::jsmntok_t *token = container + 1;
    while(token < tokensEnd && token->end < container->end) {
        if (desiredIndex == index) {
            value = token;
            return true;
        }
        index++;
        skipObject(container, token);
    }
    return false;
}
getValueTokenByKey()
bool JsonParser::getValueTokenByKey (const JsonParserGeneratorRK::jsmntok_t * container, const char * key, const JsonParserGeneratorRK::jsmntok_t *& value) const
Given an object token in container, gets the token value with the specified key name.
Parameters
container The object token to look in.
key The key to look for.
value Filled in with the token for the value for key.
Returns
true if the key is found or false if not.
This can be used for objects whose keys are arrays or objects, to get the token for the container. It can also be used for values, but normally you'd use getValueByKey() instead, which is generally more convenient.
Definition at line 272 of file JsonParserGeneratorRK.cpp.
References getKeyValueTokenByIndex(), getTokenValue(), and String::operator==().
Referenced by getOuterValueByKey(), getValueByKey(), JsonReference::key(), main(), and JsonModifier::removeKeyValue().
                                                                                                           
                                                    {
    const JsonParserGeneratorRK::jsmntok_t *key;
    String keyName;
    for(size_t ii = 0; getKeyValueTokenByIndex(container, key, value, ii); ii++) {
        if (getTokenValue(key, keyName) && keyName == name) {
            return true;
        }
    }
    return false;
}
parse()
bool JsonParser::parse ()
Parses the data you have added using addData() or addString().
When parsing data split into multiple chunks as a webhook response you can call addString() in your webhook subscription handler and call parse after each chunk. Only on the last chunk will parse return true, and you'll know the entire reponse has been received.
Definition at line 118 of file JsonParserGeneratorRK.cpp.
References JsonBuffer::buffer, JsonParserGeneratorRK::JSMN_ERROR_NOMEM, JsonParserGeneratorRK::jsmn_init(), JsonParserGeneratorRK::jsmn_parse(), maxTokens, JsonBuffer::offset, parser, JsonBuffer::staticBuffers, tokens, and tokensEnd.
Referenced by JsonModifier::finish(), getMeasure_callback(), main(), JsonModifier::removeArrayIndex(), JsonModifier::removeKeyValue(), runTest(), and subscriptionHandler().
                       {
    if (offset == 0) {
        // If addString or addData is not called, or called with an empty string,
        // do not return true, see issue #7.
        return false;
    }
    if (tokens) {
        // Try to use the existing token buffer if possible
        JsonParserGeneratorRK::jsmn_init(&parser);
        int result = JsonParserGeneratorRK::jsmn_parse(&parser, buffer, offset,
      tokens, maxTokens);
        if (result == JsonParserGeneratorRK::JSMN_ERROR_NOMEM) {
            if (staticBuffers) {
                // If using static buffers and there is not enough space, fail
                return false;
            }
            free(tokens);
            tokens = 0;
            maxTokens = 0;
        }
        else
        if (result < 0) {
            // Failed to parse: JSMN_ERROR_INVAL or JSMN_ERROR_PART
            return false;
        }
        else {
            tokensEnd = &tokens[result];
            return true;
        }
    }
    // Pass 1: determine now many tokens we need
    JsonParserGeneratorRK::jsmn_init(&parser);
    int result = JsonParserGeneratorRK::jsmn_parse(&parser, buffer, offset, 0, 0);
    if (result < 0) {
        // Failed to parse: JSMN_ERROR_INVAL or JSMN_ERROR_PART
        return false;
    }
    // If we get here, tokens will always be == 0; it would have been freed if it was
    // too small, and this code is never executed for staticBuffers == true
    maxTokens = (size_t) result;
    if (maxTokens > 0) {
        tokens = (JsonParserGeneratorRK::jsmntok_t *)malloc(sizeof(
      JsonParserGeneratorRK::jsmntok_t) * maxTokens);
        JsonParserGeneratorRK::jsmn_init(&parser);
        int result = JsonParserGeneratorRK::jsmn_parse(&parser, buffer, offset,
      tokens, maxTokens);
        tokensEnd = &tokens[result];
    }
    else {
        tokensEnd = tokens;
    }
    /*
    for(const JsonParserGeneratorRK::jsmntok_t *token = tokens; token < tokensEnd; token++) {
        printf("%d, %d, %d, %d\n", token->type, token->start, token->end, token->size);
    }
    */
    return true;
}
skipObject()
bool JsonParser::skipObject (const JsonParserGeneratorRK::jsmntok_t * container, const JsonParserGeneratorRK::jsmntok_t *& obj) const
Used internally to skip over the token in obj.
Parameters
container The array token to look in.
obj Object within the token, updated to the next object if true is returned
Returns
true if there was a next object, false if not.
For simple primitives and strings, this is equivalent to obj++. For objects and arrays, however, this skips over the entire object or array, including any nested objects within them.
Definition at line 237 of file JsonParserGeneratorRK.cpp.
References JsonParserGeneratorRK::jsmntok_t::end, and tokensEnd.
Referenced by getArraySize(), getKeyValueTokenByIndex(), getTokenByIndex(), and getValueTokenByIndex().
                                                                                                           
                        {
    int curObjectEnd = obj->end;
    while(++obj < tokensEnd && obj->end < container->end && obj->end <= curObjectEnd) {
    }
    if (obj >= tokensEnd || obj->end > container->end) {
        // No object after index
        return false;
    }
    return true;
}
Friends And Related Function Documentation
JsonModifier
friend class JsonModifier [friend]
Definition at line 756 of file JsonParserGeneratorRK.h.
Member Data Documentation
maxTokens
size_t JsonParser::maxTokens [protected]
Number of tokens that can be stored in tokens.
Definition at line 753 of file JsonParserGeneratorRK.h.
Referenced by allocateTokens(), getMaxTokens(), JsonParser(), and parse().
parser
 JsonParserGeneratorRK::jsmn_parser JsonParser::parser [protected]
The JSMN parser object.
Definition at line 754 of file JsonParserGeneratorRK.h.
Referenced by parse().
tokens
 JsonParserGeneratorRK::jsmntok_t* JsonParser::tokens [protected]
Array of tokens after parsing.
Definition at line 751 of file JsonParserGeneratorRK.h.
Referenced by allocateTokens(), getOuterArray(), getOuterObject(), getOuterToken(), getReference(), getTokens(), JsonParser(), parse(), and ~JsonParser().
tokensEnd
 JsonParserGeneratorRK::jsmntok_t* JsonParser::tokensEnd [protected]
Pointer into tokens, points after last used token.
Definition at line 752 of file JsonParserGeneratorRK.h.
Referenced by getArraySize(), getKeyValueTokenByIndex(), getOuterArray(), getOuterObject(), getOuterToken(), getReference(), getTokenByIndex(), getTokensEnd(), getValueTokenByIndex(), JsonParser(), parse(), and skipObject().
The documentation for this class was generated from the following files:
lib/JsonParserGeneratorRK/src/ JsonParserGeneratorRK.h
lib/JsonParserGeneratorRK/src/ JsonParserGeneratorRK.cpp