JsonBuffer Class Reference
Base class for managing a static or dynamic buffer, used by both JsonParser and JsonWriter.
#include <JsonParserGeneratorRK.h>
Public Member Functions
JsonBuffer ()
Construct a JsonBuffer object with no external buffer specified.
virtual ~JsonBuffer ()
Destructor. Destroying the object does not delete any underlying buffer!
JsonBuffer (char *buffer, size_t bufferLen)
Construct a JsonBuffer with an external buffer of a given size.
void setBuffer (char *buffer, size_t bufferLen)
Sets the buffers to the specified buffer and length.
bool allocate (size_t len)
Allocate the buffer using malloc/realloc.
bool addString (const char *data)
Add a c-string to the end of the buffer.
bool addData (const char *data, size_t dataLen)
Add a string to the end of the buffer.
char * getBuffer () const
Gets a pointer to the internal buffer.
size_t getOffset () const
Gets the current offset for writing.
void setOffset (size_t offset)
swets the current offset for writing
size_t getBufferLen () const
Gets the current length of the buffer.
void clear ()
Clears the current buffer for writing.
void nullTerminate ()
Null terminates the buffer.
Protected Attributes
char * buffer
The buffer to to read from or write to. This is not null-terminated.
size_t bufferLen
The length of the buffer in bytes,.
size_t offset
The read or write offset.
bool staticBuffers
True if the buffers were passed in and should not freed or reallocated.
Detailed Description
Base class for managing a static or dynamic buffer, used by both JsonParser and JsonWriter.
Definition at line 146 of file JsonParserGeneratorRK.h.
Constructor & Destructor Documentation
JsonBuffer() [1/2]
JsonBuffer::JsonBuffer ()
Construct a JsonBuffer object with no external buffer specified.
Definition at line 6 of file JsonParserGeneratorRK.cpp.
References buffer, bufferLen, offset, and staticBuffers.
Referenced by JsonParser::JsonParser(), and JsonWriter::JsonWriter().
 JsonBuffer()
JsonBuffer::~JsonBuffer () [virtual]
Destructor. Destroying the object does not delete any underlying buffer!
Definition at line 9 of file JsonParserGeneratorRK.cpp.
References buffer, and staticBuffers.
JsonBuffer() [2/2]
JsonBuffer::JsonBuffer (char * buffer, size_t bufferLen)
Construct a JsonBuffer with an external buffer of a given size.
Parameters
buffer Pointer to the buffer
bufferLen The length of the buffer
This buffer will not be deleted when the object is destructed.
Definition at line 15 of file JsonParserGeneratorRK.cpp.
References buffer, bufferLen, offset, and staticBuffers.
Referenced by JsonParser::JsonParser(), and JsonWriter::JsonWriter().
Member Function Documentation
addData()
bool JsonBuffer::addData (const char * data, size_t dataLen)
Add a string to the end of the buffer.
Parameters
data Pointer to the string bytes. Does not need to be null-terminated
dataLen Length of the data in bytes. For UTF-8, this is the number of bytes, not characters!
Definition at line 48 of file JsonParserGeneratorRK.cpp.
References allocate(), buffer, bufferLen, and offset.
Referenced by addString(), and main().
addString()
bool JsonBuffer::addString (const char * data) [inline]
Add a c-string to the end of the buffer.
Parameters
data Pointer to a c-string (null terminated).
Definition at line 197 of file JsonParserGeneratorRK.h.
References addData().
Referenced by main(), runTest(), and subscriptionHandler().
allocate()
bool JsonBuffer::allocate (size_t len)
Allocate the buffer using malloc/realloc.
Parameters
len The length of the buffer in bytes
Returns
true if the allocation/reallocation was successful or false if there was not enough free memory.
There's also a version that takes a pointer and length to use a static buffer instead of a dynamically allocated one.
Definition at line 25 of file JsonParserGeneratorRK.cpp.
References buffer, bufferLen, and staticBuffers.
Referenced by addData(), and main().
clear()
void JsonBuffer::clear ()
Clears the current buffer for writing.
This only sets the offset to 0, it does not clear the bytes.
Definition at line 62 of file JsonParserGeneratorRK.cpp.
References offset.
Referenced by getMeasure_callback(), runTest(), and subscriptionHandler().
getBuffer()
char* JsonBuffer::getBuffer () const [inline]
Gets a pointer to the internal buffer.
Note: The internal buffer is not null-terminated!
Definition at line 213 of file JsonParserGeneratorRK.h.
References buffer.
Referenced by _assertJsonParserBuffer(), _assertJsonWriterBuffer(), JsonModifier::findLeftComma(), JsonModifier::findRightComma(), JsonModifier::finish(), printJsonInner(), printToken(), JsonModifier::removeArrayIndex(), JsonModifier::removeKeyValue(), runTest(), JsonModifier::startAppend(), and JsonModifier::startModify().
getBufferLen()
size_t JsonBuffer::getBufferLen () const [inline]
Gets the current length of the buffer.
The buffer length is either the bufferLen passed to the constructor that takes a buffer and bufferLen or the length allocated using allocate(len).
Definition at line 231 of file JsonParserGeneratorRK.h.
References bufferLen.
Referenced by JsonModifier::startAppend(), and JsonModifier::startModify().
getOffset()
size_t JsonBuffer::getOffset () const [inline]
Gets the current offset for writing.
Definition at line 218 of file JsonParserGeneratorRK.h.
References offset.
Referenced by _assertJsonParserBuffer(), _assertJsonWriterBuffer(), JsonModifier::findRightComma(), JsonModifier::finish(), JsonModifier::removeArrayIndex(), JsonModifier::removeKeyValue(), JsonModifier::startAppend(), and JsonModifier::startModify().
nullTerminate()
void JsonBuffer::nullTerminate ()
Null terminates the buffer.
Definition at line 66 of file JsonParserGeneratorRK.cpp.
References buffer, bufferLen, and offset.
setBuffer()
void JsonBuffer::setBuffer (char * buffer, size_t bufferLen)
Sets the buffers to the specified buffer and length.
Parameters
buffer Pointer to the buffer
bufferLen The length of the buffer
This buffer will not be deleted when the object is destructed.
Definition at line 19 of file JsonParserGeneratorRK.cpp.
References buffer, bufferLen, and staticBuffers.
Referenced by JsonModifier::startAppend(), and JsonModifier::startModify().
setOffset()
void JsonBuffer::setOffset (size_t offset) [inline]
swets the current offset for writing
Definition at line 223 of file JsonParserGeneratorRK.h.
References offset.
Referenced by JsonModifier::finish(), JsonModifier::removeArrayIndex(), and JsonModifier::removeKeyValue().
Member Data Documentation
buffer
char* JsonBuffer::buffer [protected]
The buffer to to read from or write to. This is not null-terminated.
Definition at line 246 of file JsonParserGeneratorRK.h.
Referenced by addData(), allocate(), JsonParser::allocateTokens(), JsonParser::copyTokenValue(), JsonWriter::finishObjectOrArray(), getBuffer(), JsonParser::getTokenJsonString(), JsonParser::getTokenValue(), JsonWriter::insertChar(), JsonWriter::insertvsprintf(), JsonBuffer(), nullTerminate(), JsonParser::parse(), setBuffer(), and ~JsonBuffer().
bufferLen
size_t JsonBuffer::bufferLen [protected]
The length of the buffer in bytes,.
Definition at line 247 of file JsonParserGeneratorRK.h.
Referenced by addData(), allocate(), JsonWriter::finishObjectOrArray(), getBufferLen(), JsonWriter::insertChar(), JsonWriter::insertString(), JsonWriter::insertvsprintf(), JsonBuffer(), nullTerminate(), and setBuffer().
offset
size_t JsonBuffer::offset [protected]
The read or write offset.
Definition at line 248 of file JsonParserGeneratorRK.h.
Referenced by addData(), clear(), JsonWriter::finishObjectOrArray(), getOffset(), JsonWriter::init(), JsonWriter::insertChar(), JsonWriter::insertString(), JsonWriter::insertvsprintf(), JsonBuffer(), nullTerminate(), JsonParser::parse(), and setOffset().
staticBuffers
bool JsonBuffer::staticBuffers [protected]
True if the buffers were passed in and should not freed or reallocated.
Definition at line 249 of file JsonParserGeneratorRK.h.
Referenced by allocate(), JsonParser::allocateTokens(), JsonBuffer(), JsonParser::parse(), setBuffer(), ~JsonBuffer(), and JsonParser::~JsonParser().
The documentation for this class was generated from the following files:
lib/JsonParserGeneratorRK/src/JsonParserGeneratorRK.h
lib/JsonParserGeneratorRK/src/JsonParserGeneratorRK.cpp