JsonParserGeneratorRK Namespace Reference
Classes
struct jsmn_parser
JSON parser.
struct jsmntok_t
JSON token description.
Enumerations
enum jsmntype_t {
 JSMN_UNDEFINED = 0,
 JSMN_OBJECT = 1,
 JSMN_ARRAY = 2,
 JSMN_STRING = 3,
 JSMN_PRIMITIVE = 4
 }
JSON type identifier (object, array, string, primitive)
enum jsmnerr { JSMN_ERROR_NOMEM = -1,
 JSMN_ERROR_INVAL = -2,
 JSMN_ERROR_PART = -3
 }
JSMN error codes.
Functions
void jsmn_init (jsmn_parser *parser)
Create JSON parser over an array of tokens.
int jsmn_parse (jsmn_parser *parser, const char *js, size_t len, jsmntok_t *tokens, unsigned int num_tokens)
Run JSON parser.
static jsmntok_t * jsmn_alloc_token (jsmn_parser *parser, jsmntok_t *tokens, size_t num_tokens)
static void jsmn_fill_token (jsmntok_t *token, jsmntype_t type, int start, int end)
static int jsmn_parse_primitive (jsmn_parser *parser, const char *js, size_t len, jsmntok_t *tokens, size_t num_tokens)
static int jsmn_parse_string (jsmn_parser *parser, const char *js, size_t len, jsmntok_t *tokens, size_t num_tokens)
Enumeration Type Documentation
jsmnerr
enum JsonParserGeneratorRK::jsmnerr
JSMN error codes.
Enumerator
JSMN_ERROR_NOMEM Not enough tokens were provided.
JSMN_ERROR_INVAL Invalid character inside JSON string.
JSMN_ERROR_PART The string is not a full JSON packet, more bytes expected.
Definition at line 30 of file JsonParserGeneratorRK.h.
                 {
        JSMN_ERROR_NOMEM = -1,
        JSMN_ERROR_INVAL = -2,
        JSMN_ERROR_PART = -3
    };
jsmntype_t
enum JsonParserGeneratorRK::jsmntype_t
JSON type identifier (object, array, string, primitive)
Enumerator
JSMN_UNDEFINED undefined JSON type
JSMN_OBJECT JSON object.
JSMN_ARRAY JSON array.
JSMN_STRING JSON string.
JSMN_PRIMITIVE JSON primitive (number, true, false, or null)
Definition at line 19 of file JsonParserGeneratorRK.h.
                 {
        JSMN_UNDEFINED = 0,
        JSMN_OBJECT = 1,
        JSMN_ARRAY = 2,
        JSMN_STRING = 3,
        JSMN_PRIMITIVE = 4
    } jsmntype_t;
Function Documentation
jsmn_alloc_token()
static jsmntok_t* JsonParserGeneratorRK::jsmn_alloc_token (jsmn_parser * parser, jsmntok_t * tokens, size_t num_tokens) [static]
Allocates a fresh unused token from the token pull.
Definition at line 1102 of file JsonParserGeneratorRK.cpp.
References JsonParserGeneratorRK::jsmntok_t::end, JsonParserGeneratorRK::jsmntok_t::size, JsonParserGeneratorRK::jsmntok_t::start, and JsonParserGeneratorRK::jsmn_parser::toknext.
Referenced by jsmn_parse(), jsmn_parse_primitive(), and jsmn_parse_string().
                                              {
    jsmntok_t *tok;
    if (parser->toknext >= num_tokens) {
        return NULL;
    }
    tok = &tokens[parser->toknext++];
    tok->start = tok->end = -1;
    tok->size = 0;
#ifdef JSMN_PARENT_LINKS
    tok->parent = -1;
#endif
    return tok;
}
jsmn_fill_token()
static void JsonParserGeneratorRK::jsmn_fill_token (jsmntok_t * token, jsmntype_t type, int start, int end) [static]
Fills token type and boundaries.
Definition at line 1120 of file JsonParserGeneratorRK.cpp.
References JsonParserGeneratorRK::jsmntok_t::end, JsonParserGeneratorRK::jsmntok_t::size, JsonParserGeneratorRK::jsmntok_t::start, and JsonParserGeneratorRK::jsmntok_t::type.
Referenced by jsmn_parse_primitive(), and jsmn_parse_string().
                                                {
    token->type = type;
    token->start = start;
    token->end = end;
    token->size = 0;
}
jsmn_init()
void JsonParserGeneratorRK::jsmn_init (jsmn_parser * parser)
Create JSON parser over an array of tokens.
Creates a new parser based over a given buffer with an array of tokens available.
Definition at line 1405 of file JsonParserGeneratorRK.cpp.
References JsonParserGeneratorRK::jsmn_parser::pos, JsonParserGeneratorRK::jsmn_parser::toknext, and JsonParserGeneratorRK::jsmn_parser::toksuper.
Referenced by JsonParser::parse().
                                    {
    parser->pos = 0;
    parser->toknext = 0;
    parser->toksuper = -1;
}
jsmn_parse()
int JsonParserGeneratorRK::jsmn_parse (jsmn_parser * parser, const char * js, size_t len, jsmntok_t * tokens, unsigned int num_tokens)
Run JSON parser.
It parses a JSON data string into and array of tokens, each describing a single JSON object.
Parse JSON string and fill tokens.
Definition at line 1247 of file JsonParserGeneratorRK.cpp.
References JsonParserGeneratorRK::jsmntok_t::end, jsmn_alloc_token(), JSMN_ARRAY, JSMN_ERROR_INVAL, JSMN_ERROR_NOMEM, JSMN_ERROR_PART, JSMN_OBJECT, jsmn_parse_primitive(), jsmn_parse_string(), JsonParserGeneratorRK::jsmn_parser::pos, JsonParserGeneratorRK::jsmntok_t::size, JsonParserGeneratorRK::jsmntok_t::start, JsonParserGeneratorRK::jsmn_parser::toknext, JsonParserGeneratorRK::jsmn_parser::toksuper, and JsonParserGeneratorRK::jsmntok_t::type.
Referenced by JsonParser::parse().
                                                    {
    int r;
    int i;
    jsmntok_t *token;
    int count = parser->toknext;
    for (; parser->pos < len && js[parser->pos] != '\0'; parser->pos++) {
        char c;
        jsmntype_t type;
        c = js[parser->pos];
        switch (c) {
            case '{': case '[':
                count++;
                if (tokens == NULL) {
                    break;
                }
                token = jsmn_alloc_token(parser, tokens, num_tokens);
                if (token == NULL)
                    return JSMN_ERROR_NOMEM;
                if (parser->toksuper != -1) {
                    tokens[parser->toksuper].size++;
#ifdef JSMN_PARENT_LINKS
                    token->parent = parser->toksuper;
#endif
                }
                token->type = (c == '{' ? JSMN_OBJECT : JSMN_ARRAY);
                token->start = parser->pos;
                parser->toksuper = parser->toknext - 1;
                break;
            case '}': case ']':
                if (tokens == NULL)
                    break;
                type = (c == '}' ? JSMN_OBJECT : JSMN_ARRAY);
#ifdef JSMN_PARENT_LINKS
                if (parser->toknext < 1) {
                    return JSMN_ERROR_INVAL;
                }
                token = &tokens[parser->toknext - 1];
                for (;;) {
                    if (token->start != -1 && token->end == -1) {
                        if (token->type != type) {
                            return JSMN_ERROR_INVAL;
                        }
                        token->end = parser->pos + 1;
                        parser->toksuper = token->parent;
                        break;
                    }
                    if (token->parent == -1) {
                        if(token->type != type || parser->toksuper == -1) {
                            return JSMN_ERROR_INVAL;
                        }
                        break;
                    }
                    token = &tokens[token->parent];
                }
#else
                for (i = parser->toknext - 1; i >= 0; i--) {
                    token = &tokens[i];
                    if (token->start != -1 && token->end == -1) {
                        if (token->type != type) {
                            return JSMN_ERROR_INVAL;
                        }
                        parser->toksuper = -1;
                        token->end = parser->pos + 1;
                        break;
                    }
                }
                /* Error if unmatched closing bracket */
                if (i == -1) return JSMN_ERROR_INVAL;
                for (; i >= 0; i--) {
                    token = &tokens[i];
                    if (token->start != -1 && token->end == -1) {
                        parser->toksuper = i;
                        break;
                    }
                }
#endif
                break;
            case '\"':
                r = jsmn_parse_string(parser, js, len, tokens, num_tokens);
                if (r < 0) return r;
                count++;
                if (parser->toksuper != -1 && tokens != NULL)
                    tokens[parser->toksuper].size++;
                break;
            case '\t' : case '\r' : case '\n' : case ' ':
                break;
            case ':':
                parser->toksuper = parser->toknext - 1;
                break;
            case ',':
                if (tokens != NULL && parser->toksuper != -1 &&
                        tokens[parser->toksuper].type != JSMN_ARRAY &&
                        tokens[parser->toksuper].type != JSMN_OBJECT) {
#ifdef JSMN_PARENT_LINKS
                    parser->toksuper = tokens[parser->toksuper].parent;
#else
                    for (i = parser->toknext - 1; i >= 0; i--) {
                        if (tokens[i].type == JSMN_ARRAY || tokens[i].type ==
      JSMN_OBJECT) {
                            if (tokens[i].start != -1 && tokens[i].end == -1) {
                                parser->toksuper = i;
                                break;
                            }
                        }
                    }
#endif
                }
                break;
#ifdef JSMN_STRICT
            /* In strict mode primitives are: numbers and booleans */
            case '-': case '0': case '1' : case '2': case '3' : case '4':
            case '5': case '6': case '7' : case '8': case '9':
            case 't': case 'f': case 'n' :
                /* And they must not be keys of the object */
                if (tokens != NULL && parser->toksuper != -1) {
                    jsmntok_t *t = &tokens[parser->toksuper];
                    if (t->type == JSMN_OBJECT ||
                            (t->type == JSMN_STRING && t->size != 0)) {
                        return JSMN_ERROR_INVAL;
                    }
                }
#else
            /* In non-strict mode every unquoted value is a primitive */
            default:
#endif
                r = jsmn_parse_primitive(parser, js, len, tokens, num_tokens);
                if (r < 0) return r;
                count++;
                if (parser->toksuper != -1 && tokens != NULL)
                    tokens[parser->toksuper].size++;
                break;
#ifdef JSMN_STRICT
            /* Unexpected char in strict mode */
            default:
                return JSMN_ERROR_INVAL;
#endif
        }
    }
    if (tokens != NULL) {
        for (i = parser->toknext - 1; i >= 0; i--) {
            /* Unmatched opened object or array */
            if (tokens[i].start != -1 && tokens[i].end == -1) {
                return JSMN_ERROR_PART;
            }
        }
    }
    return count;
}
jsmn_parse_primitive()
static int JsonParserGeneratorRK::jsmn_parse_primitive (jsmn_parser * parser, const char * js, size_t len, jsmntok_t * tokens, size_t num_tokens) [static]
Fills next available token with JSON primitive.
Definition at line 1131 of file JsonParserGeneratorRK.cpp.
References jsmn_alloc_token(), JSMN_ERROR_INVAL, JSMN_ERROR_NOMEM, jsmn_fill_token(), JSMN_PRIMITIVE, and JsonParserGeneratorRK::jsmn_parser::pos.
Referenced by jsmn_parse().
                                                          {
    jsmntok_t *token;
    int start;
    start = parser->pos;
    for (; parser->pos < len && js[parser->pos] != '\0'; parser->pos++) {
        switch (js[parser->pos]) {
#ifndef JSMN_STRICT
            /* In strict mode primitive must be followed by "," or "}" or "]" */
            case ':':
#endif
            case '\t' : case '\r' : case '\n' : case ' ' :
            case ',' : case ']' : case '}' :
                goto found;
        }
        if (js[parser->pos] < 32 || js[parser->pos] >= 127) {
            parser->pos = start;
            return JSMN_ERROR_INVAL;
        }
    }
#ifdef JSMN_STRICT
    /* In strict mode primitive must be followed by a comma/object/array */
    parser->pos = start;
    return JSMN_ERROR_PART;
#endif
found:
    if (tokens == NULL) {
        parser->pos--;
        return 0;
    }
    token = jsmn_alloc_token(parser, tokens, num_tokens);
    if (token == NULL) {
        parser->pos = start;
        return JSMN_ERROR_NOMEM;
    }
    jsmn_fill_token(token, JSMN_PRIMITIVE, start, parser->pos);
#ifdef JSMN_PARENT_LINKS
    token->parent = parser->toksuper;
#endif
    parser->pos--;
    return 0;
}
jsmn_parse_string()
static int JsonParserGeneratorRK::jsmn_parse_string (jsmn_parser * parser, const char * js, size_t len, jsmntok_t * tokens, size_t num_tokens) [static]
Fills next token with JSON string.
Definition at line 1180 of file JsonParserGeneratorRK.cpp.
References jsmn_alloc_token(), JSMN_ERROR_INVAL, JSMN_ERROR_NOMEM, JSMN_ERROR_PART, jsmn_fill_token(), JSMN_STRING, and JsonParserGeneratorRK::jsmn_parser::pos.
Referenced by jsmn_parse().
                                                          {
    jsmntok_t *token;
    int start = parser->pos;
    parser->pos++;
    /* Skip starting quote */
    for (; parser->pos < len && js[parser->pos] != '\0'; parser->pos++) {
        char c = js[parser->pos];
        /* Quote: end of string */
        if (c == '\"') {
            if (tokens == NULL) {
                return 0;
            }
            token = jsmn_alloc_token(parser, tokens, num_tokens);
            if (token == NULL) {
                parser->pos = start;
                return JSMN_ERROR_NOMEM;
            }
            jsmn_fill_token(token, JSMN_STRING, start+1, parser->pos);
#ifdef JSMN_PARENT_LINKS
            token->parent = parser->toksuper;
#endif
            return 0;
        }
        /* Backslash: Quoted symbol expected */
        if (c == '\\' && parser->pos + 1 < len) {
            int i;
            parser->pos++;
            switch (js[parser->pos]) {
                /* Allowed escaped symbols */
                case '\"': case '/' : case '\\' : case 'b' :
                case 'f' : case 'r' : case 'n' : case 't' :
                    break;
                /* Allows escaped symbol \uXXXX */
                case 'u':
                    parser->pos++;
                    for(i = 0; i < 4 && parser->pos < len && js[parser->pos] != '\0'; i++) {
                        /* If it isn't a hex character we have an error */
                        if(!((js[parser->pos] >= 48 && js[parser->pos] <= 57) || /* 0-9 */
                                    (js[parser->pos] >= 65 && js[parser->pos] <= 70) || /* A-F */
                                    (js[parser->pos] >= 97 && js[parser->pos] <= 102))) { /* a-f */
                            parser->pos = start;
                            return JSMN_ERROR_INVAL;
                        }
                        parser->pos++;
                    }
                    parser->pos--;
                    break;
                /* Unexpected symbol */
                default:
                    parser->pos = start;
                    return JSMN_ERROR_INVAL;
            }
        }
    }
    parser->pos = start;
    return JSMN_ERROR_PART;
}