lib/JsonParserGeneratorRK/test/gcclib/spark_wiring_string.cpp File Reference
Copyright (c) 2013-2015 Particle Industries, Inc. All rights reserved. ...mostly rewritten by Paul Stoffregen... Copyright (c) 2009-10 Hernando Barragan. All rights reserved. Copyright 2011, Paul Stoffregen, paul@pjrc.com.
#include `spark_wiring_string.h`
#include <stdio.h>
#include <limits.h>
#include <ctype.h>
#include <stdlib.h>
#include `string_convert.h`
Classes
class StringPrintableHelper
Functions
void dtoa (double val, unsigned char prec, char *sout)
 StringSumHelper & operator+ (const StringSumHelper &lhs, const String &rhs)
 StringSumHelper & operator+ (const StringSumHelper &lhs, const char *cstr)
 StringSumHelper & operator+ (const StringSumHelper &lhs, char c)
 StringSumHelper & operator+ (const StringSumHelper &lhs, unsigned char num)
 StringSumHelper & operator+ (const StringSumHelper &lhs, int num)
 StringSumHelper & operator+ (const StringSumHelper &lhs, unsigned int num)
 StringSumHelper & operator+ (const StringSumHelper &lhs, long num)
 StringSumHelper & operator+ (const StringSumHelper &lhs, unsigned long num)
 StringSumHelper & operator+ (const StringSumHelper &lhs, float num)
 StringSumHelper & operator+ (const StringSumHelper &lhs, double num)
std::ostream & operator<< (std::ostream &os, const String &value)
Detailed Description
Copyright (c) 2013-2015 Particle Industries, Inc. All rights reserved. ...mostly rewritten by Paul Stoffregen... Copyright (c) 2009-10 Hernando Barragan. All rights reserved. Copyright 2011, Paul Stoffregen, paul@pjrc.com.
Author
Mohit Bhoite
Version
V1.0.0
Date
13-March-2013 This library is free software; you can redistribute it and/or modify it under the terms of the GNU Lesser General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
This library is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more details.
You should have received a copy of the GNU Lesser General Public License along with this library; if not, see http://www.gnu.org/licenses/.
Function Documentation
dtoa()
void dtoa (double val, unsigned char prec, char * sout)
Definition at line 39 of file spark_wiring_string.cpp.
References ultoa().
Referenced by String::concat(), and String::String().
                                                       {
    bool negative = val<0;
    if (negative) {
        val = -val;
        *sout++ = '-';
    }
    long scale = 1;
    for (uint8_t i=0; i<prec; i++)
        scale *= 10;
    val *= scale; // capture all the significant digits
    uint64_t fixed = uint64_t(val);
    if ((val-fixed)>=0.5) // round last digit
        fixed++;
    unsigned long first = (unsigned long)(fixed / scale);
    unsigned long second = (unsigned long)(fixed % scale);
    ultoa(first, sout, 10, 1);
    if (prec) {
        sout += strlen(sout);
        *sout++ = '.';
        ultoa(second, sout, 10, prec);
    }
}
operator+() [1/10]
 StringSumHelper& operator+ (const StringSumHelper & lhs, const String & rhs)
Parameters
lhs The string to append to. String lhs is not modified.
rhs The value to append.
Returns
the combined string
Definition at line 359 of file spark_wiring_string.cpp.
References String::buffer, String::concat(), String::invalidate(), and String::len.
{
    StringSumHelper &a = const_cast<StringSumHelper&>(lhs);
    if (!a.concat(rhs.buffer, rhs.len)) a.invalidate();
    return a;
}
operator+() [2/10]
 StringSumHelper& operator+ (const StringSumHelper & lhs, const char * cstr)
Parameters
lhs The string to append to. String lhs is not modified.
cstr The value to append.
Returns
the combined string
Definition at line 366 of file spark_wiring_string.cpp.
References String::concat(), and String::invalidate().
{
    StringSumHelper &a = const_cast<StringSumHelper&>(lhs);
    if (!cstr || !a.concat(cstr, strlen(cstr))) a.invalidate();
    return a;
}
operator+() [3/10]
 StringSumHelper& operator+ (const StringSumHelper & lhs, char c)
Parameters
lhs The string to append to. String lhs is not modified.
c The character to append
Returns
the combined string
Definition at line 373 of file spark_wiring_string.cpp.
References String::concat(), and String::invalidate().
{
    StringSumHelper &a = const_cast<StringSumHelper&>(lhs);
    if (!a.concat(c)) a.invalidate();
    return a;
}
operator+() [4/10]
 StringSumHelper& operator+ (const StringSumHelper & lhs, unsigned char num)
Parameters
lhs The string to append to. String lhs is not modified.
num The value to append.
Returns
the combined string
Definition at line 380 of file spark_wiring_string.cpp.
References String::concat(), and String::invalidate().
{
    StringSumHelper &a = const_cast<StringSumHelper&>(lhs);
    if (!a.concat(num)) a.invalidate();
    return a;
}
operator+() [5/10]
 StringSumHelper& operator+ (const StringSumHelper & lhs, int num)
Parameters
lhs The string to append to. String lhs is not modified.
num The value to append.
Returns
the combined string
Definition at line 387 of file spark_wiring_string.cpp.
References String::concat(), and String::invalidate().
{
    StringSumHelper &a = const_cast<StringSumHelper&>(lhs);
    if (!a.concat(num)) a.invalidate();
    return a;
}
operator+() [6/10]
 StringSumHelper& operator+ (const StringSumHelper & lhs, unsigned int num)
Parameters
lhs The string to append to. String lhs is not modified.
num The value to append.
Returns
the combined string
Definition at line 394 of file spark_wiring_string.cpp.
References String::concat(), and String::invalidate().
{
    StringSumHelper &a = const_cast<StringSumHelper&>(lhs);
    if (!a.concat(num)) a.invalidate();
    return a;
}
operator+() [7/10]
 StringSumHelper& operator+ (const StringSumHelper & lhs, long num)
Parameters
lhs The string to append to. String lhs is not modified.
num The value to append.
Returns
the combined string
Definition at line 401 of file spark_wiring_string.cpp.
References String::concat(), and String::invalidate().
{
    StringSumHelper &a = const_cast<StringSumHelper&>(lhs);
    if (!a.concat(num)) a.invalidate();
    return a;
}
operator+() [8/10]
 StringSumHelper& operator+ (const StringSumHelper & lhs, unsigned long num)
Parameters
lhs The string to append to. String lhs is not modified.
num The value to append.
Returns
the combined string
Definition at line 408 of file spark_wiring_string.cpp.
References String::concat(), and String::invalidate().
{
    StringSumHelper &a = const_cast<StringSumHelper&>(lhs);
    if (!a.concat(num)) a.invalidate();
    return a;
}
operator+() [9/10]
 StringSumHelper& operator+ (const StringSumHelper & lhs, float num)
Parameters
lhs The string to append to. String lhs is not modified.
num The value to append.
Returns
the combined string
Definition at line 415 of file spark_wiring_string.cpp.
References String::concat(), and String::invalidate().
{
    StringSumHelper &a = const_cast<StringSumHelper&>(lhs);
    if (!a.concat(num)) a.invalidate();
    return a;
}
operator+() [10/10]
 StringSumHelper& operator+ (const StringSumHelper & lhs, double num)
Parameters
lhs The string to append to. String lhs is not modified.
num The value to append.
Returns
the combined string
Definition at line 422 of file spark_wiring_string.cpp.
References String::concat(), and String::invalidate().
{
    StringSumHelper &a = const_cast<StringSumHelper&>(lhs);
    if (!a.concat(num)) a.invalidate();
    return a;
}
operator<<()
std::ostream& operator<< (std::ostream & os, const String & value)
Definition at line 807 of file spark_wiring_string.cpp.
References String::c_str().
                                                                {
    os << '"' << value.c_str() << '"';
    return os;
}