lib/JsonParserGeneratorRK/test/gcclib/string_convert.h File Reference
Functions
char * ltoa (long N, char *str, int base)
char * ultoa (unsigned long a, char *buffer, int radix, char pad=1)
char * utoa (unsigned a, char *buffer, int radix)
char * itoa (int a, char *buffer, int radix)
Function Documentation
itoa()
char* itoa (int a, char * buffer, int radix)
Definition at line 4 of file helpers.cpp.
Referenced by String::concat(), and String::String().
                                               {
    if (base == 16) {
        sprintf(str, "%x", value);
    }
    else
    if (base == 8) {
        sprintf(str, "%o", value);
    }
    else {
        sprintf(str, "%d", value);
    }
    return str;
}
ltoa()
char* ltoa (long N, char * str, int base)
Referenced by String::concat(), and String::String().
ultoa()
char* ultoa (unsigned long a, char * buffer, int radix, char pad = 1)
Referenced by String::concat(), dtoa(), and String::String().
utoa()
char* utoa (unsigned a, char * buffer, int radix)
Referenced by String::concat(), and String::String().